### ISSUE TITLE
[Feature] 增加自定义geosite更新地址，并自动更新

### ISSUE THREAD

**Issue by yubanmeiqin9048** [juewuy/ShellCrash#337]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

![图片](https://user-images.githubusercontent.com/64676973/223985484-1b0a2ab4-4d9e-47d3-bf23-360beaf84321.png)

**Comment by juewuy** [comment]
暂时不会考虑

**Comment by juewuy** [comment]
https://github.com/juewuy/ShellCrash/commit/85547ab863a7ffea47fe6b96e29d183ba2756c92
自动更新可以参考
https://github.com/DustinWin/ruleset_geodata/
