### ISSUE TITLE
[Bug] IPv6的劫持偶尔会失败

### ISSUE THREAD

**Issue by Karmylr** [juewuy/ShellCrash#436]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

![image](https://github.com/juewuy/ShellClash/assets/69903376/d4978100-b42a-402f-8d0b-c026b20c20fb)

使用nft混合模式。刚启动时一切正常，IPv6的流量会经过clash。但是过几个小时，所有IPv6流量就都不会经过clash。打开`https://6.ipw.cn/`显示的是设备的地址而不是路由器的

**Comment by juewuy** [comment]
检查是否是其他应用重置了防火墙

**Comment by Karmylr** [comment]
> 检查是否是其他应用重置了防火墙

固件是自己构建的，只有shellclash。能不能像OpenClash那样检测到防火墙重启就自动重置防火墙规则？
![image](https://github.com/juewuy/ShellClash/assets/69903376/b9544378-7ff4-48bb-8a1c-0d8c5c0afb02)

**Comment by juewuy** [comment]
这需要添加一个持续性的定时任务，有待考虑

**Comment by juewuy** [comment]
https://github.com/juewuy/ShellCrash/commit/85547ab863a7ffea47fe6b96e29d183ba2756c92
