### ISSUE TITLE
[Bug] 路由器中安装证书失败

### ISSUE THREAD

**Issue by mumaxiaozi** [juewuy/ShellCrash#490]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

在小米路由器 r3p 安装证书失败。
安装过程提示是成功的，但是使用后总是提示 
```connect error: tls: failed to verify certificate: x509: certificate signed by unknown authority```
经过排查，发现是缺少证书的问题，使用 shellclash 根据提示明明显示 证书安装成功了
后来查看脚本，发现证书会安装到 /etc/ssl/certs/ 目录下，但是看 ssl 及 certs 目录都不存在呢
至于目录为啥不存在我也不太了解，于是手动创建目录，再次执行可成功安装证书。clash 运行也正常了。

根据现有脚本执行
变量 crtdir 在 setcrt 中声明，实际的值为 /etc/ssl/certs/ca-certificates.crt
```
[ -z "$openssldir" ] && openssldir=/etc/ssl
if [ -n "$openssldir" ];then
    crtdir="$openssldir/certs/ca-certificates.crt"
```
后面 crtdir 的是否存在判断只是为了判断证书是否存在，要覆盖的逻辑，而目录是否存在没有理会
当目录不存在时，于是在 getcrt 执行 mv ，及 exprot 时都是失败的，即使提示成功了
```
mv -f $TMPDIR/ca-certificates.crt $crtdir
$clashdir/start.sh webget $TMPDIR/ssl_test https://baidu.com echooff rediron skipceroff
if [ "$?" = "1" ];then
	export CURL_CA_BUNDLE=$crtdir
	echo "export CURL_CA_BUNDLE=$crtdir" >> /etc/profile
fi
rm -rf $TMPDIR/ssl_test
echo -e "\033[32m证书安装成功！\033[0m"
```

是否可考虑
如下三种解决方案：
1、新增一个变量声明为如 crtpath=/etc/ssl/certs， 判断它是否存在，不存在就创建这个目录后，再执行 getcrt 用于 copy 证书 和 export
2、通过新增的 crtpath 判断如果不存在中断本次操作，提示用户手动创建目录再安装证书
3、在 mv 时获取不成功提示信息，一种是来用户明确提示手动创建，异或自动创建目录继续往下执行 都是可以的

**Comment by mumaxiaozi** [comment]
> @mumaxiaozi 嗯，mkdir一下就可以了，没想到小米连这个都省

是的，非常省，没有curl、wget-ssl、openssl、yum、opkg，好像是个 busy-box 套件工具包。
搞的我一顿操作猛如虎，安装了 curl、wget-ssl、openssl、opkg，安了个证书去了 /opt/etc/ssl 中
结果还是x509。
希望可以脚本完成 mkdir 操作，免的其他人也头大 。🤦‍♂️

**Comment by juewuy** [comment]
https://github.com/juewuy/ShellClash/commit/9a982fd78be0576438e9fb947e97571c141082f1
