### ISSUE TITLE
[Bug] TCP协议的DNS请求无法被代理

### ISSUE THREAD

**Issue by aixia715** [juewuy/ShellCrash#492]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

脚本只重定向了UDP协议的DNS请求，但是实际使用的过程中发现有TCP协议的DNS请求，如下图
![image](https://github.com/juewuy/ShellClash/assets/26791215/7aab17c0-d076-4b09-9e5b-3970b25de45a)

我手动运行了下面的指令即可正常访问
```bash
iptables -t nat -A clash_dns -p tcp -j REDIRECT --to 1053
iptables -t nat -I PREROUTING -p tcp --dport 53 -j clash_dns
```

是否可以将这两个指令添加到脚本中？谢谢

**Comment by juewuy** [comment]
@aixia715 很奇怪的请求，是浏览器原因吗？

**Comment by aixia715** [comment]
有可能，我windows的edge有这个问题，手机上的edge没有问题

**Comment by wray-lee** [comment]
确实windows的edge存在这个问题

**Comment by TanMusong** [comment]
之前一直有MEGA Windows客户端连接失败，浏览器访问正常的问题。刚死马当活马医试了下issues中的指令，MEGA客户端可以正常连接了，看来MEGA客户端有可能也是TCP协议的DNS请求

**Comment by BaffinLee** [comment]
Chrome 119 最新版也会用 TCP 发 DNS 请求，求支持

**Comment by juewuy** [comment]
新版已添加
