### ISSUE TITLE
[Bug] rm2100配置是128M闪存和128M内存的~可安装的时候提示检测到你的安装目录空间不足10M，是否开启小闪存模式？

### ISSUE THREAD

**Issue by xinzhongyouhai** [juewuy/ShellCrash#494]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

[Bug] rm2100配置是128M闪存和128M内存的~可安装的时候提示检测到你的安装目录空间不足10M，是否开启小闪存模式？

求解决方案~

**Comment by xinzhongyouhai** [comment]
[RM2100 /home/root]# df -h
Filesystem                Size      Used Available Use% Mounted on
rootfs                   13.6M     13.6M         0 100% /
/dev/root                13.6M     13.6M         0 100% /
tmpfs                     8.0K         0      8.0K   0% /dev
tmpfs                     9.0M      2.4M      6.6M  26% /etc
tmpfs                     1.0M      4.0K   1020.0K   0% /home
tmpfs                     8.0K         0      8.0K   0% /media
tmpfs                     8.0K         0      8.0K   0% /mnt
tmpfs                    61.0M      1.7M     59.3M   3% /tmp
tmpfs                     4.0M     84.0K      3.9M   2% /var
tmpfs                    61.0M      1.7M     59.3M   3% /sbin/wgetcurl.sh
tmpfs                    61.0M      1.7M     59.3M   3% /opt
tmpfs                    61.0M      1.7M     59.3M   3% /www/Advanced_Extensions_app07.asp
tmpfs                    61.0M      1.7M     59.3M   3% /www/Advanced_Extensions_app08.asp
tmpfs                    61.0M      1.7M     59.3M   3% /www/Advanced_Extensions_app22.asp
tmpfs                    61.0M      1.7M     59.3M   3% /www/Advanced_Extensions_app27.asp
tmpfs                    61.0M      1.7M     59.3M   3% /www/Advanced_Extensions_app21.asp
tmpfs                    61.0M      1.7M     59.3M   3% /www/Advanced_Extensions_app24.asp
tmpfs                    61.0M      1.7M     59.3M   3% /www/Advanced_Extensions_app11.asp
tmpfs                    61.0M      1.7M     59.3M   3% /www/Advanced_Extensions_app14.asp
tmpfs                    61.0M      1.7M     59.3M   3% /www/Advanced_Extensions_app16.asp
tmpfs                    61.0M      1.7M     59.3M   3% /www/Advanced_Extensions_app09.asp
tmpfs                    61.0M      1.7M     59.3M   3% /www/Advanced_Extensions_app10.asp
tmpfs                    61.0M      1.7M     59.3M   3% /www/Advanced_Extensions_app20.asp
tmpfs                    61.0M      1.7M     59.3M   3% /www/Advanced_Extensions_app12.asp
tmpfs                    61.0M      1.7M     59.3M   3% /www/Advanced_Extensions_app13.asp
tmpfs                    61.0M      1.7M     59.3M   3% /www/Advanced_Extensions_app15.asp
tmpfs                    61.0M      1.7M     59.3M   3% /www/Advanced_Extensions_app23.asp
tmpfs                    61.0M      1.7M     59.3M   3% /www/Advanced_Extensions_app17.asp
tmpfs                    61.0M      1.7M     59.3M   3% /www/Advanced_Extensions_app01.asp
tmpfs                    61.0M      1.7M     59.3M   3% /www/Advanced_Extensions_app19.asp
tmpfs                    61.0M      1.7M     59.3M   3% /www/Advanced_Extensions_app02.asp
tmpfs                    61.0M      1.7M     59.3M   3% /www/Advanced_Extensions_app03.asp
tmpfs                    61.0M      1.7M     59.3M   3% /www/Advanced_Extensions_app25.asp
tmpfs                    61.0M      1.7M     59.3M   3% /www/Advanced_Extensions_app04.asp
tmpfs                    61.0M      1.7M     59.3M   3% /www/Advanced_Extensions_app05.asp
tmpfs                    61.0M      1.7M     59.3M   3% /www/Advanced_Extensions_app06.asp
tmpfs                    61.0M      1.7M     59.3M   3% /www/Advanced_Extensions_app18.asp
tmpfs                    61.0M      1.7M     59.3M   3% /www/Advanced_Extensions_app26.asp
tmpfs                    61.0M      1.7M     59.3M   3% /www/Advanced_Extensions_app28.asp

**Comment by juewuy** [comment]
@xinzhongyouhai 正常，可以刷padavan

**Comment by xinzhongyouhai** [comment]
就是刷的padavan.padavan不像OP,不能选择安装的目录~只能安装在目标目录/etc/storage空间剩余：6.8M，而OP是可以选择其他目录安装的~

**Comment by juewuy** [comment]
@xinzhongyouhai 那可能是刷的固件有问题，正常应该有不少富余

**Comment by juewuy** [comment]
@xinzhongyouhai 建议去chongshengb的项目自己编译，可以自定义插件

**Comment by xinzhongyouhai** [comment]
自己编译可以调整安装目录啊？能调整/tmp 或者/etc目录大小啊？
