### ISSUE TITLE
[Feature] UDP流量进入Clash内核，但是是DIRECT，此时的速度理论上能否比肩没进入内核时的速度？

### ISSUE THREAD

**Issue by chuwza** [juewuy/ShellCrash#496]
大佬好，官方OpenWrt 22.03.5，ShellClash 1.8.0。开了Nft混合+redir_host

我知道Clash代理UDP很坑，这也是为什么要开禁用443端口QUIC，禁用之后YouTube才能流畅播放。所以我干脆用Nft基础，不代理UDP，这种情况下，是UDP的淘宝直播流量根本没进入Clash内核，所以流畅播放。

但是我最近需要使用Nft混合，开了之后发现淘宝直播会卡顿，进入WebUI发现淘宝直播流量进入Clash内核了。（不过依靠规则，淘宝流量是DIRECT的，如图）
![屏幕截图(312)zz](https://github.com/juewuy/ShellClash/assets/30049891/533d0089-6a92-4f14-bbda-5b1126c927d6)

我的疑问就是，理论上，进入Clash内核但是是DIRECT的话，是不是就能做到相当于没进入Clash内核那样快的？还是说，就算了DIRECT，只要进入Clash内核了，就会慢一点，淘宝直播卡顿的原因就是代理了UDP？（淘宝直播的端口是1106，ShellClash没有禁用这个端口UDP的选项）

**Comment by juewuy** [comment]
@chuwza 比不了，防火墙对udp转发无论是tun还是tproxy性能都很一般
除非使用socks5

**Comment by chuwza** [comment]
> @chuwza 比不了，防火墙对udp转发无论是tun还是tproxy性能都很一般 除非使用socks5

好的，感谢
