### ISSUE TITLE
[Bug]  无法访问观看NHK plus的电视节目

### ISSUE THREAD

**Issue by ntdsir** [juewuy/ShellCrash#499]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

无法访问观看NHK plus的电视节目https://plus.nhk.jp/watch/ch/g1
使用同样的VPN线路（必须是日本线路），用clash的windows客户端，使用日本的线路时可以访问。
麻烦告知如何设置才能实现正常访问观看nhk plus的电视节目。谢谢！

**Comment by juewuy** [comment]
@ntdsir 6-6自行添加规则
