### ISSUE TITLE
[Bug] shellclash运行一段时间后，其他机器无法访问

### ISSUE THREAD

**Issue by TylerKernel** [juewuy/ShellCrash#505]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

环境：
ubuntu22.04
ShellClash 1.8.1 Nft混合模式，代理本机流量

复现：
在shellclash运行一段时间后（1天左右），本机可以正常使用，在yacd的连接中可以正常看到相应的连接信息，但是局域网内的其他机器均无法访问，会在hang住一段时间后，提示返回值为空。

临时解决方案：
使用ShellClash重启clash服务后，恢复正常，本机和局域网其他机器均可以正常使用

**Comment by juewuy** [comment]
@TylerKernel 防火墙被其他进程重置了
