### ISSUE TITLE
[Bug] 小米R2D启动shellclash@1.8.1提示错误信息: awk: bad regex ':\{"': Unmatched {

### ISSUE THREAD

**Issue by hwbest** [juewuy/ShellCrash#506]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

RT, 原因是小米R2D的awk版本太老了, 不能支持`awk -F ':\\{"'`, 报错信息如下
`awk: bad regex ':\{"': Unmatched {`

我已经在原始的修改提交上加了comment, 并且提供了更多信息:
https://github.com/juewuy/ShellClash/commit/e5e2e873c99963eec48e7fa2421a1c28fcaaf30f

请问是否可以修改成 `awk -F ':\{"'`, 去掉一个斜杠
这样在高版本和低版本的awk都能支持运行

不过在高版本的awk上, 会有warning信息:
`awk: warning: escape sequence `\{' treated as plain `{'`

理论上, 斜杠都去掉, ubuntu20.04也支持 `awk -F ':{"'`, 不过都去掉后, 小米R2D也会报错
`awk: bad regex ':{"': Unmatched \{`

所以为了兼容, 还是得保留一个斜杠:
`awk -F ':\{"'`

另外一种思路是根据awk的版本号来用不同的字符串分隔?

谢谢

**Comment by juewuy** [comment]
两个斜杠可能是因为确实要以斜杠为分隔符，如果一个斜杠，则不会以斜杠做分隔符

**Comment by juewuy** [comment]
改成 sed 's/:{/!/g' | awk -F '!' '{for(i=1;i<=NF;i++) print $i}'  解决

**Comment by juewuy** [comment]
https://github.com/juewuy/ShellCrash/commit/9f0a2f8e1a8f176445110411ff22fceeafb26955
