### ISSUE TITLE
[Bug] 开启公网访问后无法修改用户名密码

### ISSUE THREAD

**Issue by chinazyq123** [juewuy/ShellCrash#508]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

开启代理公网访问后，找不到菜单无法修改用户名密码

**Comment by juewuy** [comment]
6-6
