### ISSUE TITLE
[Bug] 红米 AX6000，ShellClash 3 天左右不重启，科学上网就挂掉了

### ISSUE THREAD

**Issue by 77321660** [juewuy/ShellCrash#509]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

红米 AX6000，ShellClash 3 天左右不重启，科学上网就挂掉了，重启后恢复正常，请问是什么原因？有解决办法吗？

**Comment by juewuy** [comment]
@77321660 设置定时重启

**Comment by jinge1936** [comment]
你如果是subscription的话 记得 设置自动更新 订阅。

**Comment by juewuy** [comment]
@jinge1936 可以设置自动重启

**Comment by CarlosLucky** [comment]
shellclash目前我的红米ax6s也彻底用不来了，之前还能在线更新配置自动下载，后来在线更新挂了，我改用本地配置文件，勉强能用，就在刚刚本地都不行了，我测试了我的配置地址都是没有问题的，手机上用app可以正常上网，于是乎之能黑群晖里临时挂一个istoreos里面配置了一个openclash。。。。。。做旁路由还能活下去。。。。。。（不知道能不能这样讲，不方便的话可以把我的话删了）

**Comment by juewuy** [comment]
@CarlosLucky 没遇见你说的问题，尝试更新脚本及内核
