### ISSUE TITLE
[Bug] 配置文件覆写会删掉yaml锚点的配置

### ISSUE THREAD

**Issue by mengshouer** [juewuy/ShellCrash#511]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

就比如 [clash meta wiki](https://wiki.metacubex.one/example/#_2) 给的配置文件就无法使用

**Comment by juewuy** [comment]
6-6里看说明
