### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by yoohooyoo** [juewuy/ShellCrash#512]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

一直正常使用，重新安装后，反复提示：
mv: can't rename '/tmp/ShellClash/clash_config_root.yaml': No such file or directory
即使配置文件已经完整下载。

**Comment by juewuy** [comment]
无法复现，可以尝试更新脚本
