### ISSUE TITLE
[Bug] 为什么我用cloudflare workers搭建的vless节点导入shellclash后没策略信息，只在手动选择里面看到？

### ISSUE THREAD

**Issue by qq6510** [juewuy/ShellCrash#513]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [x]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

为什么我用cloudflare workers搭建的vless反代节点导入shellclash后没策略信息，只在手动选择里面看到？
wireguard节点可以导入shellclash吗？

**Comment by qq6510** [comment]
各位大佬帮忙回答一下

**Comment by qq6510** [comment]
> @qq6510 1规则问题 2可以

配置策略的在线模板可以手动替换吗？我比较喜欢分流的那个模板，但是油管没有手动选择，手动选择自己建的vless网速快。

**Comment by qq6510** [comment]
> wireguard

还有用cloudflare zerotrust建的wireguard节点用那个1在线生成直接导入不报错吗？

**Comment by juewuy** [comment]
@qq6510 你可以用6-2或者6-6

**Comment by qq6510** [comment]
> @qq6510 你可以用6-2或者6-6

谢谢大佬
