### ISSUE TITLE
[Bug] 更新内核后提示安装目录空间不足

### ISSUE THREAD

**Issue by CapQ227** [juewuy/ShellCrash#515]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

您好，不好意思来打扰。
我是小米AX3600路由，之前一直用shellclash很稳定，最近没事就在菜单里点了升级内核，结果开始提示空间不足10M，安装目录空间不足，问是否开启小闪存模式。因为最早使用时并没有提示空间不足，我怀疑是不是老版本有残留文件在路由内？总之目前无论更新还是回退，都会提示空间不足。安装后shellclash也不如以前稳定，不知道是否有啥解决办法？
谢谢。

**Comment by juewuy** [comment]
@CapQ227 可以更换其他内核

**Comment by CapQ227** [comment]
> @CapQ227 可以更换其他内核

我更换1.5.1和1.7都提示安装目录空间不足，不足10M，是可以忽视吗？不知道不稳定是不是因为空间的原因。我安装面板时就提示只有8M空间了。。。

**Comment by juewuy** [comment]
可以尝试卸载重装
