### ISSUE TITLE
[Feature] 订阅的节点能够设置自动更新，那么节点测速是不是也能自动更新？shellclash使用的自动节点万一挂了，它会怎么办？

### ISSUE THREAD

**Issue by qq6510** [juewuy/ShellCrash#516]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

shellclash使用的自动选择节点万一挂了，它会怎么办？
节点测速是不是也能自动更新，需要怎么设置？

**Comment by juewuy** [comment]
@qq6510 这是clash最基础的知识，请善用搜索引擎

**Comment by qq6510** [comment]
> @qq6510 这是clash最基础的知识，请善用搜索引擎

谢谢
