### ISSUE TITLE
[Feature] 苹果服务中TV部分是否可以单独分出来

### ISSUE THREAD

**Issue by zekirin70** [juewuy/ShellCrash#517]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

你好，我目前使用红米AX6000安装shellclash，并且使用美区 appleID 观看 AppleTV+ 的影视资源，然而当苹果服务选择直连时，AppleTV 无法正常观看，当选择代理时，TV可以看，但 App Store 又无法正常打开。

所以请问，是否可以把 TV 的代理选项和其他苹果服务分开，谢谢。

**Comment by zekirin70** [comment]
按照常见问题中的路径没有找到修改规则的【进阶设置-自定义配置】

**Comment by qq6510** [comment]
> 按照常见问题中的路径没有找到修改规则的【进阶设置-自定义配置】

6-2可以的，上传可以的，但是要编辑规则模板。下载安装包，找rules，ini文件，去研究吧！我废了好大劲才设好

**Comment by juewuy** [comment]
6-6
