### ISSUE TITLE
[Feature] 请升级一下Meta的版本

### ISSUE THREAD

**Issue by finch-ift** [juewuy/ShellCrash#519]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

最新版本的Meta支持了[Hysteria 2](https://v2.hysteria.network/) 我需要这个新协议，所以请同步升级上游Meta版本

**Comment by juewuy** [comment]
@finch-ift 自定义内核功能里有alpha版本
