### ISSUE TITLE
[Bug]  0ip: can't find device 'utun' ip: can't find device 'utun'

### ISSUE THREAD

**Issue by QuentinHsu** [juewuy/ShellCrash#520]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

设备：FriendlyElec NanoPi R2S

ShellClash：1.8.1

当在 ShellClash 设置 `Clash运行模式` 为 `混合模式` 时，报错，无法正常代理

<img width="892" alt="image" src="https://github.com/juewuy/ShellClash/assets/21162238/72ef4529-dc2f-4de7-ae30-289213a66a6c">

```
ip: can't find device 'utun'
ip: can't find device 'utun'
```

**Comment by juewuy** [comment]
@QuentinHsu 请确认设备是否拥有tun内核模块

**Comment by longyiqiang** [comment]
> @QuentinHsu 请确认设备是否拥有tun内核模块

出现同样情况
<img width="1195" alt="image" src="https://github.com/juewuy/ShellClash/assets/49137171/d737939f-1ad6-4edf-a098-1d245e3ad344">
已经安装模块，设备为r4s

**Comment by juewuy** [comment]
尝试切换premium内核

**Comment by longyiqiang** [comment]
> 尝试切换premium内核

两个都试过了，之前还是可以的，不知道哪个版本后就不行了。

**Comment by juewuy** [comment]
@longyiqiang 尝试重启设备，或者检查是否有加速器服务产生冲突

**Comment by QuentinHsu** [comment]
> @QuentinHsu 请确认设备是否拥有 tun 内核模块

最开始无，但我手动装了后，不报该错了。但是无法代理成功了。

**Comment by juewuy** [comment]
@QuentinHsu 那应该还是固件相关问题

**Comment by longyiqiang** [comment]
> @QuentinHsu 那应该还是固件相关问题

已经查明了是/etc/passwd中配置的路径与实际不同，修改后就可以了
修改前：
`shellclash:x:0:7890::/home/shellclash:`
修改后：
`shellclash:x:0:7890::/etc/clash:`
应该是这样没错，修改后我的utun设备创建成狗并且tun模式成功代理网络。
@juewuy 大佬可以看看是否是这么一回事。
