### ISSUE TITLE
求助，核心安装不成功

### ISSUE THREAD

**Issue by blusunny** [juewuy/ShellCrash#524]
ax3600官方固件
在线安装
<img width="276" alt="微信截图_20231104210922" src="https://github.com/juewuy/ShellCrash/assets/16484019/93c117d6-979c-4d2a-97e7-b3c4073fe6bd">

本地安装
<img width="297" alt="微信截图_20231104210857" src="https://github.com/juewuy/ShellCrash/assets/16484019/3289fe8e-89f3-425c-a43f-3bddef4b4222">

**Comment by juewuy** [comment]
@blusunny 内存不足，用老版本meta或者其他内核
