### ISSUE TITLE
meta核心无法同时打开混合模式+fakeIP

### ISSUE THREAD

**Issue by LostSmoch** [juewuy/ShellCrash#525]
tun或者混合模式+fakeIP都会导致路由器直接断网，应该是bug，bug可以接受，但是目的没有达成，所以来此请教，如何访问必应的new bing呢？
三种内核的多种组合都试过之后发现，主要就是fakeIP，用redirhost的时候是绝对打不开NewBing的，虽然clash pre混合模式+fakeip的组合可以访问NewBing，也可以科学，但是游戏加速器又不行了，搜索了之后发现是fakeip和游戏加速器不兼容，所以请问如何在redirhost的模式下打开NewBing可行吗？怎么操作呢，搜了一圈也没找到这两个关键词的贴子

**Comment by juewuy** [comment]
@LostSmoch 先参考常见问题，排查断网原因

**Comment by LostSmoch** [comment]
> @LostSmoch 先参考常见问题，排查断网原因

之前问过newbing，找了一圈也没找到排查到问题，但实际上我现在不是很在意断网这个问题，最重的是New Bing和加速器共存的方法，请问如何操作

**Comment by juewuy** [comment]
@LostSmoch 混合模式不兼容内置加速器

**Comment by LostSmoch** [comment]
> @LostSmoch 混合模式不兼容内置加速器

我不是这个意思，我现在只是想知道如何让newbing和加速器共存，而且我加速器不是在路由器上的，是装在设备上，其实我不在乎到底用混合模式还是tun还是redir

**Comment by juewuy** [comment]
@LostSmoch 请参考面板日志排查

**Comment by juewuy** [comment]
@LostSmoch 默认重启时就会同步节点选择

**Comment by LostSmoch** [comment]
> @LostSmoch 默认重启时就会同步节点选择

这个设置为什么和其他两个内核不一样，这个能改吗

**Comment by juewuy** [comment]
没有不一样，机制都是相同的

**Comment by LostSmoch** [comment]
> 没有不一样，机制都是相同的

佬儿，你就直说该咋办好不，有一搭没一搭的，都聊了三四天了

**Comment by juewuy** [comment]
@LostSmoch 我不知道你是否禁用了配置文件覆写，如果是的话，请自行解决问题，否则可能是bug

**Comment by LostSmoch** [comment]
> @LostSmoch 我不知道你是否禁用了配置文件覆写，如果是的话，请自行解决问题，否则可能是bug

没禁用，那看来是bug了，多谢，告辞，我重装试试

**Comment by evilyao** [comment]
> > @LostSmoch 请参考面板日志排查
> 
> 找到原因了，实际上meta内核的redir模式+redir默认组合就已经可以让bingai和加速器共存，但是每次重启clash服务都会初始化配置文件，导致每天我访问bingai时候的节点都是direct。 用的是我自己的配置链接，不知道是不是自定义链接的格式问题导致每次更新配置文件不能合并，但是我确定了只有meta内核才有这个问题。 所以现在的问题变成了如何让meta内核重启服务之后能保留已选择的节点信息，诚心求教，我已经找过了issue，貌似没有发现这个问题

我的可非得混合模式＋fake-ip模式才能访问copilot和chatgpt。默认的那种组合不行。

**Comment by juewuy** [comment]
@evilyao 规则问题请更换规则模板，或者使用自定义规则时提供相关报错
