### ISSUE TITLE
openwrt 23.05下,使用nftables设置本机代理服务出现报错

### ISSUE THREAD

**Issue by thisdk** [juewuy/ShellCrash#529]
作者你好,首先感谢写出这么好用的工具,现在我在使用的时候出现一个问题

### 虽然出现问题,但是不影响使用

下面是我的设置

 1 切换Clash运行模式: 	Nft混合
 2 切换DNS运行模式：	redir_host
 3 跳过本地证书验证：	未开启   ————解决节点证书验证错误
 4 只代理常用端口： 	未开启   ————用于过滤P2P流量
 5 过滤局域网设备：	未开启   ————使用黑/白名单进行过滤
 6 设置本机代理服务:	已开启   ————使本机流量经过clash内核 -> 使用nftables增强模式配置(支持docker,推荐！)
 7 屏蔽QUIC流量:	已启用   ————优化视频性能
 8 CN_IP绕过内核:	未开启   ————优化性能，不兼容Fake-ip

 1 ipv6相关
 3 配置公网及局域网防火墙
 4 启用域名嗅探:	已启用	————用于流媒体及防DNS污染
 5 启用节点绕过:	未启用	————用于防止多设备多重流量
 6 配置内置DNS服务	已禁用

 1 修改基础DNS
 2 修改Fallback_DNS
 3 重置DNS配置
 4 一键配置加密DNS
 5 hosts优化：  	已开启	————调用本机hosts并劫持NTP服务
 6 Dnsmasq转发：	未开启	————不推荐使用
 7 禁用DNS劫持：	已禁用	————取消劫持局域网53端口

仅上面的设置,我的用意是,使用mosdns作为dns请求的工具,shellclash作为代理

但是这样设置,会出现一个报错.

```
Error: syntax error, unexpected return
add rule inet shellclash dns_out meta skgid 453 7890 return
```

经过查看是这行代码出问题了

```
nft add rule inet shellclash dns_out meta skgid {453,7890} return
```

奈何我没办法修复该命令.希望作者有空可以修复一下

**Comment by lambdaplus** [comment]
解决了吗？

**Comment by thisdk** [comment]
> 解决了吗？

因为不影响使用,且我使用了mosdns作为dns解析工具,所以我手动把这几行代码删除了..正常做法应该是判断是否开启DNS解析,如果没开启则不执行才是

**Comment by juewuy** [comment]
@thisdk https://github.com/juewuy/ShellCrash/commit/74bfde8eb109ec1b851e25e56c42edb9a28d88e8

**Comment by thisdk** [comment]
> @thisdk [74bfde8](https://github.com/juewuy/ShellCrash/commit/74bfde8eb109ec1b851e25e56c42edb9a28d88e8)

作者太棒了.我又可以更新新版使用了!!!!!
