### ISSUE TITLE
如何设定 BT 不走 Crash ？

### ISSUE THREAD

**Issue by yamazakitouma** [juewuy/ShellCrash#534]
我使用红米 AX6000 安装 Shell Crash ，然后有一台群晖 NAS 进行 BT 下载，但是目前好像 BT 访问 tracker 服务器也会走梯子，导致提示 could not connect to tracker 无法访问到标记服务器，我想问下，怎么能设定，让 NAS 的 BT 软件不走代理，但 NAS 本身还走代理？（因为我的 Docker 还要访问 Hub）

**Comment by juewuy** [comment]
bt跑在虚拟机里，网卡模式桥接，之后用局域网过滤功能过滤掉此虚拟机

**Comment by yamazakitouma** [comment]
刚才看到大佬的说明文档，只代理常用端口是否也是一种解决办法？

**Comment by juewuy** [comment]
@yamazakitouma tracker服务器不一定会被过滤

**Comment by yamazakitouma** [comment]
昨天回家自行尝试了下，得到了以下结论

1. 仅开启常用端口翻墙 - 无效（发现默认就是开启的）
2. 通过黑名单功能，将 Docker 中创建的 qB 下载器容器的 Mac 地址添加入黑名单 - 无效（扫描的列表中完全扫描不到 Docker 容器的 172 网段 ip ）
3. 通过黑名单功能，将 NAS 添加入黑名单（ Clash 直接扫描到了 NAS 的 IP 地址，直接通过序号快速添加） - 无效，BT 仍然无法访问 tracker 服务器

最后将 Clash 服务关闭，tracker 服务器恢复正常连接

还没有尝试切换为白名单模式，仅允许部分设备（非 NAS 设备）走 Clash 是否可行。（尝试后会在反馈）

**Comment by juewuy** [comment]
@yamazakitouma 2需要桥接，3需要重启clash
