### ISSUE TITLE
在不退出crash的时候，向日葵无法连接，该怎么配置让向日葵绕过crash。以及如何配置任何应用绕过crash

### ISSUE THREAD

**Issue by Michael-Rin** [juewuy/ShellCrash#535]
![image](https://github.com/juewuy/ShellCrash/assets/58716629/55d23da9-2026-4617-9861-d1db7bb8797f)

**Comment by juewuy** [comment]
6-6添加规则绕过相关域名
域名可以从面板日志抓取
