### ISSUE TITLE
1.8版本有几个问题！

### ISSUE THREAD

**Issue by evilyao** [juewuy/ShellCrash#538]
1，如何单独删除一条订阅链接？
2，在添加多条订阅时候有一条添加不进去要不然不显示节点，要不然显示节点就没有ping值也无法连接。单独订阅这条就可以。

**Comment by juewuy** [comment]
@evilyao 1、不支持单独删除
2、检查是否链接包含特殊字符

**Comment by evilyao** [comment]
> @evilyao 1、不支持单独删除 2、检查是否链接包含特殊字符

应该没有特殊字符，如果单独加入链接的方式是可以正常订阅成功的。我现在解决的方法是一条一条的生成加入，加入一条就去yacd面板看一下，如果出来了节点，那就加入第2条。目前三条订阅都成功加入了。但是我有点怕用更新功能，我怕更新一下，节点又不见了。

**Comment by evilyao** [comment]
果然，更新了配置文件后那一条订阅的节点就没了。这条订阅中包含VLESS和hy2的节点。我只能6-3恢复之前的配置文件才出现。
大神，我按6-3恢复了之前的配置文件，发现clash/yamls目录中的config.yaml.bak文件就不见了。然后在脚本里就始终找不到备份配置文件的选项。我都忘了之前的备份你哪里来的。

**Comment by evilyao** [comment]
> @evilyao 1、不支持单独删除 2、检查是否链接包含特殊字符

果然，更新了配置文件后那一条订阅的节点就没了。这条订阅中包含VLESS和hy2的节点。我只能6-3恢复之前的配置文件才出现。
大神，我按6-3恢复了之前的配置文件，发现clash/yamls目录中的config.yaml.bak文件就不见了。然后在脚本里就始终找不到备份配置文件的选项。我都忘了之前的备份你哪里来的。

**Comment by juewuy** [comment]
之前6-1由于未适配后端版本更新导致生成可能有bug，目前版本已修复
