### ISSUE TITLE
开启shellclash后，IPV6无法使用

### ISSUE THREAD

**Issue by qq379834301** [juewuy/ShellCrash#541]
小米万兆路由，安装1.8.1版本shellclash，开启clash后，ipv6test没有本机IPV6地址，关闭后正常。
按照https://github.com/juewuy/ShellCrash/issues/196
中的提示，运行ip6tables --table nat --flush clashv6后正常

**Comment by juewuy** [comment]
@qq379834301 在进阶设置ipv6里启用相关功能

**Comment by qq379834301** [comment]
已经开启了所有进阶设置里IPV6相关功能了

**Comment by juewuy** [comment]
@juewuy 什么运行模式，是否是旁路由？

**Comment by qq379834301** [comment]
不是旁路有，小米万兆路由，shh后直接安装在主路由上运行

**Comment by juewuy** [comment]
@qq379834301 用tproxy模式尝试
