### ISSUE TITLE
proxypool的配置不能使用

### ISSUE THREAD

**Issue by SmerckZak** [juewuy/ShellCrash#542]
![IMG_20231222_093859_097](https://github.com/juewuy/ShellCrash/assets/64113248/c04d0247-b596-423e-a134-2a1c0a4a1e3c)
安卓版本clash可以使用这个地址。不知shell这个错误是什么问题，大佬帮忙看看

**Comment by juewuy** [comment]
@SmerckZak 6-2产生问题请自行解决

**Comment by SmerckZak** [comment]
> @SmerckZak 6-2产生问题请自行解决

解决就是换其他的配置地址就行了，只是想知道这个地址为啥用不了😂😂
