### ISSUE TITLE
proxy-providers 配置使用报错

### ISSUE THREAD

**Issue by crossly** [juewuy/ShellCrash#543]
proxy-providers:
  yuyan.lat:
    type: http
    url: https://proxy-provider-converter.vercel.app/api/convert?url=https%3A%2F%2Fyuyan.lat%2Fapi%2Fv1%2Fclient%2Fsubscribe%3Ftoken%3Dedd376a5c8da&target=clash
    interval: 3600
    path: ./yuyan.lat.yaml
    health-check:
      enable: true
      interval: 600
      lazy: true
      url: http://www.gstatic.com/generate_204

其中的配置是这样，在clash for windows上测试过配置没有报错，可正常使用。但是shellclash报错，报错如下：
配置文件加载失败！请查看报错信息！
INFO[0000] Start initial provider yuyan.lat             
ERRO[0000] initial proxy provider yuyan.lat error: Get "https://proxy-provider-converter.vercel.app/api/convert?url=https%!A(MISSING)%!F(MISSING)%!F(MISSING)yuyan.lat%!F(MISSING)api%!F(MISSING)v1%!F(MISSING)client%!F(MISSING)subscribe%!F(MISSING)token%!D(MISSING)3Dedd376a5c8da&target=clash": x509: certificate signed by unknown authority 
configuration file /tmp/ShellClash/clash_config_admin.yaml test failed

可以看到，在解析url时，url本体解析出错，导致无法下载到关联配置，有劳测试修复，感谢。

**Comment by juewuy** [comment]
@crossly 本地证书问题，路由器不推荐用provider
