### ISSUE TITLE
[Bug] 一键执行脚本报错下载失败，实际是Crash-Clash拼写问题

### ISSUE THREAD

**Issue by RayCyder** [juewuy/ShellCrash#545]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

1一键安装脚本有bug，下载地址后面拼接的crash应为clash，版本1.8.0稳定版；另外下载后clash1.8.0版本的init.sh里面执行报错，原因是未设置clashdir导致的；报错链接：https://fastly.jsdelivr.net/gh/juewuy/ShellCrash/bin/ShellCrash.tar.gz Crash改为Clash正常；下载解压下，执行init.sh脚本报错，原因是clashdir变量为空导致，修改脚本clashdir=clash安装目录，设置手工执行source init.sh 成功

**Comment by RayCyder** [comment]
更新报错链接：https://fastly.jsdelivr.net/gh/juewuy/ShellCrash@1.8.0/bin/ShellCrash.tar.gz

**Comment by CarlosLucky** [comment]
是啊为啥名字从clash又变成了crash，我一头雾水，我一直以为是我穿越了记错了，我一直记得叫shellclash怎么变成shellcrash了启动命令也从clash变成了crash蛋疼，一直启动不了害得我把路由器恢复出厂设置从新破解一边全部重新安装。

**Comment by devioa** [comment]
说实话我觉得仓库改名字就可以了，其它如命令、脚本代码之类的不要改最好，总觉得很怪异

**Comment by TullyMonster** [comment]
我也觉得好奇怪
