### ISSUE TITLE
[Feature] 能否设置某个域名的所有端口的流量都转发到 Clash？

### ISSUE THREAD

**Issue by devioa** [juewuy/ShellCrash#546]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

比如 E-Hentai 的 H@H 下载，会连接到包含`hath.network`后缀的域名请求资源，但所用端口并非一定是常见的80或443：
![QQ截图20240112014258](https://github.com/juewuy/ShellCrash/assets/38558065/ed7c2093-8798-4f0c-bdf7-edf3620ca677)

但又不想关闭`只代理常用端口`，因为我这里软路由还会挂 qBittorrent 下载东西
所以能否添加一个功能用于指定域名（后缀）的所有端口流量都转发到 Clash？
我感觉应该挺好实现的，但我不是很熟悉`iptables`，所以麻烦作者大佬了，非常感谢🙏

**Comment by juewuy** [comment]
@devioa iptables不支持传递和检查域名，过滤bt可以过滤整个设备，如果不方便也可以虚拟机运行桥接模式后过滤虚拟机
本机运行则不要开启本机代理

**Comment by devioa** [comment]
有时候内网设备也会有迅雷比特彗星之类的BT/P2P下载，那这种情况是没什么很好的办法解决吗？
那能否配合`smartdns`上游解析`*.hath.network`的 IP 然后加入 ipset 再供`iptables`处理？这种可行吗？

**Comment by juewuy** [comment]
@devioa 那你也可以自己写iptabels，把相关IP直接转发给内核

**Comment by devioa** [comment]
我就是不熟悉`iptables`😂不知道怎么写

**Comment by juewuy** [comment]
@devioa 那我建议你相关应用直接配置socks或者http代理还方便点

**Comment by devioa** [comment]
我用的ehviewer没有提供socks或http代理
我刚问Copilot，大概知道前半段是`iptables -t nat -A PREROUTING -m set --match-set hathnet -p tcp ?`后面我该怎么写呀？
`-j REDIRECT --to-ports 7890`？还是`dst -j REDIRECT --to-ports clash`？
烦请指教

**Comment by juewuy** [comment]
@devioa https://github.com/juewuy/ShellCrash/blob/b073c55d90fa68e2ffbde5096b7f6538ee0fa59f/scripts/start.sh#L525C1-L525C1

**Comment by devioa** [comment]
看了下源码明白了，已经配置成功，感谢！
生效规则为`iptables -t nat -A PREROUTING -p tcp -m set --match-set hathnet dst -j clash`
