### ISSUE TITLE
[Bug] 速度慢

### ISSUE THREAD

**Issue by xiaoyang886** [juewuy/ShellCrash#547]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

大佬   家里300m的宽带 用了shellclash之后只有30m了  这个机场我在电脑上直接开clash是可以跑满的 路由器是小米r3p 处理器是mt7621

**Comment by juewuy** [comment]
@xiaoyang886 开绕过cnip

**Comment by xiaoyang886** [comment]
我一开始 没绕开 链接内网是100m 慢了3分之2，链接外网只有10分之1也就是30m，绕开了之后 内网可以跑满，外网还是30m

**Comment by juewuy** [comment]
@xiaoyang886 那就换路由，性能就这样

**Comment by energyc99** [comment]
我也遇到了这个问题，我用Clash Verge Rev下同一个文件跑到20多M每秒，但用ShellCrash只跑到5M左右每秒。后来研究一天后发现是ShellCrash默认使用的是Clash内核，而不是跟Clash Verge Rev一样的meta(mihomo)内核，在设置里切换内核后就能跑满速度了。
