### ISSUE TITLE
[Bug] 意外处理入站数据

### ISSUE THREAD

**Issue by MintCoolMC** [juewuy/ShellCrash#548]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

我只测试了nft两个模式，不确定tproxy是否也有问题。
当启动了shellcrash之后，网关下的设备无法从国外使用ipv6访问，手动把访问方的IP加入cn_ipv6中就可以被访问。

**Comment by juewuy** [comment]
因为ipv6的局域网设备也会通过公网IP访问外部数据
这导致了不方便从防火墙过滤本地地址段以允许非本地入站流量绕过内核
否则很容易误杀局域网设备导致其流量无法路由内核
