### ISSUE TITLE
[Feature] 本地文件导入模式

### ISSUE THREAD

**Issue by xaotag** [juewuy/ShellCrash#550]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

shellclash 接管本地meta文件。就是可以导入本地的yaml文件

**Comment by xaotag** [comment]
作为框架使用，接管本地的clash服务。提供简单的iptables设置。

**Comment by juewuy** [comment]
@xaotag https://juewuy.github.io/bdaz/
