### ISSUE TITLE
[BUG] 热更新订阅 执行失败 `command not found`

### ISSUE THREAD

**Issue by devioa** [juewuy/ShellCrash#552]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

`start.sh: line 1663: modify_: command not found`
![image](https://github.com/juewuy/ShellCrash/assets/38558065/4163b022-3256-4964-b3c8-831cbfb2643e)
我暂时先直接改成`modify_yaml`用着

**Comment by devioa** [comment]
还有我一直没搞懂`getdate.sh`这个文件名的意思，date 不是日期的意思吗？这个是拼写错误吧

**Comment by juewuy** [comment]
@devioa 公测版未复现
因为本来想叫update

**Comment by devioa** [comment]
我用的就是1.8.7d公测版

**Comment by juewuy** [comment]
@devioa 删除重新添加任务

**Comment by devioa** [comment]
没用，问题在于`hotupdate`获取不到`$format`这个变量

**Comment by devioa** [comment]
因为我手动执行的`/opt/clash/task/task.sh 105`

**Comment by juewuy** [comment]
https://github.com/juewuy/ShellCrash/commit/85547ab863a7ffea47fe6b96e29d183ba2756c92
