### ISSUE TITLE
[Bug] 更新到1.8.7d后部分机场无法下载配置文件

### ISSUE THREAD

**Issue by wj36149** [juewuy/ShellCrash#553]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

故障现象：更新到1.8.7d公测版后无法更新配置文件，卸载重装后依然无法下载配置文件。经测试，手上三个机场，两个备用机场可以正常下载到配置文件，另个主机场无法下载到配置文件（这个机场的订阅链接用clash手机版和win版能下载到配置文件，只有shellcrash下载不到）。
咨询主机场老板后得知：下载配置文件会验证user-agent，只有包含Clash字眼的user-agent才能正确下载到配置文件。

**Comment by juewuy** [comment]
6-2不行就6-1，或者你自己本地安装
6-2不会添加，因为也有的地址添加反而报错

**Comment by wj36149** [comment]
> 6-2不行就6-1，或者你自己本地安装 6-2不会添加，因为也有的地址添加反而报错

就是6-1不行，以前还是shellclash时三个机场都正常，更新到彻底改名成shellcrash后6-1就不行了。

**Comment by juewuy** [comment]
@wj36149 6-1加不加参数不是脚本能控制的

**Comment by wj36149** [comment]
> @wj36149 6-1加不加参数不是脚本能控制的

那下载配置文件是curl调用系统ua，还是用的第三方解析服务器的ua？

**Comment by juewuy** [comment]
@wj36149 那是subconverter后端处理的

**Comment by wj36149** [comment]
> @wj36149 那是subconverter后端处理的

感谢解答，看来只能放弃机场了。
