### ISSUE TITLE
rax3000m是不是不支持暂时[Feature] 

### ISSUE THREAD

**Issue by coolangcn** [juewuy/ShellCrash#555]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

rax3000m是不是不支持暂时

**Comment by juewuy** [comment]
@coolangcn 不知道

**Comment by juewuy** [comment]
@coolangcn 刷机后可以
