### ISSUE TITLE
[Bug] 更新配置时出错

### ISSUE THREAD

**Issue by benny-tse** [juewuy/ShellCrash#556]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

在线生成配置文件时，在启动服务以使配置文件生效时，出现以下错误：
Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
然后自建vps的tls或者reality链接无法显示在服务器列表中。

**Comment by juewuy** [comment]
@benny-tse 第一个问题重启设备

**Comment by juewuy** [comment]
@benny-tse 第二个问题更换meta或者singbox内核

**Comment by benny-tse** [comment]
重启了设备，还是没用，添加配置文件后，出现以下错误：
是否启动服务以使配置文件生效？(1/0) > 1
-----------------------------------------------
Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
ip6tables: No chain/target/match by that name.
ip6tables: No chain/target/match by that name.
ip6tables: No chain/target/match by that name.
ip6tables: No chain/target/match by that name.
ip6tables: No chain/target/match by that name.
ip6tables: No chain/target/match by that name.
ip6tables: No chain/target/match by that name.
ip6tables: No chain/target/match by that name.
ip6tables: No chain/target/match by that name.
ip6tables: No chain/target/match by that name.
ip6tables: No chain/target/match by that name.
ip6tables: No chain/target/match by that name.
ip6tables: No chain/target/match by that name.
ip6tables: No chain/target/match by that name.
ip6tables: No chain/target/match by that name.
ip6tables: No chain/target/match by that name.
ip6tables: No chain/target/match by that name.
ip6tables: No chain/target/match by that name.
ip6tables: No chain/target/match by that name.
ip6tables v1.6.2: Couldn't load target `shellcrashv6':No such file or directory

Try `ip6tables -h' or 'ip6tables --help' for more information.
ip6tables v1.6.2: Couldn't load target `shellcrashv6':No such file or directory

Try `ip6tables -h' or 'ip6tables --help' for more information.
Clash服务已启动！
请使用 http://192.168.1.254:19999/ui 管理内置规则

**Comment by juewuy** [comment]
@benny-tse iptables被其他应用锁定了，这不是我能解决的问题
