### ISSUE TITLE
[Feature] 锐捷天蝎适配

### ISSUE THREAD

**Issue by fesily** [juewuy/ShellCrash#557]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

我不知道应该如何适配这个设备，能给我一些指导吗？

**Comment by juewuy** [comment]
@fesily 非镜像化设备直接进ssh安装，镜像化设备参考mi_snipshot.sh

**Comment by fesily** [comment]
我装了 直接断网，所以肯定需要适配

**Comment by juewuy** [comment]
@fesily 那么先参考常见问题
