### ISSUE TITLE
[Bug] 关于singbox的sniff

### ISSUE THREAD

**Issue by firedes** [juewuy/ShellCrash#559]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [x]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

经测试，在不启用`sniff`时singbox的domain相关的rule不会生效（应该跟域名是cname记录和singbox的嗅探机制有关），比如：
```
      {
        "domain": [
          "whatismyip.akamai.com",
          "www.baidu.com"
        ],
        "outbound": "direct"
      }
```
在启用了`sniff_override_destination`后，有些网站又会访问异常，比如douyu的直播看不了。

个人认为：对于singbox而言，入站的`sniff`必须开启，而`sniff_override_destination`没有开启的必要，要防止dns污染应在服务端开启`sniff_override_destination`

**Comment by juewuy** [comment]
@firedes 我本地没复现你提出的情况，是否是DNS没有劫持成功？
或者你提供一下面板连接详情，看一下未启用sniff的连接是否显示域名？
如果DNS已经成功劫持，则即使sniff禁用，依然会显示域名

**Comment by firedes** [comment]
@juewuy 可以确认劫持成功。注意`whatismyip.akamai.com`是cname记录，如果不配置`sniff=true`，singbox默认解析出来的是它的最终cname：a1524.g.akamai.net，所以这个域名匹配不了whatismyip.akamai.com。
![image](https://github.com/juewuy/ShellCrash/assets/16650765/2cb95783-2ef7-4bc2-8cd8-5e08fddd883b)
![image](https://github.com/juewuy/ShellCrash/assets/16650765/15e30039-fc5b-476a-8360-01a6862b9a47)

**Comment by firedes** [comment]
@juewuy 可以确认劫持成功。注意`whatismyip.akamai.com`是cname记录，如果不配置`sniff=true`，singbox默认解析出来的是它的最终cname：a1524.g.akamai.net，所以这个域名匹配不了whatismyip.akamai.com。
![image](https://github.com/juewuy/ShellCrash/assets/16650765/2cb95783-2ef7-4bc2-8cd8-5e08fddd883b)
![image](https://github.com/juewuy/ShellCrash/assets/16650765/1c77fb17-e9a0-4020-9ad3-161cfde1ea8a)

**Comment by juewuy** [comment]
这样看，倒更像是内核的一个问题
理论上既然启用了域名反查就应该使用请求域名进行访问而不是cname
我只能先观察一下

**Comment by firedes** [comment]
> 这样看，倒更像是内核的一个问题 理论上既然启用了域名反查就应该使用请求域名进行访问而不是cname 我只能先观察一下

@juewuy 我猜测这是他故意设计成这样的，需要拿到原始域名他也提供了`sniff`这个机制，所以无可厚非。`sniff_override_destination`还存在一些其它的设计问题，然而singbox的社区氛围并不友好，我是不期望靠提issue或等待能解决某些问题。

**Comment by juewuy** [comment]
恩，确实没办法，只能加上了
