### ISSUE TITLE
[Feature] 为什么订阅转换规则不支持vless了？

### ISSUE THREAD

**Issue by benny-tse** [juewuy/ShellCrash#561]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

新的订阅转换为什么不支持vless？原来一直都支持的。

301 墙洞提供,不支持vless|hy https://api.dler.io  
302 SUB作者提供,不支持vless|hy https://sub.xeton.dev 
303 品云提供,不支持vless|hy https://sub.id9.cc

**Comment by benny-tse** [comment]
我是以一个小白用户的角度来说的。我现在更新配置，vless的就是不能转换成功。今天我看到你的server.list里边写的，才知道。我只能手动设置。

**Comment by juewuy** [comment]
6-1生成时候只要检测链接内包含vless或者hy会自动切换为支持的后端
