### ISSUE TITLE
[Bug] 小米R2D ShellClash 1.8.0 meta内核下节点fallback不能自动切换

### ISSUE THREAD

**Issue by martin-songzy** [juewuy/ShellCrash#566]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

环境：
- 小米路由器R2D
- ShellClash 1.8.0
- clash.meta core 1.16 Armv5（尝试升级到更高版本，不工作）

现象：
- fallback proxy group，无法实现失效节点自动切换，相同的配置在clash meta for android下可以自动切换
- dashboard的状态比较奇怪，不点检测前，相当一部分节点状态显示不可用，手动检测后，节点状态恢复正常。
- dashboard上点击检测，可以看到首节点状态是down的，但对应的组不切换到第二个可用节点上

相关配置：
proxy-groups:
  - name: AUTO
    type: fallback
    proxies:
      - proxy1
      - proxy2
      - proxy3
      - proxy4
    url: 'https://www.gstatic.com/generate_204'
    interval: 300

**Comment by juewuy** [comment]
先尝试切换clash内核或者clashpre内核，如果只是meta内核问题，请去上游项目反馈

**Comment by martin-songzy** [comment]
测试url由https更改为http后问题解决，貌似因为R2D路由器的ssl模块有问题
