### ISSUE TITLE
[Feature] 希望能提供自定义下载缓存位置

### ISSUE THREAD

**Issue by umifly** [juewuy/ShellCrash#569]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

当前shellcrash下载的内核等文件会先放在/tmp目录下解压，对于根目录小，但是可以外接存储（如TF卡）的设备不友好，希望可以提供自定义缓存路径，或者直接下载到安装路径的功能，谢谢。

**Comment by juewuy** [comment]
尝试
https://github.com/juewuy/ShellCrash/commit/f4ebf101f5f5cca06baff583e716e40b59c6fef6

**Comment by umifly** [comment]
更新到了最新版，也没有解决问题，我这台设备的tmp目录占用的是根目录存储，因为安装目录空间充足，把tmp也就是根目录塞爆也进不去小闪存模式

**Comment by juewuy** [comment]
@umifly 好吧，你先用之前的版本吧，这个我得下个版本之后才会考虑了

**Comment by juewuy** [comment]
@umifly 暂时可以通过修改安装目录下/configs/command.env文件调整缓存目录

**Comment by umifly** [comment]
@juewuy 修改了缓存目录，爆根目录的情况解决了，谢谢帮助
