### ISSUE TITLE
[Bug] invalid go version while compiling from action

### ISSUE THREAD

**Issue by simonsmh** [juewuy/ShellCrash#570]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

Logs from actions shows that binaries are building with go 1.20 which leads to missing features as go-version input was not specified.
```
Setup go version spec 
Warning: go-version input was not specified. The action will try to use pre-installed version.
/usr/bin/go env GOMODCACHE
/usr/bin/go env GOCACHE
/home/runner/go/pkg/mod
/home/runner/.cache/go-build
Received 4194304 of 261187520 (1.6%), 4.0 MBs/sec
Received [17](https://github.com/juewuy/ShellCrash/actions/runs/7811231814/job/21305984517#step:3:18)1966464 of 261[18](https://github.com/juewuy/ShellCrash/actions/runs/7811231814/job/21305984517#step:3:19)7520 (65.8%), 81.9 MBs/sec
Received 256993216 of 261187520 (98.4%), 81.6 MBs/sec
Cache Size: ~249 MB (261187520 B)
/usr/bin/tar -xf /home/runner/work/_temp/6b774aaa-6122-4d07-8f2a-62f[19](https://github.com/juewuy/ShellCrash/actions/runs/7811231814/job/21305984517#step:3:20)e615e55/cache.tzst -P -C /home/runner/work/ShellCrash/ShellCrash --use-compress-program unzstd
Received 2611875[20](https://github.com/juewuy/ShellCrash/actions/runs/7811231814/job/21305984517#step:3:21) of 261187520 (100.0%), 62.2 MBs/sec
Cache restored successfully
Cache restored from key: setup-go-Linux-ubuntu[22](https://github.com/juewuy/ShellCrash/actions/runs/7811231814/job/21305984517#step:3:23)-go-1.20.13-778c01adffbf2b50cf99061e714fdb8d01615c6b8557640302ddff279a[23](https://github.com/juewuy/ShellCrash/actions/runs/7811231814/job/21305984517#step:3:24)ab0c
go version go1.20.13 linux/amd64
```
To fix it, we should fetch go versions again within the `cross` stage to bypass the context switch, or try to switch to the [jobs context](https://docs.github.com/zh/actions/learn-github-actions/contexts#jobs-context).
https://github.com/juewuy/ShellCrash/blob/43f0bffef67383687ccb826355a81116a3dd330a/.github/workflows/update_singbox_core.yaml#L132-L135

**Comment by juewuy** [comment]
@simonsmh OK, thanks for report!

**Comment by juewuy** [comment]
https://github.com/juewuy/ShellCrash/commit/38af29536bc93215a261817dd526cad57c0af00a
