### ISSUE TITLE
[Bug] 最新公测/稳定版在小米AX3000（RA80）上会导致死机

### ISSUE THREAD

**Issue by CelianLH** [juewuy/ShellCrash#574]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

小米AX3000(RA80)安装后内存剩余30兆，存储空间剩余17兆，运行几分钟后即导致路由器死机，表现为Wifi连不上、后台无法访问、SSH连接很卡/无法连接的情况。不知道是硬件太差还是shellcrash的BUG

**Comment by juewuy** [comment]
@CelianLH 禁用第三方DNS或者本机代理

**Comment by CelianLH** [comment]
> @CelianLH 禁用第三方DNS或者本机代理
我重新安装试了下，在安装时：
选择1.路由设备配置局域网透明代理，会导致一会卡死
选择2.Linux设备仅配置本机代理，不会出现卡死的情况

**Comment by juewuy** [comment]
@CelianLH 只能说你网络中可能有大量无意义请求，请结合面板连接/日志进行排查

**Comment by chenbihao** [comment]
我也遇到这个问题了，ax3600，更新了最新版本后，再更新了订阅，好像是内存占用会暴涨，会把路由器的管理界面、wifi、ssh卡掉

**Comment by chiui-li** [comment]
一样的路由器型号，一样的问题，请问有解决方式吗

**Comment by chenbihao** [comment]
> 一样的路由器型号，一样的问题，请问有解决方式吗

我是先重启，趁着还没脚本还没启动，把脚本删了，重新下个最新版
