### ISSUE TITLE
[Feature]  能否支持yaml 文档 中的 锚点 & * << 语法？

### ISSUE THREAD

**Issue by FrankLiangCN** [juewuy/ShellCrash#575]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

 当在yaml配置文件定义锚点，启动服务时校验配置报错 error msg="yaml: unknown anchor 'AN' referenced"

配置如下:
auto:
  &AN {
    type: url-test,
    lazy: true,
    url: http://www.gstatic.com/generate_204,
    interval: 900,
    use: [freenodes],
  }

  - { name: ♻️ 自动选择, <<: *AN }
  
相同配置在openclash，clash verge客户端可以通过校验，请问能否增加对自定义锚点的支持？

**Comment by juewuy** [comment]
@FrankLiangCN 一直都支持，6-6里看说明

**Comment by FrankLiangCN** [comment]
6-6里的说明如下，也就是说类似锚点等功能必须要通过others.yaml单独文件来定义，把锚点定义放到在线订阅文件就无法正确识别定义？
如果是这种情况，在shellcrash和openclash/clash verge等不同客户端之间就无法共用一个配置，需要针对不同客户端分别编写，是否有可能让客户端正确识别到在线订阅文件中的锚点定义呢？

已经创建自定义设定文件：/etc/ShellCrash/yamls/user.yaml ！
可用于编写自定义的DNS，等功能
-----------------------------------------------
已经创建自定义功能文件：/etc/ShellCrash/yamls/others.yaml ！
可用于编写自定义的锚点、入站、proxy-providers、sub-rules、rule-set、script等功能
-----------------------------------------------

**Comment by FrankLiangCN** [comment]
> 6-6里的说明如下，也就是说类似锚点等功能必须要通过others.yaml单独文件来定义，把锚点定义放到在线订阅文件就无法正确识别定义？ 如果是这种情况，在shellcrash和openclash/clash verge等不同客户端之间就无法共用一个配置，需要针对不同客户端分别编写，是否有可能让客户端正确识别到在线订阅文件中的锚点定义呢？
> 
> ## 已经创建自定义设定文件：/etc/ShellCrash/yamls/user.yaml ！
> 可用于编写自定义的DNS，等功能
> ## 已经创建自定义功能文件：/etc/ShellCrash/yamls/others.yaml ！
> 可用于编写自定义的锚点、入站、proxy-providers、sub-rules、rule-set、script等功能



> @FrankLiangCN 一直都支持，6-6里看说明

6-6里的说明如下，也就是说类似锚点等功能必须要通过others.yaml单独文件来定义，把锚点定义放到在线订阅文件就无法正确识别定义？
如果是这种情况，在shellcrash和openclash/clash verge等不同客户端之间就无法共用一个配置，需要针对不同客户端分别编写，是否有可能让客户端正确识别到在线订阅文件中的锚点定义呢？

已经创建自定义设定文件：/etc/ShellCrash/yamls/user.yaml ！
可用于编写自定义的DNS，等功能
已经创建自定义功能文件：/etc/ShellCrash/yamls/others.yaml ！
可用于编写自定义的锚点、入站、proxy-providers、sub-rules、rule-set、script等功能

**Comment by FrankLiangCN** [comment]
> @FrankLiangCN 一直都支持，6-6里看说明

6-6里的说明如下，也就是说类似锚点等功能必须要通过others.yaml单独文件来定义，把锚点定义放到在线订阅文件就无法正确识别定义？
如果是这种情况，在shellcrash和openclash/clash verge等不同客户端之间就无法共用一个配置，需要针对不同客户端分别编写，是否有可能让客户端正确识别到在线订阅文件中的锚点定义呢？

已经创建自定义设定文件：/etc/ShellCrash/yamls/user.yaml ！
可用于编写自定义的DNS，等功能
已经创建自定义功能文件：/etc/ShellCrash/yamls/others.yaml ！
可用于编写自定义的锚点、入站、proxy-providers、sub-rules、rule-set、script等功能

**Comment by juewuy** [comment]
@FrankLiangCN 你可以禁用覆写

**Comment by FrankLiangCN** [comment]
> @FrankLiangCN 你可以禁用覆写

测试了一下，确实不报错，可以通过配置校验并启动，同时也意味着在配置文件中要把用到的端口，DNS等都要配置好才能完全正常工作

**Comment by XYZliang** [comment]
> > [@FrankLiangCN](https://github.com/FrankLiangCN) 你可以禁用覆写
> 
> 测试了一下，确实不报错，可以通过配置校验并启动，同时也意味着在配置文件中要把用到的端口，DNS等都要配置好才能完全正常工作

是的。我觉得更方便的方式是把自己配置文件的锚点部分复制一份到others里，这样也不影响脚本管理功能
