### ISSUE TITLE
[Bug] proxy 0: create WireGuard device: gVisor is not included in this build, rebuild with -tags with_gvisor

### ISSUE THREAD

**Issue by xixiha5230** [juewuy/ShellCrash#577]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

影响：无法使用wireguard节点
实现功能：正常使用wireguard节点
ShellClash行为：启动失败，提示错误
```
error msg="proxy 0: create WireGuard device: gVisor is not included in this build, rebuild with -tags with_gvisor"
自定义配置文件校验失败！将使用基础配置文件启动！
错误详情请参考 /tmp/ShellCrash/error.yaml 文件！
服务启动失败！请查看报错信息！详细信息请查看/tmp/ShellCrash/core_test.log
time="2024-03-01T08:59:54.940263725Z" level=fatal msg="Parse config error: proxy 0: create WireGuard device: gVisor is not included in this build, rebuild with -tags with_gvisor"
```

原因：
目前使用的meta v1.18.0内核不支持WireGuard，切换到1.18.1可以解决这个问题。
```
root@OpenWrt:/etc/ShellCrash# ./CrashCore -v
Mihomo Meta v1.18.1 linux arm64 with go1.21.6 Fri Feb  2 12:20:12 UTC 2024
Use tags: with_gvisor
```

**Comment by juewuy** [comment]
@xixiha5230 有提供自定义内核功能为什么不用

**Comment by xixiha5230** [comment]
没注意到这个功能😂，默认情况下会出错，切换自定义内核就好了
