### ISSUE TITLE
[Bug] 最新公测版无法使用wrap节点，想回退到1.8.7，但是没有这个版本了

### ISSUE THREAD

**Issue by MikasaEmiya** [juewuy/ShellCrash#579]
1.8.0后面的稳定版不见了，最新版不支持warp节点，启动报错

1.8.7e稳定版的链接怎么不见了，1.8.0后的稳定版都没有了，目前用1.8.7e挺好的，最新版不支持warp结点

最新公测版报错信息
# 服 务 启 动 失 败 ！ 请 查 看 报 错 信 息 ！ 详 细 信 息 请 查 看 /tmp/ShellCrash/core_test.log
time="2024-03-06T12:30:36.859658613+08:00" level=fatal msg="Parse config error: proxy 2: create WireGuard device: gVisor is not included in this build, rebuild with -tags with_gvisor"

**Comment by juewuy** [comment]
自定义内核里安装官方内核即可

**Comment by MikasaEmiya** [comment]
确实可以了，感谢感谢
