### ISSUE TITLE
 华硕 RT-AC68U 重启以后无法启动crash 

### ISSUE THREAD

**Issue by piggy2011** [juewuy/ShellCrash#580]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

shellcrash成功安装在华硕 RT-AC68U （firmware ：386.9）下，选用内核meta-v1.18.1， 配置warp功能测试正常。但路由器重启以后，crash无法自动运行。提示如下：
Connie-ASUS@RT-AC68U:/tmp/home/root# crash
-sh: crash: not found

需要执行一下指令重新安装ShellCrash后，才能启动Crash。
export url='https://fastly.jsdelivr.net/gh/juewuy/ShellClash@master' && sh -c "$(curl -kfsSl $url/install.sh)" && source /etc/profile &> /dev/null

请问如何可以实现路由器重启以后自动启动ShellCrash？谢谢！

**Comment by juewuy** [comment]
@piggy2011 安装时有提示

**Comment by piggy2011** [comment]
安装时好像没有见到关于开机启动的选项，但是进入crash菜单是显示crash已设置开机启动。
<img width="1392" alt="Screenshot 2024-03-07 at 08 13 44" src="https://github.com/juewuy/ShellCrash/assets/136430232/f2d11cef-6786-4082-b0d1-0409eb0bee4b">

**Comment by juewuy** [comment]
要重装
覆盖安装不显示

**Comment by piggy2011** [comment]
卸载重装了还是不行。具体可以帮忙看看下面的安装过程截图，安装过程没有看到提示说是否允许开机自动启动。

<img width="1392" alt="Screenshot 2024-03-07 at 22 35 35" src="https://github.com/juewuy/ShellCrash/assets/136430232/7f42ae48-b08b-4cf2-aaac-a4554e98d4f9">

<img width="1392" alt="Screenshot 2024-03-07 at 22 35 44" src="https://github.com/juewuy/ShellCrash/assets/136430232/2a0bd3c0-6320-45bd-bb86-455202a85743">

<img width="1392" alt="Screenshot 2024-03-07 at 22 36 19" src="https://github.com/juewuy/ShellCrash/assets/136430232/97ac39f3-f4dc-437e-970b-7c6d64834658">

<img width="1392" alt="Screenshot 2024-03-07 at 22 36 53" src="https://github.com/juewuy/ShellCrash/assets/136430232/84d3a8ee-1030-4e43-84d8-115b6150c73c">

<img width="1392" alt="Screenshot 2024-03-07 at 22 37 26" src="https://github.com/juewuy/ShellCrash/assets/136430232/6907e770-30f1-48a8-a377-a08bde1a8713">

**Comment by juewuy** [comment]
第一张图看不见吗？
还是说你是梅林固件

**Comment by piggy2011** [comment]
是的，刷了梅林固件。版本信息是
Connie-ASUS@RT-AC68U:/tmp/home/root# uname -a
Linux RT-AC68U 2.6.36.4brcmarm #1 SMP PREEMPT Mon Sep 4 11:49:01 EDT 2023 armv7l ASUSWRT-Merlin
Connie-ASUS@RT-AC68U:/tmp/home/root#

**Comment by juewuy** [comment]
尝试用usb的方式启动
或者将/jffs/ShellCrash/start.sh init命令设置为开机启动

**Comment by piggy2011** [comment]
reboot路由器以后，我试着手工执行“/jffs/ShellCrash/start.sh init”也不能启动crash，请问是不是有什么问题？

**Comment by juewuy** [comment]
@piggy2011 有什么报错？或者去8-3看一下启动日志

**Comment by piggy2011** [comment]
路由器重启以后执行“/jffs/ShellCrash/start.sh init”没有看到报错，就是一只在执行但没有任何返回结果。crash 如果没有启动，无法通过菜单看到有什么启动日志。

**Comment by juewuy** [comment]
@piggy2011 前面可以加sh -x

**Comment by piggy2011** [comment]
还是不行，具体结果请看下图。
![Screenshot 2024-03-10 192858](https://github.com/juewuy/ShellCrash/assets/136430232/ab271b95-761a-47c8-8619-bde3507d0934)

**Comment by juewuy** [comment]
重进ssh即可

**Comment by piggy2011** [comment]
不好意思，请问“重进ssh”是指？

**Comment by juewuy** [comment]
算了，如果还是不行，等我下版本改一下呼出命令的方式吧

**Comment by piggy2011** [comment]
能具体说一下“重进ssh”是指做什么具体操作吗？谢谢！

**Comment by YtnbFirewings** [comment]
> 能具体说一下“重进ssh”是指做什么具体操作吗？谢谢！

断开ssh链接，再重新连进来

**Comment by m-zheng** [comment]
碰到過同樣的問題。我的以下解決方案啓發自[這個issue](https://github.com/juewuy/ShellCrash/issues/208).

1. 利用SSH 進入路由器操作系統
2. 卸載已安裝的ShellCrash
3. 重啓，併重新利用SSH 進入路由器操作系統
4. 在重新安裝ShellCrash之前執行這個命令`touch /jffs/scripts/nat-start`
5. 然後再正常安裝ShellCrash

**Comment by wolaijiuni** [comment]
老哥 你这个梅林固件是 原版梅林吗

**Comment by piggy2011** [comment]
都是在GitHub上下载的，也不知道是否原版梅林。你是有遇到什么问题了吗？

**Comment by danieldniu** [comment]
我用的是官网的包https://www.asuswrt-merlin.net/，遇到同样问题，但不影响使用；
我是安装到U盘的；
crash等同于运行 /mnt/USBxxx/ShellCrash/menu.sh 
启动shellcrash可以运行script里面的 /mnt/USBxxx/ShellCrash/start.sh init

**Comment by dayu2025** [comment]
我在 https://www.asuswrt-merlin.net/ 下载的软件包，遇到同样问题但是不影响使用；
crash等同于/mnt/USB4g/ShellCrash/menu.sh
运行shellcrash可以用  /mnt/USB4g/ShellCrash/start.sh init
我安装在U盘的
