### ISSUE TITLE
[Bug] 路由器重启，clash命令就失效了，无法呼出控制台，但是clash是正常运行状态

### ISSUE THREAD

**Issue by shinesky** [juewuy/ShellCrash#581]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

路由器型号：中兴E8820S，mt7621，刷的padavan系统
问题：只要路由器重启，clash命令就失效了，无法呼出控制台，但是clash仍然是正常运行状态，包括ui界面都是可以访问的
clash安装是用的推荐的小闪存模式
![图1](https://github.com/juewuy/ShellCrash/assets/26346923/cfaab8ce-bafe-4078-b906-69ef7cc57352)
![图2](https://github.com/juewuy/ShellCrash/assets/26346923/42e46a66-dd28-4ad9-81f8-a4951008a13f)

**Comment by juewuy** [comment]
@shinesky ssh工具没加载环境变量

**Comment by shinesky** [comment]
> @shinesky ssh工具没加载环境变量

这个要怎么操作

**Comment by juewuy** [comment]
@shinesky 换一个工具

**Comment by shinesky** [comment]
> @shinesky 换一个工具

我换了别的ssh工具也不行，我的n1也安装了shellcrash，但没有这个问题

**Comment by juewuy** [comment]
那就是环境变量没写入，可以用sh /etc/storage/ShellCrash menu.sh 呼出菜单

**Comment by shinesky** [comment]
> 那就是环境变量没写入，可以用sh /etc/storage/ShellCrash menu.sh 呼出菜单

这个命令依然无效
![图3](https://github.com/juewuy/ShellCrash/assets/26346923/79e686da-9a3f-4574-b41d-359a4cedda18)

确实是是环境变量没写入，我之前也查过了，是padavan系统本身问题，只有 /etc/storage 文件夹是可读写，其他目录都是只读，系统没有给root权限，都是admin登录的
shellclash安装完毕后，查看etc/profile，里面是有配置环境变量的，但是这个profile是个软链接，实际指向etc_pro/profile，而本体profile并没有配置shellclash环境变量，，一旦重启，软链接里的环境变量也就失效了，感觉无解啊
![图2](https://github.com/juewuy/ShellCrash/assets/26346923/23856df9-18d8-4a16-8d34-f29420448e2a)

**Comment by shinesky** [comment]
> 加一下判断的事情，主要padavan版本太多文件不一样而已

加什么判断？下个版本会更新吗

**Comment by juewuy** [comment]
@shinesky 看情况吧
