### ISSUE TITLE
如何开始全局模式？

### ISSUE THREAD

**Issue by mafulong** [juewuy/ShellCrash#582]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

如何开始全局模式？

**Comment by juewuy** [comment]
建议先去学习了解最基础的clash知识
