### ISSUE TITLE
[Bug]  切换DNS运行模式：    redir_host，仍为fake ip模式

### ISSUE THREAD

**Issue by kukume** [juewuy/ShellCrash#583]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

环境：x64 openwrt系统 
版本：1.9.0-release
安装在/etc/目录下，文件/etc/ShellCrash/config.yaml为运行配置文件。
配置文件是我手动上传的，上传的配置文件中没有dns模块
已启用的dns运行模式为redir_host，但是在/etc/ShellCrash/config.yaml配置文件下，dns配置为fake_ip，且fallback-filter配置下的域名无法解析ip。自带了 bing.com 和 领英，均无法解析ip。
如图所示。仅设置过重置dns配置
![image](https://github.com/juewuy/ShellCrash/assets/45278810/6c793490-ac90-4100-bd18-83b5dd5d2b8a)
![image](https://github.com/juewuy/ShellCrash/assets/45278810/001dda0a-eabc-4f7e-b2b0-30501f1bc65a)

**Comment by juewuy** [comment]
@kukume 因为现在redirhost都是用fakeip模拟的

**Comment by kukume** [comment]
@juewuy 可以问下fallback-filter配置下的域名无法解析ip是什么问题吗？我试了下是可以直接访问fallback的dns ip的

**Comment by juewuy** [comment]
@kukume 我不确定，你要自定义DNS可以用user.yaml文件来实现

**Comment by kukume** [comment]
@juewuy user.yaml 放在哪个目录下？

**Comment by juewuy** [comment]
6-6
