### ISSUE TITLE
在线导入配置文件，如果线上文件叫ShellClash.yml，实际记录到系统中的文件名却变成ShellCrash.yml

### ISSUE THREAD

**Issue by meteorain** [juewuy/ShellCrash#585]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

在线导入配置文件，如果线上文件叫ShellClash.yml，实际记录到系统中的配置文件名却变成ShellCrash.yml，“l”变成“r”，是不是脚本中的通用替换把文件名错改了。

**Comment by juewuy** [comment]
@meteorain ？6-1或者6-2统一都会明明为config.yaml

**Comment by meteorain** [comment]
> @meteorain ？6-1或者6-2均会重新命名为config.yaml

我再解释一下这个issue，在线导入配置文件 https://xxx.com/ShellClash.yml，导入成功后，再选择更新配置文件，会发现更新的地址被改动，新地址为 https://xxx.com/ShellCrash.yml。URL中的“l”被脚本更改为“r”。

**Comment by juewuy** [comment]
@meteorain 没有这种机制，本地测试也未复现
