### ISSUE TITLE
[Feature] 能否支持自定义在线配置规则模版？

### ISSUE THREAD

**Issue by moonfruit** [juewuy/ShellCrash#586]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

能否支持自定义在线配置规则模版？

支持本地目录或者在线导入均可。我目前主要是希望能自定义`custom_proxy_group`自动把机场提供的节点分到不同的组里。

**Comment by juewuy** [comment]
@moonfruit 可以用6-2

**Comment by moonfruit** [comment]
好的，我研究一下

**Comment by chenbihao** [comment]
> @moonfruit 可以用6-2

请教下， crash 支持 prepend-rules 配置吗
