### ISSUE TITLE
Crash环境下手机APP youtube无法观看视频

### ISSUE THREAD

**Issue by piggy2011** [juewuy/ShellCrash#587]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

shellcrash成功安装后选用内核meta-v1.18.1， 配置选用wiregurad，科学上网功能使用PC测试正常，可以通过浏览器访问youtube视频。如果手机APP YouTube虽然可以打开并浏览到内容，但具体点击视频发现视频一直无法正常播放，同样问题也出现在AppleTV中。请问要解决这个问题是否对crash设置进行修改？谢谢！

**Comment by juewuy** [comment]
@piggy2011 规则问题或者节点不支持udp
