### ISSUE TITLE
[Bug] `ipv6-DNS解析`开关是否失效了？

### ISSUE THREAD

**Issue by devioa** [juewuy/ShellCrash#588]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

在 2-1-9-2 关闭了`ipv6-DNS解析`但是观察上游 smartdns 日志还是有 ipv6 的查询请求
![image](https://github.com/juewuy/ShellCrash/assets/38558065/30856e58-16e0-402e-a048-3184c98e7bba)
![image](https://github.com/juewuy/ShellCrash/assets/38558065/ccb810e8-161e-40e2-bed9-18df9e7686d5)

**Comment by juewuy** [comment]
在PC上用nslookup测试

**Comment by devioa** [comment]
似乎只有`fake-ip`模式会这样，且`nslookup`查询到的只是假 ip，改为`redir-host`就没有了

**Comment by ixbcqq** [comment]
> 似乎只有`fake-ip`模式会这样，且`nslookup`查询到的只是假 ip，改为`redir-host`就没有了

Redmi AX6000只有Tproxy+fakeip模式，没有Tproxy 模式+redir_host。有人知道这是怎么回事吗
