### ISSUE TITLE
一个小问题

### ISSUE THREAD

**Issue by shiqu36** [juewuy/ShellCrash#589]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

作者你好，想问一下chellcrash与mwan3插件共存吗，多虚拟网口流量能全部代理不

**Comment by juewuy** [comment]
@shiqu36 没有研究过
