### ISSUE TITLE
wireguard

### ISSUE THREAD

**Issue by ziyan66** [juewuy/ShellCrash#590]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

wireguard配置的文件不能用吗

**Comment by juewuy** [comment]
@ziyan66 请看更新公告谢谢
