### ISSUE TITLE
[Bug] 在线生成配置文件后，报错error msg="yaml:control characters are not allowed"

### ISSUE THREAD

**Issue by twi1ight00** [juewuy/ShellCrash#591]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

更换了手头的三个机场，尝试了6-1/6-2（机场有直接导出meta配置文件的选项）/6-4，但是不管使用哪一个都会在加载完配置文件后启动时报同样的错误。

**Comment by juewuy** [comment]
尝试更换内核

**Comment by twi1ight00** [comment]
卸载后重新安装，目前这个问题已经解决了。

**Comment by juewuy** [comment]
@twi1ight00 可能是有什么自定义配置文件导致的
