### ISSUE TITLE
[Bug] 报错

### ISSUE THREAD

**Issue by Karmylr** [juewuy/ShellCrash#593]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

1.9.1alpha4 Tproxy模式

```
Error: Could not process rule: Not supported
add rule inet shellcrash output_tproxy meta mark 7892 meta l4proto {tcp, udp} tproxy to :7893
```

**Comment by juewuy** [comment]
@Karmylr lsmod |grep tproxy 查看是否有nft_tproxy内核模块

**Comment by Karmylr** [comment]
@juewuy 
![图片](https://github.com/juewuy/ShellCrash/assets/69903376/2a9ffdf0-a0ce-4063-b711-3bd768977de7)

**Comment by juewuy** [comment]
能完整截图一下错误吗？应该有波浪线提示

**Comment by Karmylr** [comment]
![图片](https://github.com/juewuy/ShellCrash/assets/69903376/0884b380-193e-4f92-9b94-29995a530056)

**Comment by juewuy** [comment]
……
好吧，我有空本地起一个虚拟机试一下

**Comment by Karmylr** [comment]
换了天灵的 ImmortalWrt 也是同样的报错
![图片](https://github.com/juewuy/ShellCrash/assets/69903376/d9da2b1a-fc4b-4019-9a92-c9231b5c6fce)

**Comment by juewuy** [comment]
https://github.com/juewuy/ShellCrash/commit/8f109ecf2ae6708119e3f0860a81801aab9d639a

**Comment by Karmylr** [comment]
![图片](https://github.com/juewuy/ShellCrash/assets/69903376/d3a81be1-24b1-4b23-8043-d5c4b54cc532)
还是报错

**Comment by juewuy** [comment]
这个重启一下设备应该就行了

**Comment by Karmylr** [comment]
重启完还是这样

**Comment by juewuy** [comment]
代理正常吗？这个按理说可以无视

**Comment by Karmylr** [comment]
断网

**Comment by Karmylr** [comment]
等待一会儿后会开始出现udp连接
![Uploading Screenshot_2024-03-21-21-58-28-92_984e1414ae90666a90f12ff17ec14a7f.jpg…]()

**Comment by Karmylr** [comment]
启动后一段时间会出现udp连接，没有tcp
![Screenshot_2024-03-21-21-58-28-92_984e1414ae90666a90f12ff17ec14a7f](https://github.com/juewuy/ShellCrash/assets/69903376/49b4916b-867e-4ec7-97aa-af652ae0cccb)

**Comment by juewuy** [comment]
beta1应该已经修复了之前的报错

**Comment by Karmylr** [comment]
![图片](https://github.com/juewuy/ShellCrash/assets/69903376/4c33400e-4ba4-492c-b9d9-039c306c1473)
还是会出现这条报错信息。而且只有udp流量经过clash，tcp流量被阻断了

**Comment by Karmylr** [comment]
![图片](https://github.com/juewuy/ShellCrash/assets/69903376/f7f06e62-3b0b-436d-8706-7146bef846c3)

**Comment by juewuy** [comment]
没什么问题，tcp如果没进内核可能是被其他应用劫持了

**Comment by Karmylr** [comment]
这个固件只装了shellcrash。换其他作者（eSir，kiddin9）的固件试了下，都无法进入2-1切换防火墙运行模式

**Comment by juewuy** [comment]
@Karmylr ip route 和ip rule 看一下路由规则

**Comment by Karmylr** [comment]
![图片](https://github.com/juewuy/ShellCrash/assets/69903376/ea9a0b91-c576-4cfb-8d0e-8b068c252ea7)

**Comment by juewuy** [comment]
确实看不出问题，你可以尝试一下其他模式试试

**Comment by Karmylr** [comment]
用`混合模式: Redir转发TCP，Tun转发UDP`发现udp流量不会经过内核，但也不会被阻断
zheshi  8-1-4 的输出:
```
table inet shellcrash {
        chain input {
                type filter hook input priority -100; policy accept;
                ip daddr 127.0.0.1 accept
                tcp dport 9999 ip saddr 192.168.2.0/24 accept
                tcp dport 9999 reject
                tcp dport 7890 ip saddr 192.168.2.0/24 accept
                tcp dport 7890 reject
        }

        chain prerouting_dns {
                type nat hook prerouting priority dstnat; policy accept;
                meta mark 0x00001ed6 return
                meta skgid { 453, 7890 } return
                udp dport 53 redirect to :1053
                tcp dport 53 redirect to :1053
        }

        chain prerouting {
                type nat hook prerouting priority mangle; policy accept;
                meta mark 0x00001ed6 return
                meta skgid 7890 return
                ip saddr 198.18.0.0/16 return
                ip daddr { 0.0.0.0/8, 10.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.168.0.0/16, 224.0.0.0/3 } return
                ip saddr != 192.168.2.0/24 return
                ip6 daddr { ::/127, ::ffff:0.0.0.0/96, 64:ff9b::/96, 100::/64, 2001::/32, 2001:20::/28, 2001:db8::/32, 2002::/16, 240e:378:806:dcf7::/64, 240e:37a:90e:d100::/60, fc00::/7, fe80::/10, ff00::/8 } return
                ip6 saddr != { 240e:378:806:dcf7::/64, 240e:37a:90e:d100::/60, fdfe:dcba:9876::/126 } return
                meta l4proto udp meta mark set 0x00001ed4
                meta l4proto tcp meta mark set 0x00001ed5
        }

        chain prerouting_mixtcp {
                type nat hook prerouting priority dstnat; policy accept;
                meta mark 0x00001ed5 meta l4proto tcp redirect to :7892
        }

        chain forward {
                type filter hook forward priority mangle; policy accept;
                oifname "utun" accept
        }
}
```

**Comment by juewuy** [comment]
@Karmylr 确实看不出问题，你可以尝试降级1.9.0稳定版

**Comment by Karmylr** [comment]
1.9.0release没问题
