### ISSUE TITLE
shellcrash什么时候支持alpine linux

### ISSUE THREAD

**Issue by xd19861224** [juewuy/ShellCrash#594]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

shellcrash什么时候支持alpine linux

**Comment by xd19861224** [comment]
alpine重启好像可以用了

**Comment by juewuy** [comment]
@xd19861224 一直都支持，缺少部分依赖可以自行安装apk add 
curl、crond、nftables
