### ISSUE TITLE
[Bug] 无Tproxy模式

### ISSUE THREAD

**Issue by adoctors** [juewuy/ShellCrash#595]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

内核版本：linux_x86_64；系统：Ubuntu 22.04.2 LTS；

**Comment by juewuy** [comment]
@adoctors tproxy需要内核支持

**Comment by adoctors** [comment]
> @adoctorstproxy 需要内核支持

请问需要什么样的内核呢？

**Comment by juewuy** [comment]
@adoctors 编译了xt_tproxy或者nft_tproxy模块的

**Comment by adoctors** [comment]
> @adoctors 编译了xt_tproxy或者nft_tproxy模块的

![image](https://github.com/juewuy/ShellCrash/assets/25791654/7d87e16e-9018-4aac-a01d-3fcc2931cbe7)
这样的可以吗 @juewuy

**Comment by juewuy** [comment]
应该可以了

**Comment by adoctors** [comment]
> 应该可以了
哎……内核和环境本来就这样，但是怎么都没法出来Tproxy。同一批机器只有两台是这样，怎么都找不到原因……发出来也是看看有没有解决方式，其他同学看到也好有个参考

**Comment by juewuy** [comment]
@adoctors 更新一下nftables再试试

**Comment by adoctors** [comment]
> @adoctors 更新一下nftables再试试

还是一样，重装了几次，最后使用的Nft混合和nfttables，暂时是通了，再观察下后续使用效果吧

**Comment by juewuy** [comment]
@adoctors nft混合就是用的tproxy
