### ISSUE TITLE
[Bug] 连接路由器后无法通过外网域名访问到内外设备

### ISSUE THREAD

**Issue by icksky** [juewuy/ShellCrash#596]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

小米路由器7000，连WiFi 用域名访问内网服务都被拒绝了，比如nas的导航页，用移动网络可以访问。
我怀疑是我设置的问题？ 想请教一下如何设置。

版本：1.9.0 和 1.9.1-dev
域名模糊为： hello.com
公网IP模糊为：111.222.123.234

日志：
`24-03-19 08:07:07[ warn ][TCP] dial 🎯 全球直连 (match DomainSuffix/hello.com) 192.168.1.77:35689 --> test.hello.com:10000 error: connect failed: dial tcp 111.222.123.234:10000: connect: connection refused`

**Comment by juewuy** [comment]
开发版增加了dns过滤机制，会过滤来自外部的dns请求，你可以尝试一下在不启用本机代理的前提下，能否访问内部设备

**Comment by icksky** [comment]
> 开发版增加了dns过滤机制，会过滤来自外部的dns请求，你可以尝试一下在不启用本机代理的前提下，能否访问内部设备

@juewuy 早前升级了开发版, 看着好像问题解决了; 前两天我重新安装正式版, 再切回测试版, 又不行了

不知道是不是哪里设置问题

**Comment by icksky** [comment]
目前版本没这个问题了, 感谢~
