### ISSUE TITLE
ShellCrash不支持vlessj节点吗？

### ISSUE THREAD

**Issue by 725216** [juewuy/ShellCrash#598]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

clouldflare的worker搭建的vless,在openclash和w2ray上正常使用,在shellclash上报错：
2024-03-26_19:37:26~服务启动失败！请查看报错信息！详细信息请查看/tmp/ShellCrash/core_test.log
2024-03-26_19:37:26~time="2024-03-26T11:37:24Z" level=fatal msg="Parse config error: proxy 0: unsupport proxy type: vless"

**Comment by juewuy** [comment]
@725216 更新里更换支持的内核

**Comment by 725216** [comment]
> @725216 更新里更换支持的内核

shellclash和openclash的配置文件通用吗？为什么我切换mate内核后，导入配置文件后上不了网了？连国内网也上不了

**Comment by juewuy** [comment]
@725216 不完全通用
