### ISSUE TITLE
[Bug] ubuntu 20.04安装shellCrash无法解析dns

### ISSUE THREAD

**Issue by hepengshuai** [juewuy/ShellCrash#599]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

pve中开启lxc ubuntu20.04, 安装shell crash脚本后存在下面的问题(安装时已经选择旁路由模式)
1.ubuntu本机可以访问国内和国外地址
2.局域网内的其他机器将网关和dns都指向ubuntu后，dns使用redir时国内和国外都无法访问，改用fake-ip模式时其他机器可以正常访问国外网站(google, youtube等，国内网站无法解析dns，电脑微信确可以收发消息，网站打不开)
3.已经开启了ubuntu ipv4转发功能

**Comment by juewuy** [comment]
@hepengshuai 上游DNS连接失败，DNS设置里自行更换

**Comment by hepengshuai** [comment]
大佬，请教一下是要修改哪里的dns配置呢，ubuntu自带的resolved配置，还是shellcrash的dns配置。crash命令行里面好像只能切换dns运行模式，没看到修改dns的选项。ubuntu本身国内国外都能访问, resolved的配置应该没问题吧

**Comment by juewuy** [comment]
@hepengshuai 7-6

**Comment by hepengshuai** [comment]
@juewuy 谢谢大佬，改完dns后可以了
