### ISSUE TITLE
[Bug] shlelcrash做旁路由，电脑访问www.test-ipv6.com是旁路由的ipv6地址

### ISSUE THREAD

**Issue by laobanbiefangcu** [juewuy/ShellCrash#600]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

ubuntu安装shlelcrash做旁路由，电脑访问www.test-ipv6.com是旁路由的ipv6地址，是不是有问题，我看电脑的ipv6地址没用到，请问需要怎么调整，电脑DNS为119.29.29.29
<a href="https://freeimage.host/i/JwFJiLg"><img src="https://iili.io/JwFJiLg.md.png" alt="JwFJiLg.md.png" border="0"></a>

**Comment by juewuy** [comment]
@laobanbiefangcu 不建议在ipv6环境使用旁路由模式

**Comment by laobanbiefangcu** [comment]
> @laobanbiefangcu 不建议在ipv6环境使用旁路由模式

那这个算bug吗

**Comment by juewuy** [comment]
@laobanbiefangcu 不算

**Comment by laobanbiefangcu** [comment]
> @laobanbiefangcu 不算

那这个怎么解决呢，主要是IPV6有时候需要用到

**Comment by juewuy** [comment]
@laobanbiefangcu 请自行解决

**Comment by laobanbiefangcu** [comment]
选择Tproxy 模式+redir_host解决，Tproxy+fakeip模式不行

**Comment by ixbcqq** [comment]
> 选择Tproxy 模式+redir_host解决，Tproxy+fakeip模式不行

Redmi AX6000只有Tproxy+fakeip模式，没有Tproxy 模式+redir_host。有人知道这是怎么回事吗
