### ISSUE TITLE
[Bug] AX3600 版本：1.9.0release 程序异常停止

### ISSUE THREAD

**Issue by hff3706001** [juewuy/ShellCrash#601]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

AX3600 有时候会莫名其妙的 服务停止 
我自己做了个sh每分钟记录程序状态and内容使用情况 如下
![QQ截图20240331111750](https://github.com/juewuy/ShellCrash/assets/24475989/840bf64a-02cb-4e48-b282-3085af818022)

查看log如下

![QQ截图20240331111806](https://github.com/juewuy/ShellCrash/assets/24475989/a4a3c8b2-92ea-4495-aaca-60dd1a708575)

使用的是2个vless节点
其他配置如下
![image](https://github.com/juewuy/ShellCrash/assets/24475989/c4855cff-2ee2-4f05-9c70-2e55a2ad6131)
![image](https://github.com/juewuy/ShellCrash/assets/24475989/bbe0629d-0fcb-4c67-8115-244d92ac4cd9)
![image](https://github.com/juewuy/ShellCrash/assets/24475989/85e822c8-0c9e-4f4d-8f71-f73b0d6e03ba)
![image](https://github.com/juewuy/ShellCrash/assets/24475989/0f2af490-e4b3-4196-ba91-7e8a3a037ca8)
![image](https://github.com/juewuy/ShellCrash/assets/24475989/c47c5794-7e94-4d5e-be4e-8211c4d14681)

**Comment by juewuy** [comment]
请使用内置的debug功能8-1-1监测运行日志
