### ISSUE TITLE
[Feature] 一点儿 Shell 脚本开发的建议

### ISSUE THREAD

**Issue by moonfruit** [juewuy/ShellCrash#604]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

我是个码农，工作需要经常和 shell 脚本打交道，所以有一点儿心得。
首先，我得说这是一个非常棒的项目！能够帮助很多人轻而易举的就在各种设备上搭建起科学上网的通道，我很佩服！
但是阅读了代码之后，我有一点儿建议。

1. 使用 [shellcheck](https://www.shellcheck.net/). shell 脚本开发其实并不容易，会遇到很多坑。`shellcheck` 是我这些年开发 shell 脚本过程使用过的最好的帮手。它能轻易发现很多问题，帮你提前规避掉。比如这里：
	
	https://github.com/juewuy/ShellCrash/blob/0d1383d132d96fc6805249c929f863738d0d75d5/scripts/update.sh#L77-L78

	和这里：

	https://github.com/juewuy/ShellCrash/blob/0d1383d132d96fc6805249c929f863738d0d75d5/scripts/update.sh#L1654

2. 明确究竟是使用`POSIX标准sh`还是`bash`，这个我没有发言权，我不太清楚大多数路由器是否安装了`bash`。但不管是使用哪一个，都应该明确。
	* 如果使用`POSIX标准sh`，那就应该规避掉非`POSIX`的用法，比如`echo -e "请选择安装目录"`。
	* 如果使用`bash`，就需要使用`#!/bin/bash`。`bash`就强大得多了，可以使用的特性会丰富很多：比如数组、哈希数组，字符串替换，正则表达式匹配之类的。

一点儿浅见供您参考，如果您愿意接受这种PR，我也很乐意提供一些这方面的帮助。

**Comment by juewuy** [comment]
@moonfruit 其实是使用的ash语法，然后在支持bash的设备上会在安装时修改文件头来调用bash运行，因为厂商定制的openwrt通常只预装了ash
不用shellcheck是因为有太多没必要的提醒让人很烦，回头我也会考虑更换一下ide开发，毕竟我本来也是业余开发者
当然欢迎提供任何有意义的pr！

**Comment by moonfruit** [comment]
ash 是指的 buzybox 内嵌的 shell 么？

**Comment by juewuy** [comment]
@moonfruit 通常是的

**Comment by devioa** [comment]
@juewuy 最近我检查代码发现有很多地方的缩进存在空格和制表符混用的情况，还有大量的代码行尾随空格。
这个是作者的个人代码习惯吗😂

**Comment by juewuy** [comment]
@devioa 我不是专业的程序员，代码能跑就行🙈

**Comment by moonfruit** [comment]
> @juewuy 最近我检查代码发现有很多地方的缩进存在空格和制表符混用的情况，还有大量的代码行尾随空格。 这个是作者的个人代码习惯吗😂


说到这个，就不得不推荐[shfmt](https://github.com/mvdan/sh)了，也是我现在开发shell必备的工具。
