### ISSUE TITLE
[Feature] 为`clash.meta`提供`unified-delay`和`proxy-server-nameserver`支持

### ISSUE THREAD

**Issue by devioa** [juewuy/ShellCrash#605]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

`unified-delay`更换延迟计算方式，去除握手等额外延迟
`proxy-server-nameserver`代理节点域名解析服务器，仅用于解析代理节点的域名
我现在自用的代码是这样的：
```bash
  #Meta内核专属配置
  [ "$crashcore" = 'meta' ] && {
    [ "$redir_mod" != "纯净模式" ] && find_process='find-process-mode: "off"'
    unified_delay='unified-delay: true'
  }
  #dns配置
  [ -z "$(cat ${CRASHDIR}/yamls/user.yaml 2>/dev/null | grep '^dns:')" ] && {
    if [ "$crashcore" = 'meta' ];then
      cat > ${TMPDIR}/dns.yaml <<EOF
dns:
  enable: true
  listen: :$dns_port
  use-hosts: true
  ipv6: $dns_v6
  default-nameserver:
    - 223.5.5.5
    - 114.114.114.114
  proxy-server-nameserver:
    - 223.5.5.5
    - 114.114.114.114
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
EOF
    else
      cat > ${TMPDIR}/dns.yaml <<EOF
dns:
  enable: true
  listen: :$dns_port
  use-hosts: true
  ipv6: $dns_v6
  default-nameserver:
    - 223.5.5.5
    - 114.114.114.114
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
EOF

…………

  #生成set.yaml
  cat > ${TMPDIR}/set.yaml <<EOF
mixed-port: $mix_port
redir-port: $redir_port
tproxy-port: $tproxy_port
authentication: ["$authentication"]
allow-lan: true
mode: Rule
log-level: info
ipv6: true
$unified_delay
external-controller: :$db_port
external-ui: ui
secret: $secret
$tun
$exper
$sniffer_set
$find_process
routing-mark: $routing_mark
EOF
```

**Comment by devioa** [comment]
> @devioa 我只能说有点脱裤子放屁那感觉了……

？没明白，麻烦说清楚，咋就脱裤子放屁了？
没有`unified-delay`在 webui 上`urltest`的延迟显示非常高，但是手动测速后就正常，这在使用自动测速的策略组上就很有用，而且据我观察 sing-box 好像内核默认就是打开的，不管手动测速还是`urltest`节点延迟都相差不大，而且也没提供配置项来关闭。
而`proxy-server-nameserver`，在直连机场（比如采用 hysteria 协议的节点）如果使用全域名 DoH，或是上游搭配 
 smartdns 使用`proxy-server`再通过节点连接 DNS 服务器连接的话就会陷入解析死循环，节点找不到自己的IP地址，而上游的 doh  也找不到自己的 ip。之前我不知道这个配置项的时候只能靠自己提前在 smartdns 配置文件里写好所有节点域名的 ip 地址，然后再写个脚本定期`nslookup`去更新 ip 才可以。

**Comment by devioa** [comment]
> @devioa 个人需求请使用自定义配置文件功能，另外搭配上游DNS时，不要启用本机代理或者使用shellcrash用户执行第三方应用

并没有启用本机代理，而是 smartdns 通过 socks5 代理 dns 服务器，你没看明白我的意思，如果启用本机代理`nslookup`获取到的 ip 就是 smartdns 已经写好的 ip，那才是真的脱裤子放屁

**Comment by devioa** [comment]
刚才试了下自定义配置文件这功能并不好用
比如我只想在`dns`下加`proxy-server-nameserver`，它就把`dns`下所有其它配置全删了。
或者我要么就把`dns`下所有配置全写上，根本没必要，所以最好的方式就是在脚本里直接加上。

**Comment by xudshen** [comment]
可以自己改一下路由器上start.sh的脚本

```shell
	cat > ${TMPDIR}/set.yaml <<EOF
mixed-port: $mix_port
redir-port: $redir_port
tproxy-port: $tproxy_port
authentication: ["$authentication"]
allow-lan: true
mode: Rule
log-level: info
$ipv6
external-controller: :$db_port
external-ui: ui
secret: $secret 
keep-alive-idle: 600 
keep-alive-interval: 30
unified-delay: true
tcp-concurrent: true
$tun
$exper
$sniffer_set
$find_process
EOF
```

**Comment by juewuy** [comment]
@xudshen 直接在user.yaml里自定义不用改脚本
