### ISSUE TITLE
[Bug] 1.9.1beta2版本，开启局域网过滤后，dns流量劫持异常

### ISSUE THREAD

**Issue by ericsyj** [juewuy/ShellCrash#608]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

目前使用版本为1.9.1beta2，检查后发现start.sh文件[943行](https://github.com/juewuy/ShellCrash/blob/6eff925b1d069875087be0a4737b5c144366bdd2/scripts/start.sh#L943)和[948行](https://github.com/juewuy/ShellCrash/blob/6eff925b1d069875087be0a4737b5c144366bdd2/scripts/start.sh#L948)中[ "$3" = 'PREROUTING' ]判断错误，导致iptables/ip6tables规则添加错误，我理解应该是[ "$2" = 'PREROUTING' ]，请大佬看看修复一下

**Comment by juewuy** [comment]
已修复

**Comment by ericsyj** [comment]
嗯嗯最新版本已修复
