### ISSUE TITLE
[Bug] sing-box `geoip-cn.srs`数据库未被调用，导致国内网站被错误分流走代理

### ISSUE THREAD

**Issue by devioa** [juewuy/ShellCrash#609]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description
这里只调用了`geosite-cn.srs`
https://github.com/juewuy/ShellCrash/blob/82b51cd22c8b9a68bc35b54dce8c54302c4983db/scripts/start.sh#L604-L618
结果就是 geosite-cn 中没有收录的网站会被错误分流到 final 最后走代理
![image](https://github.com/juewuy/ShellCrash/assets/38558065/3fce9e8e-6019-43a0-8f2c-b0cc954a784f)
![image](https://github.com/juewuy/ShellCrash/assets/38558065/2328907d-e164-41d2-9daa-fde4c9a4b645)

**Comment by devioa** [comment]
> @devioa 这个只是分流DNS决定是否返回fakeip，不会影响具体规则分流

问题是这个网站是国内的，但却走了代理，我自己在 ruleset 调用 geoip-cn 后这个网站就再也没出现了
而且不止`im.jinritemai.com`这个域名下所有子域名都会被分流到代理，还有一个就是`*.chnau9999.com`中国黄金的域名也会被分到代理去，其他网站暂时不知道，目前我自己就遇到这两个

**Comment by devioa** [comment]
不信你自己用 sing-box 内核测一下访问[中国黄金官网](https://www.chnau9999.com)

**Comment by juewuy** [comment]
@devioa 这是分流规则问题而不是脚本DNS问题

**Comment by devioa** [comment]
但`geoip-cn.srs`下载了后没有被调用是事实吧？而且我自己修改代码加上调用过后这问题就解决了

**Comment by devioa** [comment]
而且这本来就是分流规则问题，这不是 sing-box 的`rule-set`配置管的吗？我啥时候说这是 dns 问题了

**Comment by devioa** [comment]
我这张图想表达的意思是，这是一个 ip 在中国大陆的网站，但是
![image](https://github.com/juewuy/ShellCrash/assets/38558065/2328907d-e164-41d2-9daa-fde4c9a4b645)
但是却在经过 sing-box 内核的时候，可能因为`jinritemai.com`不在`geosite-cn.srs`数据库中有记录，而且此时 singbox 内核也没有 geoip-cn 数据库去识别是否为国内 ip，所以在这张图里就可以看到它最后被分流到 final 里去了，然后通过 final 走代理绕国外去了
![image](https://github.com/juewuy/ShellCrash/assets/38558065/3fce9e8e-6019-43a0-8f2c-b0cc954a784f)

**Comment by ericsyj** [comment]
这是singbox官方内核的预期行为，在路由规则匹配阶段，singbox不会做任何域名解析，如果你需要可以用singboxp内核

**Comment by devioa** [comment]
> 这是singbox官方内核的预期行为，在路由规则匹配阶段，singbox不会做任何域名解析，如果你需要可以用singboxp内核

OK，如果是官方内核的预期行为，可以忽略我这上面的解释，那回到 issue 标题的问题，`geoip-cn.srs`下载后并未被调用

**Comment by ericsyj** [comment]
> > 这是singbox官方内核的预期行为，在路由规则匹配阶段，singbox不会做任何域名解析，如果你需要可以用singboxp内核
> 
> OK，如果是官方内核的预期行为，可以忽略我这上面的解释，那回到 issue 标题的问题，`geoip-cn.srs`下载后并未被调用
建议你先检查一下内核运行后/tmp/ShellCrash/jsons/中的配置文件是否有引用此数据库

**Comment by juewuy** [comment]
@ericsyj 我不是告诉你此数据库是用来分流DNS了吗？
至于规则问题请自行解决，没有完美的规则我只能这么说
你所说的一切都不是bug，不会再回复

**Comment by devioa** [comment]
> > > 这是singbox官方内核的预期行为，在路由规则匹配阶段，singbox不会做任何域名解析，如果你需要可以用singboxp内核
> > 
> > 
> > OK，如果是官方内核的预期行为，可以忽略我这上面的解释，那回到 issue 标题的问题，`geoip-cn.srs`下载后并未被调用
> 
> 建议你先检查一下内核运行后/tmp/ShellCrash/jsons/中的配置文件是否有引用此数据库

并没有，我在 issue `Description`中都把相关代码引用出来了，建议你先看下

**Comment by devioa** [comment]
> @ericsyj 我不是告诉你此数据库是用来分流DNS了吗？ 至于规则问题请自行解决，没有完美的规则我只能这么说 你所说的一切都不是bug，不会再回复

OKOK行行行你觉得不是那就不是你说的都对我自己 fork 自己解决
