### ISSUE TITLE
[Bug] 将内核切换到singbox 无法开机自启  

### ISSUE THREAD

**Issue by dr-forget** [juewuy/ShellCrash#610]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

使用clash内核 开启重启 可以自动启动shell crash
将clash 内核 切换到singbox 无法自动重启  需要每次手动启动

**Comment by juewuy** [comment]
@dr-forget 内置ntp服务的问题，开发版已修复

**Comment by dr-forget** [comment]
> @dr-forget 内置ntp服务的问题，开发版已修复

<img width="1228" alt="image" src="https://github.com/juewuy/ShellCrash/assets/136982352/cac1fbf4-6a85-44f9-ba60-701dce4c008d">
刚刚切换到最新的开发版 发现次问题还存在

**Comment by dr-forget** [comment]
> @dr-forget 内置ntp服务的问题，开发版已修复

刚刚已经切换到开发版了 依旧还是有此问题 
<img width="1311" alt="image" src="https://github.com/juewuy/ShellCrash/assets/136982352/474a74c7-fbb2-436a-8b49-6287d522f224">
<img width="584" alt="image" src="https://github.com/juewuy/ShellCrash/assets/136982352/77e93e1d-1a0f-42d1-b9d8-7936b14c7f44">
<img width="1290" alt="image" src="https://github.com/juewuy/ShellCrash/assets/136982352/f5e15975-3104-42a5-bfa8-1f3d5b52f99b">

**Comment by dr-forget** [comment]
@juewuy  还有每次在第一次启动的时候 会抛出 自定义配置文件错误  可以确定的是配置文件的json没有问题 跑官方核心没有问题

**Comment by juewuy** [comment]
检查自定义inbound.json文件

**Comment by dr-forget** [comment]
> 检查自定义inbound.json文件

已经检查过了  /tmp/ShellCrash/jsons/inbound.json 格式也没毛病啊  但是修改以后 貌似重新启动 又会覆盖这个文件

**Comment by juewuy** [comment]
@dr-forget 是安装目录不是tmp目录

**Comment by dr-forget** [comment]
> inbound.json

<img width="448" alt="image" src="https://github.com/juewuy/ShellCrash/assets/136982352/5c115a71-97cf-4aef-8765-f35124529f2c">
安装目录是/usr/share/ShellCrash 该目录下没有inbound.json 呀  jsons 下只有一个 config.json
<img width="767" alt="image" src="https://github.com/juewuy/ShellCrash/assets/136982352/b33d21ff-3a6d-44d0-8e71-dd9db6a064f4">
/usr/share/ShellCrash 目录下 没找到这个inbound.json 文件

**Comment by juewuy** [comment]
@dr-forget 正常手动启动会报错吗

**Comment by dr-forget** [comment]
> @dr-forget 正常手动启动会报错吗

正常启动不报错  就第一次 如果把geoip-cn.srs geosite-cn.srs删掉  重新加载依赖  就会抛出错误  但是也能正常使用，也能正常启动  后续如果在启动 停止 不会出现该错误

**Comment by dr-forget** [comment]
@juewuy 大佬 已经确认不是systemd 问题 通过几天的摸索目前已经实现了开机自启 是通过修改sing-box配置实现的
1.修改点 将singbox的rule_set 远程地址先改为local 地址 如果是远程地址则无法连接情况
2.配置文件问题 由于本人是自建的节点  节点直连tag为小写direct 大佬的脚本是 DIRECT   所以开机自启 会抛出ntp无服务器无法连接的情况 此处引发另外一个bug 按照大佬脚本的提示  在/usr/share/ShellCrash/json 新建一个ntp.json 启动时会自动加载 实际启动会排除错误  错误如下：
<img width="889" alt="image" src="https://github.com/juewuy/ShellCrash/assets/136982352/2fded97b-541e-464c-b528-112f67b5fb95">
ntp.json 内容与/tmp/ShellCrash/jsons/ntp.json 内容一致 只是改了detour 为小写的 direct

**Comment by dr-forget** [comment]
rule_set 改为远程 出站改为DIRECT
<img width="959" alt="image" src="https://github.com/juewuy/ShellCrash/assets/136982352/31c1abed-b947-446e-a835-1b1cf8ecfe39">
自启的时候  就报错  内容为如下
<img width="647" alt="image" src="https://github.com/juewuy/ShellCrash/assets/136982352/7a962007-2ce6-4baf-a7ad-916b9ea30529">
<img width="859" alt="image" src="https://github.com/juewuy/ShellCrash/assets/136982352/aad4f29b-d411-4eab-9818-99a43e448698">
疑惑点：本机ip 192.168.9.13 不知道为何 自启动的是 确是用192.168.0.10 ip去访问的  导致无法访问 启动失败

**Comment by juewuy** [comment]
https://github.com/juewuy/ShellCrash/commit/c5e28110cbcaebe2ee86ea00c4bde03a0fa1ea25
