### ISSUE TITLE
[Feature] 请教下， crash 支持 prepend-rules 配置吗，该如何配置

### ISSUE THREAD

**Issue by chenbihao** [juewuy/ShellCrash#611]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

请教下， crash 支持 prepend-rules 配置吗，该如何配置

**Comment by juewuy** [comment]
@chenbihao 不支持，自定义配置请使用6-6

**Comment by chenbihao** [comment]
> @chenbihao 不支持，自定义配置请使用6-6

请教下如何自定义某个规则呀，具体规则这里只有直连跟拒绝吗
![image](https://github.com/juewuy/ShellCrash/assets/21167262/edb6c0e2-0d64-41bc-82d2-72d4c5921591)

**Comment by juewuy** [comment]
会自动读取当前运行中的配置

**Comment by chenbihao** [comment]
> 会自动读取当前运行中的配置

会读取到配置中的 【🔰国外流量】之类的吗？好像没读取到

**Comment by chenbihao** [comment]
> 要先运行服务

是指哪个服务呢？

![image](https://github.com/juewuy/ShellCrash/assets/21167262/4c99b2f6-33cd-4edb-b4cd-30d376fa9cbc)

**Comment by juewuy** [comment]
@chenbihao 内核服务，必须可以正常访问面板

**Comment by chenbihao** [comment]
> @chenbihao 内核服务，必须可以正常访问面板

是指这个面板吗：

![image](https://github.com/juewuy/ShellCrash/assets/21167262/bb77b7b1-192b-408e-8061-e09e2db8d26a)
