### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by svenwang0715** [juewuy/ShellCrash#612]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

大佬，vless，使用了https://github.com/Loyalsoldier/clash-rules
看了几个历史的issue建议用[Premium 内核]，但已不更新不支持vless，会自动切换到meta。导致无限重启。
尝试自定义内核[衍生版 Clash.Meta](https://github.com/MetaCubeX/Clash.Meta/releases)，也是会无线重启，请教下如何配置呢？
小米AX3000T

**Comment by juewuy** [comment]
8-1-1可以debug运行检查重启原因
