### ISSUE TITLE
[Bug] 在自动任务设置每天停止和开启 clash服务，报错

### ISSUE THREAD

**Issue by jkwang** [juewuy/ShellCrash#613]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

在自动任务设置每天停止和开启 clash服务，报错找不到/tmp/ShellCrash/web_proxies
但是手动执行task.sh 101 和task.sh 102 又是正常的。

**Comment by juewuy** [comment]
没有用过这个文件，请提供完整报错信息

**Comment by jkwang** [comment]
/usr/share/ShellCrash/start.sh: line 1412: /tmp/ShellCrash/web_proxies: No such file or directory

**Comment by juewuy** [comment]
@jkwang 这个应该不影响使用

**Comment by jkwang** [comment]
暂时看起来是可以运行的。谢谢！

**Comment by juewuy** [comment]
https://github.com/juewuy/ShellCrash/commit/c5e28110cbcaebe2ee86ea00c4bde03a0fa1ea25
