### ISSUE TITLE
[Bug] ssl 错误 issuer welcome/good

### ISSUE THREAD

**Issue by yarnping** [juewuy/ShellCrash#614]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

偶尔出现ssl 证书错误，很奇怪的证书，像是自签名的，不太确定是不是shellcrash产生的

<img width="652" alt="image" src="https://github.com/juewuy/ShellCrash/assets/8018268/8fd66c94-6576-46cd-9d15-7fbd26525b99">

**Comment by juewuy** [comment]
@yarnping 通常是DNS污染
参考常见问题
