### ISSUE TITLE
[Bug] Mix DNS 模式下，未加载 fake_ip_filter.list，导致局域网设备无法通过主机名访问

### ISSUE THREAD

**Issue by mpco** [juewuy/ShellCrash#616]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

如题

**Comment by juewuy** [comment]
https://github.com/juewuy/ShellCrash/pull/619
https://github.com/juewuy/ShellCrash/pull/621
