### ISSUE TITLE
[Bug] 无法让openAI(chatgpt)走这个代理

### ISSUE THREAD

**Issue by Simuliya** [juewuy/ShellCrash#623]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

我在shellcrash节点选择正确选择了人工智能的节点,并且测试过我的t子可以正常访问gpt,但是我打开gpt显示Unable to load site,下面显示的ip是我非代理的ip地址(查了下是我居住地的ip地址),不知道是什么情况,其他的一些网站如youtube,推特等我可以正常进入

**Comment by juewuy** [comment]
@Simuliya 要代理udp

**Comment by Simuliya** [comment]
![image](https://github.com/juewuy/ShellCrash/assets/127732514/f2f6e406-82e0-4abd-99eb-d74e833fbf04)
这个应该是udp来着
![image](https://github.com/juewuy/ShellCrash/assets/127732514/de58edcd-4f79-4299-9c0c-13ce58a5fba3)

**Comment by Simuliya** [comment]
![image](https://github.com/juewuy/ShellCrash/assets/127732514/e7dfeb06-20af-4908-8f09-3353aceeeddb)
规则应该也是正确的,但是我打开openai在连接里也不显示openai

**Comment by juewuy** [comment]
用混合模式或者tproxy模式

**Comment by Simuliya** [comment]
> 用混合模式或者tproxy模式

问下这俩个模式有什么区别呢,感谢
