### ISSUE TITLE
请问怎么设置某个域名直连？

### ISSUE THREAD

**Issue by 725216** [juewuy/ShellCrash#625]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

不知道是不是节点的问题，用的时clouldflae上搭的免费vless节点，我的设置好了，已经可以正常上网了，使用的时透明模式，别的网站都正常，就时恩山论坛不能访问，只能直连上级路由才行，另外我刷padavan固件设置了也是一样的情况，ssr-plus没试过，因为刷的潘多拉固件，现在的源码编译ipk会报错，以前编译的不支持vless,用不了，但时电脑上的客户端正常

**Comment by juewuy** [comment]
@725216 规则问题
