### ISSUE TITLE
[Bug] /var/log/syslog 磁盘占用过高问题

### ISSUE THREAD

**Issue by zzinx58** [juewuy/ShellCrash#626]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

/var/log/syslog 充满了 ShellCrash 或者 dashboard 面板的日志，如何解决这个问题，关闭日志输出？日志轮换？

<img width="362" alt="image" src="https://github.com/juewuy/ShellCrash/assets/77034104/d3876864-89b1-4e44-a62d-5470e4882ba3">

<img width="393" alt="image" src="https://github.com/juewuy/ShellCrash/assets/77034104/3ac70bc8-7a01-4bd2-a7d0-b021f0801825">

<img width="879" alt="image" src="https://github.com/juewuy/ShellCrash/assets/77034104/a9566932-03dc-4676-b9f4-4e096565f085">

**Comment by juewuy** [comment]
@zzinx58 什么设备？运行模式？脚本版本？

**Comment by zzinx58** [comment]
我目前的解决办法是在 Yacd-Meta 魔改面板的 web ui 界面的设置页中设置 warn 级别日志 log，并通过手动删除方式清除日志文件占用的磁盘空间。
不知道这日志行为是否跟该 web-ui 面板控制行为绑定。
目前状况这似乎意味着在刚启用这个面板时会导致有较多日志占用磁盘空间。
之前上传流量狂跑现象没有截图，主要是来自我 docker 服务，日志也是从那些服务来的。
Ubuntu 设备
纯净模式
版本 1.9.0 release

**Comment by kingsey** [comment]
看了一下syslog里也是shellcrash的日志，但不会一直增加，会滚动删除。
试了一下日志等级受log.json控制（不受面板log等级控制），默认是info，改到error之类的就不会一直写了。

**Comment by juewuy** [comment]
@kingsey 是个bug，切换一次内核就不会出现了，下版本修复

**Comment by zzinx58** [comment]
收到，感谢两位回复，我没别的问题了，很赞。
