### ISSUE TITLE
[求助]如何将一个普通的linux系统设置为旁路由

### ISSUE THREAD

**Issue by huajideshutiao** [juewuy/ShellCrash#627]
我的意思是，能否像[tpclash](https://github.com/TPClash/tpclash)那样，允许直接在主路由的dhcp通告中设置网关为shellcrash服务器
看了readme好像没有明确说到这一点。

**Comment by huajideshutiao** [comment]
> 直接代理主机模式可以把，不做旁路由

意思是通过pac进行代理吗？可以是可以，但是有点麻烦，我是准备直接主路由操作一下就行的

**Comment by huajideshutiao** [comment]
> @huajideshutiao 当然支持，但是不推荐

https://juewuy.github.io/ 这里有对应内容吗？我尝试配置了几次，yacd都看不到连接

**Comment by juewuy** [comment]
@huajideshutiao 通常来说，和其他设置旁路由的方式都是一致的

**Comment by huajideshutiao** [comment]
> @huajideshutiao 通常来说，和其他设置旁路由的方式都是一致的

好，我再试试

**Comment by huajideshutiao** [comment]
> @huajideshutiao 通常来说，和其他设置旁路由的方式都是一致的

还是不行，使用pac会出现部分应用无法代理(比如nagram)，填写网关直接都连不上。可能是我用的unraid的问题。

**Comment by juewuy** [comment]
@huajideshutiao 可能是虚拟机防火墙的安全策略拦截了
