### ISSUE TITLE
[Bug] 小米AX6000，打开shellclash后访问需要走代理的网站报错ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by cdredfox** [juewuy/ShellCrash#628]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

[Bug] 小米AX6000，打开shellclash后访问需要走代理的网站报错ERR_SSL_PROTOCOL_ERROR。

使用其他本机的软件如shadrowroket可以正常访问

**Comment by juewuy** [comment]
@cdredfox 这种一般是DNS劫持失败
