### ISSUE TITLE
[求助] 云服务器安装shellcrash代理遇到的问题 

### ISSUE THREAD

**Issue by jiashu1024** [juewuy/ShellCrash#631]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

我通过云服务器运行shellclash的本地模式，已经能通过web ui访问面板了，且配置正常。但是我export proxy到7890端口，在当前终端会话尝试通过curl google.com发现无法访问，详细信息如下。
curl https://google.com -i
HTTP/1.1 200 Connection established
curl: (35) error:0A000126:SSL routines::unexpected eof while reading

**Comment by juewuy** [comment]
@jiashu1024 启用本机代理

**Comment by jiashu1024** [comment]
<img width="1073" alt="image" src="https://github.com/juewuy/ShellCrash/assets/67859663/64467144-2128-4d7d-b696-f271b015797e">
<img width="1297" alt="image" src="https://github.com/juewuy/ShellCrash/assets/67859663/66440f87-24c0-409d-9575-d72f6e4e1c5b">
是用的本机代理

**Comment by juewuy** [comment]
用脚本提供的本机代理增强模式

**Comment by vincentrift** [comment]
@juewuy 启用tun模式，本地+局域网劫持的模式下。docker和本机启动的telegram都无法使用代理网络。配置正确，UI进入正常。
