### ISSUE TITLE
[Feature] 请问CrashCore.tar.gz解压了应该放哪里。未找到meta核心 下载1分钟才1%才熬人了

### ISSUE THREAD

**Issue by alexallen1** [juewuy/ShellCrash#632]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

我有2台路由，一台已经正常工作，看到目录下有CrashCore.tar.gz
但另一台下载meta核心太鸡儿慢了，1个小时还下不下来。
那个核心文件应该放哪里？

**Comment by juewuy** [comment]
@alexallen1 换源或者使用本地安装
更新里有提示

**Comment by alexallen1** [comment]
fastly.jsdelivr.net 一点都不fast，1000M广东电信全看脸……

**Comment by famousprince** [comment]
jsdelivr.b-cdn.net / testingcf.jsdelivr.net 将就着用吧

**Comment by juewuy** [comment]
@famousprince 参考
https://juewuy.github.io/bdaz/
