### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by xiaoqi2020** [juewuy/ShellCrash#633]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

小米BE7000
安装到内部储存可以正常使用，但是内部储存空间太小了，想安装到外部空间，试了很多次，路由器重启后，crash无法自动启动，输入crash找不到命令！

**Comment by juewuy** [comment]
@xiaoqi2020 可以用小闪存模式然后把目录指向外部存储
