### ISSUE TITLE
[Bug] 7621潘多拉固件，安装shellclash后三星手机无线没有网？电脑wifi有网

### ISSUE THREAD

**Issue by 725216** [juewuy/ShellCrash#636]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

主要是刷这个固件信号号，但是安装shellclash了，手机无网，不知道怎么回事？

**Comment by 725216** [comment]
![Uploading Screenshot_20240508_115721_Settings.jpg…]()

**Comment by juewuy** [comment]
可能是相关wifi验证导致的问题，请配合面板日志查看是否有异常

**Comment by 725216** [comment]
> 可能是相关wifi验证导致的问题，请配合面板日志查看是否有异常

下面那个2.4G的没设密码也没网

**Comment by juewuy** [comment]
@725216 是没网还是没图标？手机重置一下WiFi设置试试，电脑WiFi正常说明不是脚本问题
