### ISSUE TITLE
[求助] 云服务器安装shellcrash，别的云服务器怎么使用

### ISSUE THREAD

**Issue by jiashu1024** [juewuy/ShellCrash#640]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

我服务器比较多，但是我又不想每台服务器上都装一遍shellcrash比较麻烦。所以有没有办法比如云服务器A安装了shellcrash，然后云服务器B需要代理的时候，在终端export http_proxy=A.ip：port的方式用代理。如果能加上安全验证啥的就再好不过了

**Comment by juewuy** [comment]
@jiashu1024 请务必不要这么做，除非云服务器是你自己家开的

**Comment by jiashu1024** [comment]
> @jiashu1024 请务必不要这么做，除非云服务器是你自己家开的

嗯，是我自己家开的[doge]!!!!哈哈，有没有办法呢

**Comment by xiandu999-yu** [comment]
> > @jiashu1024 请务必不要这么做，除非云服务器是你自己家开的
> 
> 嗯，是我自己家开的[doge]!!!!哈哈，有没有办法呢

从源头解决啊dogs

**Comment by juewuy** [comment]
进阶设置里启用公网访问即可
