### ISSUE TITLE
[Feature] 人工智能分类域名提交

### ISSUE THREAD

**Issue by iamsweet** [juewuy/ShellCrash#647]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

人工智能分类加上域名
[ciciai.com](url)

**Comment by Coarisu** [comment]
建议如果有详细自定义的需求的话，学习手动编辑配置文件。

另外，规则相关的内容应该不归这边管，shellclash也是使用的别家的订阅地址转换。

**Comment by juewuy** [comment]
可以，基于DOMAIN-SUFFIX？
