### ISSUE TITLE
小米ax6000  mi.com无法访问[Bug] 

### ISSUE THREAD

**Issue by welenwho** [juewuy/ShellCrash#648]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

<img width="691" alt="image" src="https://github.com/juewuy/ShellCrash/assets/6349085/e3c862c8-3d45-44d0-add2-910b4c0a4a35">

如图，小米ax6000 启动服务会有报错，之后mi.com, xiaomi.com就无法访问了，比如米家就不能登录了，无法访问错误的两处站点，规则中添加这两个域名直连也不行

**Comment by juewuy** [comment]
尝试用1.9.0以上版本内核

**Comment by juewuy** [comment]
尝试更换DNS模式

**Comment by welenwho** [comment]
<img width="693" alt="image" src="https://github.com/juewuy/ShellCrash/assets/6349085/8eaa260f-222f-48ec-a4a7-bf86bce01637">
问题依旧，我在另一台红米ax6上没有这个问题

**Comment by juewuy** [comment]
检查你设备的/etc/hosts文件
