### ISSUE TITLE
[Bug] singboxp无法启动

### ISSUE THREAD

**Issue by xoyojank** [juewuy/ShellCrash#649]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

用的ssr服务器，使用meta内核正常，但内存占用高，切到singboxp后无法启动，重新在线生成配置文件也一样：
可以手动复制该链接到浏览器打开并查看数据是否正常！
        -=O=-#   #    #     #                                         
已成功获取配置文件！
是否启动服务以使配置文件生效？(1/0) > 1
-----------------------------------------------
FATAL[0000] decode config at /data/ShellCrash/jsons/config.json: invalid character '}' looking for beginning of value: row 1, column 2882
panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x9a4b34] goroutine 1 [running]: github.com/sagernet/sing-box/route.(*Router).Initialize(0x40002fb888, {0x40003f30e0, 0x5, 0xc?}, {0x1748c40, 0x0, 0x0}, {0x40003f92f0, 0x1, 0x1}) github.com/sagernet/sing-box/route/router.go:476 +0x754 github.com/sagernet/sing-box.New({{{0x400028f900, 0x1226, 0x1300}, {0x0, 0x0}, 0x40003d4f30, 0x40000c42a0, 0x0, {0x4000400008, 0x5, ...}, ...}, ...}) github.com/sagernet/sing-box/box.go:170 +0x11f4 main.check() github.com/sagernet/sing-box/cmd/sing-box/cmd_check.go:34 +0x114 main.init.func18(0x40001cf800?, {0x4000142880?, 0x4?, 0xd14146?}) github.com/sagernet/sing-box/cmd/sing-box/cmd_check.go:16 +0x1c github.com/spf13/cobra.(*Command).execute(0x16d46a0, {0x4000142800, 0x4, 0x4}) github.com/spf13/cobra@v1.8.0/command.go:987 +0x828 github.com/spf13/cobra.(*Command).ExecuteC(0x16d5ac0) github.com/spf13/cobra@v1.8.0/command.go:1115 +0x344 github.com/spf13/cobra.(*Command).Execute(...) github.com/spf13/cobra@v1.8.0/command.go:1039 main.main() github.com/sagernet/sing-box/cmd/sing-box/main.go:38 +0x24
自定义配置文件校验失败，请检查【/data/ShellCrash/jsons/】文件！

**Comment by juewuy** [comment]
疑似内存溢出
