### ISSUE TITLE
[Bug] 内核更新失败 singboxp

### ISSUE THREAD

**Issue by KleinerSource** [juewuy/ShellCrash#650]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

使用的内核是singboxp
但是更新过程是
################################################################################################################# 100.0%
chmod: /tmp/ShellCrash/core_new: No such file or directory
任务【在每周1的2点整自动更新内核】执行失败！
缓存目录下查看过 下载过程 是core_new.tar.gz 但是解压出来是 ClashCore

**Comment by juewuy** [comment]
可能是存储空间不足或者网络问题，尝试使用本地安装

**Comment by laye0619** [comment]
我有同样的问题，在目录里面选择9更新内核或者脚本就是成功的
