### ISSUE TITLE
meta v1.18.1内核下 error msg="proxy 0: create WireGuard device: gVisor is not included in this build, rebuild with -tags with_gvisor"

### ISSUE THREAD

**Issue by piggy2011** [juewuy/ShellCrash#652]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

切换到meta v1.18.1内核启动服务，出现以下提示错误：

error msg="proxy 0: create WireGuard device: gVisor is not included in this build, rebuild with -tags with_gvisor"
自定义配置文件校验失败！将使用基础配置文件启动！
错误详情请参考 /tmp/ShellCrash/error.yaml 文件！

Connie-ASUS@RT-AC68U:/tmp/home/root# 
Connie-ASUS@RT-AC68U:/tmp/home/root# 服务启动失败！请查看报错信息！详细信息请查看/tmp/ShellCrash/core_test.log
time="2024-06-01T14:35:13.145609343Z" level=fatal msg="Parse config error: proxy 0: create WireGuard device: gVisor is not included in this build, rebuild with -tags with_gvisor"

**Comment by juewuy** [comment]
@piggy2011 去自定义内核里下载
