### ISSUE TITLE
[Feature] Sing-box TUN 的 IPv6 和 GSO

### ISSUE THREAD

**Issue by love4taylor** [juewuy/ShellCrash#654]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

目前 Sing-box 开的 TUN 无法受 IPv6 开关影响，从 JSON 部分来看没有给 IPv6 的 CIDR，以及我建议给个选项开 GSO 或者从用户配置文件读是否开启，开了 GSO 能非常大程度上提高 TUN 性能。

**Comment by juewuy** [comment]
默认内核未编译gso，singbox默认是配置了tun的v6地址的
