### ISSUE TITLE
[Bug] 小米ax3000t,网速一快直接崩溃

### ISSUE THREAD

**Issue by shamate123dashu** [juewuy/ShellCrash#656]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

小米ax3000t,内存占用一大就直接崩溃

**Comment by shamate123dashu** [comment]
我是自己买的vps，有没有办法去掉所有规则，全部直连

**Comment by zszwnes** [comment]
自己购买的vps可以使用在线订阅转换工具添加规则，网上有他人构建好的，如果对他们的服务不放心，也可以自行搭建

**Comment by juewuy** [comment]
使用极简规则即可

**Comment by akongjian100** [comment]
> 使用极简规则即可

老大，同样小米AX3000T  也是经常导致路由器自动重启，应该怎么优化呢？
