### ISSUE TITLE
PROXY-DNS不能配置为tcp://1.1.1.1吗？只能使用tls或者https协议的才能正常工作？

### ISSUE THREAD

**Issue by suikastar** [juewuy/ShellCrash#657]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

正常工作的配置：
防火墙运行模式:  Tproxy模式
DNS运行模式：    redir_host
当前基础DNS：udp://223.5.5.5
PROXY-DNS：tls://1.1.1.1:853

不能正常工作的配置：
防火墙运行模式:  Tproxy模式
DNS运行模式：    redir_host
当前基础DNS：udp://223.5.5.5
PROXY-DNS：tcp://1.1.1.1

**Comment by juewuy** [comment]
@suikastar 去看上游内核相关文档有具体的支持列表及格式
