### ISSUE TITLE
[Bug] 红米AX6000 安装完了之后，应该使用那种模式

### ISSUE THREAD

**Issue by xmlijian** [juewuy/ShellCrash#660]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

希望能过滤国内IP和某些端口或者域名不走代理。比如PT的P2P端口，或者某个域名不设置走代理。

**Comment by juewuy** [comment]
@xmlijian 这不是模式能解决的，需要自定义规则（6-6）
