### ISSUE TITLE
[Bug] AX3600 Tproxy 和混合模式无法运行

### ISSUE THREAD

**Issue by PS0123456** [juewuy/ShellCrash#661]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

如图，分别选择两种模式，都不行，即使运行TUN修复，提示该设备无需修复。
![2024-6-11 17-53-37](https://github.com/juewuy/ShellCrash/assets/13433663/24f42f57-2250-4b98-9e51-af25cdd20961)
![2024-6-11 17-53-25](https://github.com/juewuy/ShellCrash/assets/13433663/6a0b0593-9875-4211-8f5e-5e20c7556b71)

**Comment by PS0123456** [comment]
内核是singboxp

**Comment by PS0123456** [comment]
> 重启设备

重启后依然如此

**Comment by juewuy** [comment]
那只能尝试切换内核了
可以运行modinfo tun 命令检查是否有tun模块

**Comment by PS0123456** [comment]
> 那只能尝试切换内核了 可以运行modinfo tun 命令检查是否有tun模块

谢谢解答，运行提示如下：

module:         /lib/modules/4.4.60/tun.ko
license:        GPL
depends:
似乎有？
