### ISSUE TITLE
[Bug] Shellcrash里面，Redmi AX6000只有Tproxy+fakeip模式，没有Tproxy 模式+redir_host。有人知道这是怎么回事吗

### ISSUE THREAD

**Issue by ixbcqq** [juewuy/ShellCrash#662]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

Shellcrash里面，Redmi AX6000只有Tproxy+fakeip模式，没有Tproxy 模式+redir_host。有人知道这是怎么回事吗

**Comment by ixbcqq** [comment]
> @ixbcqq 用其他内核，基础内核已移除redirhost支持

原来如此，谢谢啦

**Comment by suikastar** [comment]
> @ixbcqq 用其他内核，基础内核已移除redirhost支持

好像只是移除了显示？输入一个不在显示列表的数字，按下回车后还是能成功选择redirhost，是bug吗？

**Comment by juewuy** [comment]
@suikastar 使用中会有问题
