### ISSUE TITLE
[Bug] 红米Redmi AX3000-路由器用一会就变很卡，ShellCrash自动闪退

### ISSUE THREAD

**Issue by Aqvdrt** [juewuy/ShellCrash#663]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

- 路由器型号：红米Redmi AX3000 (RA81)
- 路由器固件：1.0.33、1.0.68
- 开启路由器SSH用的方法：https://www.right.com.cn/forum/thread-8348196-1-1.html
- ShellCrash版本：1.9.1beta10

- 遇到的问题：
  - 路由器运行一段时间之后，会出现异常，无法访问网页。如果已经连上wifi，会保持连接，但断开后无法再次连上wifi；
  - 当路由器出现异常，已经连上wifi的设备，会提示网络异常，无法上网，且无法访问路由管理页面192.168.31.1；
  - 当路由器出现异常，有时候可以刷B站视频，却无法加载B站用户评论，其他一切网络访问基本都不行；
  - 当路由器出现异常，基本无法上网，但是可以控制米家设备；
  - 当路由器出现异常，一段时间之后，ShellCrash会闪退，路由器CPU占用率会飙升；

- ShellCrash服务启动之后有一次自动提示iptables: Chain already exists.
![image](https://github.com/juewuy/ShellCrash/assets/23170555/6d3bcb62-e0bd-4f34-bdbd-0d7d359673c9)

- 路由器运行一段时间之后，ShellCrash消失在进程里
![image](https://github.com/juewuy/ShellCrash/assets/23170555/76ba0142-501e-42e3-a69d-4139748c1ede)

- 当发现ShellCrash不在进程中，重启crash服务一段时间后，crash自动闪退，系统cpu飙升
![image](https://github.com/juewuy/ShellCrash/assets/23170555/f55e2bca-c72b-41ee-b52f-672478351430)

- 有一次重启路由之后，crash没有自启动，打开crash提示配置失效，但过一会仍然起作用了
  - /tmp/ShellCrash/core_test.log为空
![image](https://github.com/juewuy/ShellCrash/assets/23170555/3a67e292-34f6-45ae-93c3-02f1a6a559c2)

**Comment by shamate123dashu** [comment]
你是红米ax3000还是小米ax3000t

**Comment by Aqvdrt** [comment]
您的来件我已收到。I‘ve received your e-mail.            ---dy

**Comment by Aqvdrt** [comment]
> 你是红米ax3000还是小米ax3000t

红米ax3000

**Comment by akongjian100** [comment]
> 你是红米ax3000还是小米ax3000t

小米AX3000T也有出现类似的问题

**Comment by juewuy** [comment]
更新脚本，如果依然存在问题，请注意观察面板日志是否有大量异常链接
