### ISSUE TITLE
[Bug] 安装完成后 web面板的使用问题

### ISSUE THREAD

**Issue by dudu502** [juewuy/ShellCrash#664]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

在shellcrash中已安装了面板，但是在浏览器中依然不会显示，仅提示已安装请刷新，或者打开
![image](https://github.com/juewuy/ShellCrash/assets/36216406/71554480-fb9f-4079-a53c-d7b4768a448f)
进入填写地址页面
![image](https://github.com/juewuy/ShellCrash/assets/36216406/2eddfb7e-f427-4251-a788-8a5e8cfc55df)
也是看着一头雾水不知怎么操作。而且填写了局域网段里的地址也进不去。
希望能出一个使用引导

**Comment by juewuy** [comment]
Ctrl+f5

**Comment by Aqvdrt** [comment]
这是因为浏览器有缓存。
解决办法1：你开一个无痕窗口；
解决办法2：打开开发者工具，清理当前页面cookies和storage；

**Comment by dudu502** [comment]
好的  多谢
