### ISSUE TITLE
[Feature] Add s-ui support

### ISSUE THREAD

**Issue by chengnan049** [juewuy/ShellCrash#666]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

https://github.com/alireza0/s-ui

**Comment by juewuy** [comment]
这不是一个单纯的内核或者dashboard，而是一个综合体，我很难把他纳入既有的脚本框架内
