### ISSUE TITLE
[Bug] local_ipv4 does not include host ip when ip route includes metric value at the end

### ISSUE THREAD

**Issue by zhechenzhu** [juewuy/ShellCrash#670]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

In start.sh script getlanip() at line 202,
`local_ipv4=$(ip route 2>&1 | grep 'src' | grep -Ev 'utun|iot|docker' | grep -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3} $' | sed 's/.*src //g')`
filters ip according to ip address at the end of each line. But some route include metric value at the end. Thus thoes lines get filtered and not include in the firewall rules preventing the host from accessing the proxy.

This happends on my cloud server. Here is the output from ip route and the local_ipv4 output.
```
default via 172.19.63.253 dev eth0 proto dhcp src 172.19.48.6 metric 100
100.100.2.136 via 172.19.63.253 dev eth0 proto dhcp src 172.19.48.6 metric 100
100.100.2.138 via 172.19.63.253 dev eth0 proto dhcp src 172.19.48.6 metric 100
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown
172.18.0.0/16 dev br-7cc7d9038a32 proto kernel scope link src 172.18.0.1 linkdown
172.19.48.0/20 dev eth0 proto kernel scope link src 172.19.48.6 metric 100
172.19.63.253 dev eth0 proto dhcp scope link src 172.19.48.6 metric 100
172.20.0.0/16 dev br-51566e734527 proto kernel scope link src 172.20.0.1
172.21.0.0/16 dev br-dce9d01c7e27 proto kernel scope link src 172.21.0.1 linkdown
172.24.0.0/16 dev br-d51c5cd73759 proto kernel scope link src 172.24.0.1
```
```
172.20.0.1 172.24.0.1
```

**Comment by juewuy** [comment]
Are you sure the local traffic is originated from eth0? This seems to be the LAN.

**Comment by juewuy** [comment]
https://github.com/juewuy/ShellCrash/commit/792edb67a46c59a43dd8a73603a6520c37e39e60
