### ISSUE TITLE
[Bug] 我定了每周7更新订阅并重启服务，为什么6月17号就会重启呢？6月17号是周1不是周7啊

### ISSUE THREAD

**Issue by ixbcqq** [juewuy/ShellCrash#671]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

![image](https://github.com/juewuy/ShellCrash/assets/131175449/0b65de9f-d718-4832-ac91-ebb417cd6754)

**Comment by juewuy** [comment]
这个我也不清楚，可能是系统时间的问题？

**Comment by ixbcqq** [comment]
> 这个我也不清楚，可能是系统时间的问题？

刚才用date命令看了一下时间，时间是正确的

**Comment by juewuy** [comment]
这超出我的理解了，本地无法复现
