### ISSUE TITLE
[Bug] 自定义配置文件校验失败！将使用基础配置文件启动！

### ISSUE THREAD

**Issue by suikastar** [juewuy/ShellCrash#673]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

自定义添加一条trojan，当天正常使用，过了两天后，进程自动结束，尝试启动提示错误

`欢迎使用ShellCrash！            版本：1.9.1beta10
Clash服务没有运行（Tproxy模式），已设置开机启动！
TG频道：https://t.me/ShellClash
-----------------------------------------------
 1 启动/重启服务
 2 内核功能设置
 3 停止内核服务
 4 内核启动设置
 5 配置自动任务
 6 导入配置文件
 7 内核进阶设置
 8 其他工具
 9 更新/卸载
-----------------------------------------------
 0 退出脚本
请输入对应数字 > 1
-----------------------------------------------
error msg="rules[0] [DOMAIN-SUFFIX,local,🎯 全球直连] error: proxy [🎯 全球直连] not found"
自定义配置文件校验失败！将使用基础配置文件启动！
错误详情请参考 /tmp/ShellCrash/error.yaml 文件！
root@XiaoQiang:~# 服务启动失败！请查看报错信息！详细信息请查看/tmp/ShellCrash/core_test.log
time="2024-06-19T12:47:47.325628293Z" level=fatal msg="Parse config error: rules[0] [DOMAIN-SUFFIX,local,🎯 全球直连] error: proxy [🎯 全球直连] not found"`

**Comment by suikastar** [comment]
红米ax6000，配置过程如下，地址已脱敏

BusyBox v1.25.1 (2023-01-30 10:31:26 UTC) built-in shell (ash)

 -----------------------------------------------------
       Welcome to XiaoQiang!
 -----------------------------------------------------
  $$$$$$\  $$$$$$$\  $$$$$$$$\      $$\      $$\        $$$$$$\  $$\   $$\
 $$  __$$\ $$  __$$\ $$  _____|     $$ |     $$ |      $$  __$$\ $$ | $$  |
 $$ /  $$ |$$ |  $$ |$$ |           $$ |     $$ |      $$ /  $$ |$$ |$$  /
 $$$$$$$$ |$$$$$$$  |$$$$$\         $$ |     $$ |      $$ |  $$ |$$$$$  /
 $$  __$$ |$$  __$$< $$  __|        $$ |     $$ |      $$ |  $$ |$$  $$<
 $$ |  $$ |$$ |  $$ |$$ |           $$ |     $$ |      $$ |  $$ |$$ |\$$\
 $$ |  $$ |$$ |  $$ |$$$$$$$$\       $$$$$$$$$  |       $$$$$$  |$$ | \$$\
 \__|  \__|\__|  \__|\________|      \_________/        \______/ \__|  \__|


root@XiaoQiang:~# clash
-----------------------------------------------
欢迎使用ShellCrash！            版本：1.9.1beta10
Clash服务没有运行（Tproxy模式），已设置开机启动！
TG频道：https://t.me/ShellClash
-----------------------------------------------
 1 启动/重启服务
 2 内核功能设置
 3 停止内核服务
 4 内核启动设置
 5 配置自动任务
 6 导入配置文件
 7 内核进阶设置
 8 其他工具
 9 更新/卸载
-----------------------------------------------
 0 退出脚本
请输入对应数字 > 6
-----------------------------------------------
 ShellCrash配置文件管理
-----------------------------------------------
 1 在线生成meta配置文件
 2 在线获取完配置文件
 3 本地生成providers配置文件
 4 本地上传完整配置文件
 5 设置自动更新
 6 自定义配置文件
 7 更新配置文件
 8 还原配置文件
-----------------------------------------------
 0 返回上级菜单
请输入对应数字 > 1
-----------------------------------------------
检测到已记录的链接内容：
trojan://xxx
-----------------------------------------------
清空链接/追加导入？[1/0] > 1
-----------------------------------------------
链接已清空！
-----------------------------------------------
 欢迎使用在线生成配置文件功能！
-----------------------------------------------
-----------------------------------------------
本功能依赖第三方在线subconverter服务实现，脚本本身不提供任何代理服务！
严禁使用本脚本从事任何非法活动，否则一切后果请自负！
-----------------------------------------------
支持批量(<=99)导入订阅链接、分享链接
-----------------------------------------------
 1 开始生成配置文件（原文件将被备份）
 2 设置节点过滤关键字
 3 设置节点筛选关键字
 4 选取在线配置规则模版
 5 选取在线生成服务器
 0 撤销输入并返回上级菜单
-----------------------------------------------
请直接输入第1个链接或对应数字选项 > 1
-----------------------------------------------
请先输入订阅或分享链接！
-----------------------------------------------
本功能依赖第三方在线subconverter服务实现，脚本本身不提供任何代理服务！
严禁使用本脚本从事任何非法活动，否则一切后果请自负！
-----------------------------------------------
支持批量(<=99)导入订阅链接、分享链接
-----------------------------------------------
 1 开始生成配置文件（原文件将被备份）
 2 设置节点过滤关键字
 3 设置节点筛选关键字
 4 选取在线配置规则模版
 5 选取在线生成服务器
 0 撤销输入并返回上级菜单
-----------------------------------------------
请直接输入第1个链接或对应数字选项 > trojan://xxx

-----------------------------------------------
本功能依赖第三方在线subconverter服务实现，脚本本身不提供任何代理服务！
严禁使用本脚本从事任何非法活动，否则一切后果请自负！
-----------------------------------------------
支持批量(<=99)导入订阅链接、分享链接
-----------------------------------------------
 1 开始生成配置文件（原文件将被备份）
 2 设置节点过滤关键字
 3 设置节点筛选关键字
 4 选取在线配置规则模版
 5 选取在线生成服务器
 0 撤销输入并返回上级菜单
-----------------------------------------------
请直接输入第2个链接或对应数字选项 > 1
-----------------------------------------------
链接地址为：http://sub2.jwsc.eu.org/xxx

可以手动复制该链接到浏览器打开并查看数据是否正常！
################################################################################### 100.0%已成功获取配置文件！
是否启动服务以使配置文件生效？(1/0) > 1
-----------------------------------------------
服务已启动！
请使用 http://10.0.1.1:9999/ui 管理内置规则
root@XiaoQiang:~#

**Comment by juewuy** [comment]
使用任务获取时，链接复制到浏览器是否正常？

**Comment by suikastar** [comment]
> 使用任务获取时，链接复制到浏览器是否正常？

复现不出来了，一看日志，我怎么在用sub2.jwsc.eu.org，我换成sub.jwsc.eu.org再观察几天
