### ISSUE TITLE
[Bug] 虚拟云服务器中流量没有经过内核

### ISSUE THREAD

**Issue by Overview3833** [juewuy/ShellCrash#675]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

服务器为腾讯云系统Ubuntu22
测试版管理脚本与稳定版脚本问题相同
具体表现为**所有工作模式**下系统流量都不会经过内核，面板中没有任何连接，日志中没有任何记录
同时使用管理脚本自身测试连通性可以正常看到流量记录与连接记录，管理脚本更新内核可以正常看到流量记录与连接
手动为apt配置代理指向shellcrash的端口问题依旧
请问如何进一步排查

**Comment by juewuy** [comment]
@Overview3833 要启用本机代理增强模式（稳定版）或者在2-1中设定代理范围（公测版）

**Comment by Overview3833** [comment]
> @Overview3833 要启用本机代理增强模式（稳定版）或者在2-1中设定代理范围（公测版）

稳定版选择本机代理增强两种模式测试问题依旧，更新到beta11公测版设定代理范围为本机，问题依旧，我检查下是不是网络配置部分有问题，可能其他网络服务冲突了

**Comment by juewuy** [comment]
@Overview3833 用curl测试

**Comment by xiandu999-yu** [comment]
> @Overview3833 用curl测试

同无法代理本机流量，第一次接触还能用，刷一次固件后就再也不行了[换过脚本了]...刚刚看到您这评论去试了一下curl↓
![image](https://github.com/juewuy/ShellCrash/assets/58256481/630bb486-dad7-4d32-96e3-87d6a139629d)
设备是NanoPi R6S，固件是openwrt.ai这里的内核6.1最后一版[最新6.6不管哪边，不是SD卡暴尸就是USB3.0间歇狗带]

**Comment by xiandu999-yu** [comment]
> @Overview3833 用curl测试

![image](https://github.com/juewuy/ShellCrash/assets/58256481/934f85c1-292b-43ef-b296-0c7271ef6cf4)
问题好像找到了？少了个wanIP，我填上curl就能用了...
![image](https://github.com/juewuy/ShellCrash/assets/58256481/82833e96-14a1-4fb4-92f1-88aef03bdc10)
![image](https://github.com/juewuy/ShellCrash/assets/58256481/47dc098a-429c-4d83-8474-fe2482d5a36c)

**Comment by juewuy** [comment]
好像部分时候会出现curl乱调用出口的情况，有待观察

**Comment by juewuy** [comment]
> > @Overview3833 用curl测试
> 
> ![image](https://private-user-images.githubusercontent.com/58256481/343151649-934f85c1-292b-43ef-b296-0c7271ef6cf4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2NDUzMjAsIm5iZiI6MTcxOTY0NTAyMCwicGF0aCI6Ii81ODI1NjQ4MS8zNDMxNTE2NDktOTM0Zjg1YzEtMjkyYi00M2VmLWIyOTYtMGM3MjcxZWY2Y2Y0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI5VDA3MTAyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmNzBmNDY1MTJlNWMxNmU5OTMzOTM0YzE5Yzc4ODE5MDU4ZjM5NmE5OWRmYmM0ZDVlYzJjZTJiM2E5NzczNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KaKWSZNpkd5pVVUg_81W-opsS0fBl2iGB3LT9CwG1Dg) 问题好像找到了？少了个wanIP，我填上curl就能用了... ![image](https://private-user-images.githubusercontent.com/58256481/343152305-82833e96-14a1-4fb4-92f1-88aef03bdc10.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2NDUzMjAsIm5iZiI6MTcxOTY0NTAyMCwicGF0aCI6Ii81ODI1NjQ4MS8zNDMxNTIzMDUtODI4MzNlOTYtMTRhMS00ZmI0LTkyZjEtODhhZWYwM2JkYzEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI5VDA3MTAyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjMTU4MDRlMTE0ZTkwNTc5YTg1MDE0Njc0ZGU2ODAzZDQ3MDkxZjg3NWU5MDVhNzFlMGI5YWMwNWQ1MWQwOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kUhdi3q7TCmG9tTHjBkUYHWKl0UwrLQw8S8sWuW5Wnc) ![image](https://private-user-images.githubusercontent.com/58256481/343152420-47dc098a-429c-4d83-8474-fe2482d5a36c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2NDUzMjAsIm5iZiI6MTcxOTY0NTAyMCwicGF0aCI6Ii81ODI1NjQ4MS8zNDMxNTI0MjAtNDdkYzA5OGEtNDI5Yy00ZDgzLTg0NzQtZmUyNDgyZDVhMzZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI5VDA3MTAyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyMmE5YWI4OTI4NjJmOTZmNDIyNTlkNTcwZGRjYjA2YmI2NTcwMDA2YjgxZWQxNmM2MjZkODY3NGYxY2YzYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cUaflUfwtdFBns4AJru8BiVNoh8Ox6VPd3ys1BqqfBo)

最好提供一下ip route命令的执行结果给我

**Comment by juewuy** [comment]
https://github.com/juewuy/ShellCrash/issues/670

**Comment by Overview3833** [comment]
```
time="2024-07-02T08:06:54.55784031+08:00" level=warning msg="[TUN] default interface changed by monitor,  => eth0"
time="2024-07-02T08:06:54.562095718+08:00" level=info msg="[TUN] Tun adapter listening at: utun([198.18.0.1/30],[fdfe:dcba:9876::1/126]), mtu: 9000, auto route: false, ip stack: System"
```
我这台机器上有tailscale服务配置，也许是接口路由出错，我会进一步调试

**Comment by Overview3833** [comment]
更新管理脚本与Meta内核到最新版本后切换模式Redir-Host，仅代理本机后工作正常

**Comment by juewuy** [comment]
https://github.com/juewuy/ShellCrash/commit/792edb67a46c59a43dd8a73603a6520c37e39e60

**Comment by XYZliang** [comment]
请问现在tun模式是否可用？
