### ISSUE TITLE
[Bug]  /etc/ShellCrash/menu.sh: /etc/ShellCrash/update.sh: line 415: syntax error: unexpected end of file (expecting "then")

### ISSUE THREAD

**Issue by a523** [juewuy/ShellCrash#676]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

bash --version 
GNU bash, version 4.3.42(1)-release (mipsel-openwrt-linux-gnu)

clash 
-----------------------------------------------
欢迎使用ShellCrash！		版本：1.9.1beta11
Clash服务没有运行（纯净模式），已设置开机启动！
TG频道：https://t.me/ShellClash

**Comment by juewuy** [comment]
@a523 文件不完整，检查存储空间
