### ISSUE TITLE
[Feature] 能否支持ipv6本机代理？

### ISSUE THREAD

**Issue by jelly21fish** [juewuy/ShellCrash#677]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

首先感谢开发者的辛勤付出！最近在尝试不用tun模式实现本机代理。openclash只支持redirect代理本机tcp流量（包括ipv6的），可惜udp流量不行。而我尝试shellcrash发现，可以通过tproxy代理本机ipv4 tcp&udp。

不过，我发现ipv6的本机流量没有被代理。查阅nftables，发现 chain output 有一句`meta nfproto ipv6 return`。我试着把它注释掉（还添加了ip6 daddr、 ip6 saddr两个return），然后用nft -f应用修改后的完整配置，但ipv6本机流量还是没有被代理。

想请教 @juewuy 大佬 ，不知道ipv6只是暂时未添加支持（毕竟是特殊需求）还是tproxy本身就不好实现ipv6本机代理呢？如果可以实现但不打算添加进脚本，能否指点一下自定义方法？如果不好实现，可以推出tproxy代理ipv4，tun代理ipv6的混合模式么？

提问如有不妥还望见谅。不论作者如何打算，都很感谢您的贡献！

**Comment by juewuy** [comment]
@jelly21fish 只是单纯觉得没必要，没有写相关代码

**Comment by jelly21fish** [comment]
@juewuy 感谢大佬的回复！

**Comment by jelly21fish** [comment]
@juewuy 感谢大佬的回复！

**Comment by jelly21fish** [comment]
@juewuy 感谢大佬的回复！我自己修改了一下nft规则，成功代理了ipv6本机流量~

我的操作是将chain output中的meta nfproto ipv6 return注释掉，然后从chain prerouting中复制ip6 daddr、ip6 saddr这两个return规则。

之前不知道是什么原因，wan口的两个公网ipv6地址没有被正确读取，导致本机代理失败。重启之后，地址被成功读取。修改并应用规则后，ipv6的本机代理就实现了。

为了使防火墙能够自动生成，我尝试着修改了脚本。如果大佬愿意的话，希望您能看一下，不知道可不可以把这个功能加进项目里？
https://github.com/juewuy/ShellCrash/compare/dev...jelly21fish:ShellCrash:patch-1

不管怎样，都非常感谢您的工作！

**Comment by juewuy** [comment]
@jelly21fish 其实正常来说用fakeip就行了，除非是本机发出的纯ip的v6流量，所以我才没有考虑代理本机的ipv6流量

**Comment by jelly21fish** [comment]
@juewuy 感谢您的回复！您考虑得对，ipv6本机代理用处较小，只是教育网等环境可能需要，如免流下载等。

我修改了start.sh，替换后启动，测试了Redir模式、混合模式、Tproxy模式、TUN模式，都表现正常，而且实现了ipv6的本机代理。不知道能不能提交PR，合并这个功能？(>﹏<)

我修改了这些地方：https://github.com/juewuy/ShellCrash/compare/dev...jelly21fish:ShellCrash:patch-1

不过我只测试了nftables规则，没有其他设备了。iptables规则是照猫画虎写的，不知道有没有朋友愿意帮我测试……也可以不加入这部分~

虽然这个需求很小众，但既然自己实现了，还是希望能帮到有需要的人，增加一点点价值……希望大佬能接受这个小请求，但不管怎样，都很感谢您！

**Comment by jelly21fish** [comment]
使用虚拟机安装了使用iptables的openwrt进行测试，Redir模式、混合模式、Tproxy模式表现正常，均实现ipv6本机代理。

唯独tun模式的tcp流量异常，但使用原版start.sh文件同样异常，应为虚拟机网络设置的问题。如不放心，可以再进行测试~有空的话，我也会争取在更正常的网络环境下再做测试的！

因为排除了代码修改有错误，所以提出了pull request https://github.com/juewuy/ShellCrash/pull/687 ，希望大佬能予以考虑~🥺感谢您的付出！
