### ISSUE TITLE
[Bug] singbox核心下修改了配置无法保存

### ISSUE THREAD

**Issue by think2011** [juewuy/ShellCrash#678]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

非常感谢你做了这么好用的软件

<img width="1129" alt="image" src="https://github.com/juewuy/ShellCrash/assets/3961388/d3e2e0a4-1a2d-4a81-aa3c-49178e204790">

如图所示，我的平时的习惯是用【手动切换】（因为自动的话，可能会随机到不合适的ip地区），但是用了 singbox 核心后每次重启又恢复成了自动，这很不方便，在之前的版本是正常的

```
欢迎使用ShellCrash！		版本：1.9.1beta11
SingBox服务正在运行（Tun模式），已设置开机启动！

当前目录(/etc/ShellCrash)剩余空间：40.3M
-----------------------------------------------
 1 更新管理脚本    1.9.1beta11 > 1.9.1beta11
 2 切换内核文件    1.9.0 > 1.9.0
 3 更新数据库文件	> 20240608
 ```

**Comment by juewuy** [comment]
@think2011 定时任务里添加自动保存

**Comment by think2011** [comment]
非常感谢，自动任务里确实有这项设置！

**Comment by think2011** [comment]
@juewuy  奇怪的是，我发现确实没有生效，哪怕我设置了自动任务，也手动去执行了任务，然后重启服务器依然会重置，并没有保存面板设置

**Comment by think2011** [comment]
https://github.com/juewuy/ShellCrash/assets/3961388/15688247-8cac-4fbf-8bd1-d1230f96a43e

**Comment by juewuy** [comment]
是否设置了面板密码？确认密码中没有特殊符号

**Comment by think2011** [comment]
> 是否设置了面板密码？确认密码中没有特殊符号

在局域网内使用，没有设置任何密码，没见到其他人反馈过，或许我尝试重置清空下看看会不会正常了

**Comment by think2011** [comment]
<img width="537" alt="image" src="https://github.com/juewuy/ShellCrash/assets/3961388/ebc2e268-7e44-43a3-b1fc-f93eaa917e5d">

重置了，实测在 SingBox 下确实无法保存，clash、meta 则正常

**Comment by juewuy** [comment]
这个可能是个例了，暂时无法定位问题
