### ISSUE TITLE
[Bug] LXC debian环境下安装失败

### ISSUE THREAD

**Issue by mengniu8** [juewuy/ShellCrash#681]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

proxmox下开的LCX小鸡，系统为debian，CPU为X86平台，安装遇到错误：
开始从服务器获取安装文件！
-----------------------------------------------
################################################################################################################################################### 100.0%
-----------------------------------------------
开始解压文件！
tar: clash_providers.list: Cannot change ownership to uid 197609, gid 197609: Invalid argument
tar: Country.mmdb: Cannot change ownership to uid 197609, gid 197609: Invalid argument
tar: fake_ip_filter.list: Cannot change ownership to uid 197609, gid 197609: Invalid argument
tar: fallback_filter.list: Cannot change ownership to uid 197609, gid 197609: Invalid argument
tar: init.sh: Cannot change ownership to uid 197609, gid 197609: Invalid argument
tar: menu.sh: Cannot change ownership to uid 197609, gid 197609: Invalid argument
tar: misnap_init.sh: Cannot change ownership to uid 197609, gid 197609: Invalid argument
tar: servers.list: Cannot change ownership to uid 197609, gid 197609: Invalid argument
tar: shellcrash.procd: Cannot change ownership to uid 197609, gid 197609: Invalid argument
tar: shellcrash.service: Cannot change ownership to uid 197609, gid 197609: Invalid argument
tar: singbox_providers.list: Cannot change ownership to uid 197609, gid 197609: Invalid argument
tar: start.sh: Cannot change ownership to uid 197609, gid 197609: Invalid argument
tar: task.list: Cannot change ownership to uid 197609, gid 197609: Invalid argument
tar: task.sh: Cannot change ownership to uid 197609, gid 197609: Invalid argument
tar: update.sh: Cannot change ownership to uid 197609, gid 197609: Invalid argument
tar: Exiting with failure status due to previous errors
-----------------------------------------------
ShellCrash 已经安装成功!
-----------------------------------------------
输入 crash 命令即可管理！！！

**Comment by juewuy** [comment]
@mengniu8 权限有问题，用sudo -i提权
