### ISSUE TITLE
[Bug] h3 dns无法正常解析

### ISSUE THREAD

**Issue by suikastar** [juewuy/ShellCrash#682]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

解析结果：

![QQ图片20240623144428](https://github.com/juewuy/ShellCrash/assets/53206264/4d135ea8-db70-4c38-9aa7-4b3a3a6c4ea8)

浏览器：
提示dns错误

配置：
```dns:
  enable: true
  prefer-h3: false
  ipv6: false
  listen: 0.0.0.0:1053
  fake-ip-range: 198.18.0.1/16
  enhanced-mode: fake-ip
  fake-ip-filter: ['+.*']
  nameserver:
    - https://223.5.5.5/dns-query#h3=true
    - https://223.6.6.6/dns-query#h3=true
    - https://223.5.5.5/dns-query
    - https://223.6.6.6/dns-query
  nameserver-policy:
    'geosite:category-ads-all': rcode://success
    'geosite:microsoft@cn,apple-cn,google-cn,category-games@cn,cn,private': [https://223.5.5.5/dns-query#h3=true, https://223.6.6.6/dns-query#h3=true, https://223.5.5.5/dns-query, https://223.6.6.6/dns-query]
    'geosite:geolocation-!cn': [https://1.1.1.1/dns-query#🚀 手动切换, https://1.0.0.1/dns-query#🚀 手动切换]```

**Comment by suikastar** [comment]
去除https://223.5.5.5/dns-query#h3=true、https://223.6.6.6/dns-query#h3=true后，正常解析，浏览器正常访问

**Comment by juewuy** [comment]
@suikastar 这不是脚本相关问题
