### ISSUE TITLE
[Feature] 希望能增加mac arm支持，配置如下

### ISSUE THREAD

**Issue by werner-balonius** [juewuy/ShellCrash#685]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

Darwin Werner-3.local 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:16:51 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T8103 arm64

**Comment by werner-balonius** [comment]
即使手动指定了CPU架构为arm64依然会报错：找不到设备的CPU信息，请手动指定处理器架构类型！

**Comment by werner-balonius** [comment]
且使用过程中每执行一行命令会出现： /etc/ShellCrash/start.sh: line 1863: pidof: command not found这个警告

**Comment by werner-balonius** [comment]
核心是Meta，架构选择的arm64

**Comment by juewuy** [comment]
@werner-balonius 是虚拟机吗还是？可以用ubuntu吗？

**Comment by werner-balonius** [comment]
是mac air M1实体机，不能原生用Ubuntu，但是可以用Asahi Linux（8G内存用pd的Ubuntu虚拟机基本卡得不能用），内核选择Meta，在自定义内核列表中无法找到对应的mac arm的内核文件（只有Linux的），需要手动从Mihomo的GitHub仓库下对应的适用于mac arm内核的链接，内核成功下载到本地并通过编译，但是在启动服务时依然显示：找不到设备的CPU信息，请手动指定处理器架构类型！（已选择处理器架构类型为arm64），

谢谢大佬，希望能添加mac arm支持

**Comment by werner-balonius** [comment]
> @werner-balonius 是虚拟机吗还是？可以用ubuntu吗？

是mac air M1实体机，不能原生用Ubuntu，但是可以用Asahi Linux（8G内存用pd的Ubuntu虚拟机基本卡得不能用），内核选择Meta，在自定义内核列表中无法找到对应的mac arm的内核文件（只有Linux的），需要手动从Mihomo的GitHub仓库下对应的适用于mac arm内核的链接，内核成功下载到本地并通过编译，但是在启动服务时依然显示：找不到设备的CPU信息，请手动指定处理器架构类型！（已选择处理器架构类型为arm64），

谢谢大佬，希望能添加mac arm支持

**Comment by juewuy** [comment]
@werner-balonius 是必须用mac_arm64内核不能用Linux_arm64内核吗？

**Comment by juewuy** [comment]
@werner-balonius uname -a返回的信息是？

**Comment by werner-balonius** [comment]
> Darwin Werner-3.local 23.5.0 Darwin Kernel Version 23.5.0: Wed May 1 20:16:51 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T8103 arm64

**Comment by werner-balonius** [comment]
> @werner-balonius uname -a返回的信息是？
返回信息如下
Darwin Werner-3.local 23.5.0 Darwin Kernel Version 23.5.0: Wed May 1 20:16:51 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T8103 arm64

**Comment by werner-balonius** [comment]
> @werner-balonius uname -a返回的信息是？

Darwin Werner-3.local 23.5.0 Darwin Kernel Version 23.5.0: Wed May 1 20:16:51 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T8103 arm64
返回信息如上

**Comment by werner-balonius** [comment]
> @werner-balonius 是必须用mac_arm64内核不能用Linux_arm64内核吗？

如果使用Linux的ARM64，Crash无法识别mac上的CPU信息，看ClashMeta内核仓库发现Linux arm64和mac arm64确实不一样，使用对应的mac版内核可以通过编译，但是Linux不行，且最后两者都无法正常启动服务，谢谢大佬

**Comment by juewuy** [comment]
尝试直接用本地安装的方式上传内核呢？
参考https://juewuy.github.io/bdaz

**Comment by werner-balonius** [comment]
> 尝试直接用本地安装的方式上传内核呢？ 参考https://juewuy.github.io/bdaz

试了，还是不行，用了本地的两种Clash Meta内核，一个crash仓库给的Linux64的，一个是mihomo那个仓库的Darwin arm64的，都不行

**Comment by juewuy** [comment]
目前没有对Darwin系统的支持计划，请尝试手动上传内核
