### ISSUE TITLE
[Bug] 启动提示错误信息

### ISSUE THREAD

**Issue by benben7466** [juewuy/ShellCrash#686]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

error msg="proxy group[6]: `use` or `proxies` missing"

error msg "proxy group[8]:use or proxies  missing
自定义配置文件校验失败!将使用基础配置文件启动!错误详情请参考 /tmp/Shellcrash/error.yaml 文件!

**Comment by juewuy** [comment]
配置文件问题，尝试使用其他方式生成

**Comment by xiandu999-yu** [comment]
代理组6的use或proxies未填写
