### ISSUE TITLE
【Feature】内核求适配，我设备是n100处理器，应该是amd64，结果所有的内核都不适配

### ISSUE THREAD

**Issue by a810439322** [juewuy/ShellCrash#690]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

![image](https://github.com/juewuy/ShellCrash/assets/50438539/57832d8f-081d-42a1-9560-b3c035da366a)

**Comment by xiandu999-yu** [comment]
找错地方了吧。。。核心不适配去核心的仓库啊。。。。

**Comment by a810439322** [comment]
> 找错地方了吧。。。核心不适配去核心的仓库啊。。。。

https://github.com/juewuy/ShellCrash/tree/dev/bin

你看看呢

**Comment by xiandu999-yu** [comment]
> > 找错地方了吧。。。核心不适配去核心的仓库啊。。。。
> 
> https://github.com/juewuy/ShellCrash/tree/dev/bin
> 
> 你看看呢

你去源仓库下载试试?直接替换本地文件试试。。。?

**Comment by xiandu999-yu** [comment]
> > 找错地方了吧。。。核心不适配去核心的仓库啊。。。。
> 
> https://github.com/juewuy/ShellCrash/tree/dev/bin
> 
> 你看看呢

还有。。。
mihomo[原clash.meta]:我还没💩呢？

**Comment by juewuy** [comment]
尝试x86
可能你系统是32位
