### ISSUE TITLE
debian中使用tun作为旁路由时本机可以上网其他机器无法上网

### ISSUE THREAD

**Issue by lq-259** [juewuy/ShellCrash#692]
在 [https://github.com/MetaCubeX/mihomo/discussions/1042#discussioncomment-8504247](url) 找到了解决办法

**Comment by juewuy** [comment]
正常tun模式是会自动添加forward链规则的

**Comment by lq-259** [comment]
> 正常tun模式是会自动添加forward链规则的

那不知道哪里出了问题，该怎么定位这个问题可能在哪里会出现

**Comment by juewuy** [comment]
重新运行后，使用 iptables -L FORWARD -v -n --line-numbers
查看FORWARD 链是否有相关规则

**Comment by lq-259** [comment]
[FORWARD.txt](https://github.com/user-attachments/files/16453816/FORWARD.txt)
好像没有
