### ISSUE TITLE
ShellCrash/yaml/config.yaml设置ipv6: false后，生成的ShellCrash/config.yaml文件内会被强制修改为true

### ISSUE THREAD

**Issue by suikastar** [juewuy/ShellCrash#693]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

可否不强制修改？

**Comment by suikastar** [comment]
已确定未设置
![QQ截图20240629000136](https://github.com/juewuy/ShellCrash/assets/53206264/565ca10d-bce2-4dc6-8cfb-4d260cd13ac1)

**Comment by juewuy** [comment]
@suikastar 6-6

**Comment by suikastar** [comment]
@juewuy 你看看我提交的pr
