### ISSUE TITLE
[咨询] 关于 CN_IP 绕过内核的原理和执行流程

### ISSUE THREAD

**Issue by ovnrain** [juewuy/ShellCrash#696]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

内核是 sing-box，DNS 模式为 mix，且自定义了 dns.json

我的 DNS 配置可以简化如下：
```json
{
  "dns": {
    "servers": [
      {
        "tag": "dns_proxy",
        "address": "https://1.1.1.1/dns-query",
        "client_subnet": "1.0.1.0",
        "detour": "proxy"
      },
      {
        "tag": "dns_direct",
        "address": "https://223.5.5.5/dns-query",
        "detour": "DIRECT"
      }
    ],
    "rules": [
      { "outbound": ["any"], "server": "dns_direct" },
      {
        "rule_set": ["geosite-cn"],
        "server": "dns_direct"
      }
    ],
    "final": "dns_proxy"
  }
}
```

路由规则简化如下：
```json
{
  "route": {
    "rule_set": [
      {
        "tag": "geosite-cn",
        "type": "remote",
        "format": "binary",
        "url": "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/cn.srs",
        "download_detour": "DIRECT"
      },
      {
        "tag": "geosite-geolocation-!cn",
        "type": "remote",
        "format": "binary",
        "url": "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/geolocation-!cn.srs",
        "download_detour": "DIRECT"
      },
      {
        "tag": "geoip-cn",
        "type": "remote",
        "format": "binary",
        "url": "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geoip/cn.srs",
        "download_detour": "DIRECT"
      }
    ],
    "rules": [
      {
        "rule_set": "geosite-geolocation-!cn",
        "outbound": "proxy"
      },
      {
        "rule_set": "geosite-cn",
        "outbound": "DIRECT"
      },
      {
        "rule_set": "geoip-cn",
        "outbound": "DIRECT"
      }
    ],
    "final": "proxy"
  }
}
```

我大概知道 CN_IP 绕过内核是通过将 cn_ip.txt、cn_ipv6.txt 写入到防火墙规则实现的，咨询如下：

1. DNS 查询得到的绕过内核的 IP 跟使用哪个 DNS 有关系吗？如果 `dns_proxy` 得到的 IP 在 cn_ip.txt、cn_ipv6.txt 内，是不是也会绕过内核？
2. 为什么 geosite-cn.srs 和 geoip-cn.srs 只会在启动/重启 ShellCrash 的时候检测下载，而执行更新数据任务时只会更新 cn_ip.txt、cn_ipv6.txt？是不是 CN_IP 绕过内核这个功能跟 .srs 规则集没什么关系？
3. 更进一步，我是不是可以简单直接的理解为，只要 sing-box 的 DNS 模块解析到的 IP 地址在 cn_ip.txt、cn_ipv6.txt 内，就会直接绕过内核，而 route 下的 rules 中与 cn_ip.txt、cn_ipv6.txt 有关的的域名分流规则就不起作用了？

感谢哟😊~

**Comment by juewuy** [comment]
@ovnrain 防火墙只能传递IP不能传递域名，启用绕过cn后相关IP不会进入内核，但DNS解析不受影响

**Comment by ovnrain** [comment]
所以总结下来就是：
CN_IP 绕过内核与使用什么 DNS 无关，只要设备得到的 IP 在 cn_ip.txt、cn_ipv6.txt 内就会绕过内核。同理也与规则集没有关系。

```json
{
  "rule_set": "geosite-cn",
  "outbound": "DIRECT"
}
```
但是启用 CN_IP 绕过内核后，上面的路由域名分流规则不一定没用了，如果一个网站在 `geosite-cn` 内，但解析得到的 IP 不在 cn_ip.txt、cn_ipv6.txt 内，那么这个规则还是会有用的。

这样理解对不？

**Comment by suikastar** [comment]
@ovnrain 我觉得你的理解没毛病，我也是这么理解的https://github.com/juewuy/ShellCrash/issues/680

不过你为什么要给你的dns_proxy配置client_subnet，这样解析出来的ip离client_subnet近了，但离你的vps岂不是很远，影响访问速度？

**Comment by ovnrain** [comment]
@suikastar 看的这里 https://bulianglin.com/archives/singbox.html

他的意思是，对于不在 geosite-cn 里面的网站，尽量解析成国内的 IP，这样就可以通过 geoip-cn 直连了

不过你说的好像也有道理，如果得不到国内 IP，就会走代理。不过得看节点位置，如果距离很近，比如香港节点，就能发挥优势了

**Comment by juewuy** [comment]
@ovnrain 是

**Comment by suikastar** [comment]
@ovnrain 你可以利用singbox内核强大的dns分流功能配置，达到无与伦比的ip访问效果（缺点是第一次解析会慢点），实现如果给出的是国内ip，让它离你更近，如果给出的是国外ip，让它离vps更近

https://sing-box.sagernet.org/manual/proxy/client/#__tabbed_2_2

```
{
        "type": "logical",
        "mode": "and",
        "rules": [
          {
            "rule_set": "geosite-geolocation-!cn",
            "invert": true
          },
          {
            "rule_set": "geoip-cn"
          }
        ],
        "server": "google",
        "client_subnet": "114.114.114.114/24" // Any China client IP address
      }
```

**Comment by ovnrain** [comment]
@juewuy 我发现不管 DNS 是什么模式，只要 $CRASHDIR 目录下没有 geosite-cn.srs，启动 ShellCrash 时就会重新下载 geosite-cn.srs，即使我的自定义配置文件里有
```json
{
  "tag": "geosite-cn",
  "type": "remote",
  "format": "binary",
  "url": "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/cn.srs",
  "download_detour": "DIRECT"
}
```
这算不算一个小 bug

**Comment by juewuy** [comment]
@ovnrain 检测到相关规则并且安装目录没有相关数据库就会自动下载

**Comment by ovnrain** [comment]
https://github.com/juewuy/ShellCrash/blob/1acb1464bd8f6ef35b1132feada119202df18b85/scripts/start.sh#L1632

感觉逻辑稍微有点不合理，应该是有使用 "rule_set": "geosite-cn" 且并没有定义 "tag": "geosite-cn" 规则集时才需要下载

如果用户已经自定义了 "tag": "geosite-cn" 规则集，则不需要 ShellCrash 下载，即使下载了也用不上，因为 sing-box 并没有配置规则集的 path 选项，所以并不会使用 ShellCrash 下载的 geosite-cn.srs

geoip-cn.srs 同理

**Comment by juewuy** [comment]
@ovnrain 因为检测自定义这件事本身很难做，就干脆不做了，就这么简单

**Comment by ovnrain** [comment]
OK，小问题

**Comment by ovnrain** [comment]
@suikastar 不是很理解 geoip-cn 和 client_subnet 在 DNS 规则中起到的作用

**Comment by ovnrain** [comment]
@suikastar 我理解这段配置了，"rule_set": "geoip-cn" 是为了过滤结果是否符合

**Comment by suikastar** [comment]
@ovnrain 是的，client_subnet告诉8.8.8.8我要一个离指定IP近点的，logical and用来判断8.8.8.8返回的IP在不在国内，在我就要这个IP了，不在就不要。之后，程序可以重新请求8.8.8.8，拿一个离VPS近点的IP。缺点就是DNS解析慢了点。
