### ISSUE TITLE
[Feature] English translate request

### ISSUE THREAD

**Issue by Cryolitia** [juewuy/ShellCrash#698]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

English translate is not only helpful for non-chinese speakers, but also useful for ASCII console.

![image](https://github.com/juewuy/ShellCrash/assets/23723294/00e0bdf3-cae7-4563-b0fb-940a02c32548)

**Comment by juewuy** [comment]
Sorry, no plans
