### ISSUE TITLE
[Bug] 小米ax3000t用meta内核hysteria2协议，yacd面板延迟driect项不显示延迟

### ISSUE THREAD

**Issue by Tothemoon111222** [juewuy/ShellCrash#699]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

如题，节点速度正常立即出现driect这项却没延迟显示。目前可以用关闭cn-ip再重新开启此项，然后重启内核解决。没有错误显示，也不知道为什么。
话说hysteria2协议占用内存好高，不论meta核心还是singbox。可垃圾vps用这协议是真好用，用别的协议都是500ms以上，这个200多ms.还有送singbox的规则看着好乱，完全不如yaml格式的清晰明了。
最后谢谢大佬的无私奉。如果这问题不好查就算了，反正我能正常使用。

**Comment by Tothemoon111222** [comment]
今天发现不是开关cn-ip能好。而是多次重启内核不一定哪一次就好了。bug期间cn-ip规则不能起作用。

**Comment by juewuy** [comment]
我不确定是不是内核的bug，请尝试切换内核或者使用纯净模式看是否能复现问题

**Comment by zhqu1148980644** [comment]
把证书验证关掉试试

**Comment by Tothemoon111222** [comment]
不要意思，搞了好久发现大概是vps端口被限流或封禁。
