### ISSUE TITLE
[Bug] 小米6500pro开启shellcrash后小米门锁无法连接WiFi

### ISSUE THREAD

**Issue by Cathgao** [juewuy/ShellCrash#701]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

开启shellcrash后门锁无法连接WiFi，摄像头功能全部失效。关闭shellcrash后门锁正常连接，判断为有规则或其他原因导致门锁联网认证不成功。日志里看到有关小米的域名均已直连，但就是要关闭之后才能正常使用门锁摄像头

**Comment by Cathgao** [comment]
已经将门锁的MAC地址手动添加到局域网黑名单中，但问题依旧

**Comment by juewuy** [comment]
@Cathgao 请提供相关面板日志

**Comment by Cathgao** [comment]
从singbox换成Meta之后似乎问题改善了，但meta内核dns模式无论是fake-ip还是mix解析速度都感觉很慢，网页要等好几秒才能刷出来，国内dns用的是doh腾讯阿里，远程dns是doh的cloudflare和opendns

不过目前门锁可以正常使用了，我再观察几天，有问题再反馈
