### ISSUE TITLE
[Feature] 可否提高进程连接数？

### ISSUE THREAD

**Issue by suikastar** [juewuy/ShellCrash#703]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

在启动服务代码的procd_close_instance之前加入一行
procd_set_param limits nofile="65535 65535"
以应对https://github.com/vernesong/OpenClash/issues/402

**Comment by juewuy** [comment]
保守模式是否也会出现同样问题？
另外连接数过高本身也可能导致内核崩溃

**Comment by suikastar** [comment]
@juewuy 有道理，经过[测试](https://qps.itzmx.com/)，512M内存的路由器，同时保持3000连接就是极限了，再高内存爆了路由器就强制重启了
