### ISSUE TITLE
[Bug] 请求援助：开机启动的ShellCrash，PAC配置中返回的地址不正确

### ISSUE THREAD

**Issue by Youwenqwq** [juewuy/ShellCrash#704]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

系统环境：Ubuntu 23.04

ShellCrash版本：1.9.1 beta11，内核版本1.7.1

如题所示，我为ShellCrash设置了开机自启。重启系统后，自启动的ShellCrash提供的PAC配置中，将代理主机返回为223.5.5.5而不是本机IP(192.168.9.3)
![abnormal](https://github.com/juewuy/ShellCrash/assets/25259258/975ff02a-57ba-49dd-9fce-fbde51d9539b)
手动在ShellCrash中按1重启Clash服务后，PAC恢复正常。
![normal](https://github.com/juewuy/ShellCrash/assets/25259258/7daccb91-fd08-4fdd-a557-39fe38e89218)

我想知道这个是为什么，检索了以下issue，没看到很多关于PAC的议题。另外，如果不使用PAC而是直接使用手动配置，可以正常使用Clash。

**Comment by juewuy** [comment]
设置一下启动延迟，这可能是因为网络初始化在脚本启动之后，脚本无法正确获取本机ip

**Comment by Youwenqwq** [comment]
> 设置一下启动延迟，这可能是因为网络初始化在脚本启动之后，脚本无法正确获取本机ip

好的，谢谢qwq
