### ISSUE TITLE
局域网设备无法访问公网ip(路由器wanIP)

### ISSUE THREAD

**Issue by jack338c** [juewuy/ShellCrash#706]
大神好!
Shellcrash代理速度不是一般的快，个人很喜欢！
只是目前局域网设备无法访问自己的域名（路由器wanIP),因为有nas在网络中，需要域名+端口的形式访问nas
不知道这个需要在哪里配置下？

望有空帮解答下
谢谢！

**Comment by juewuy** [comment]
@jack338c 局域网设备过滤

**Comment by jack338c** [comment]
感谢！
和这个一模一样的问题 [https://github.com/juewuy/ShellCrash/issues/596](https://github.com/juewuy/ShellCrash/issues/596)
局域网设备可以通过内网ip访问NAS，就是不可以用域名访问
是不是自己通过改fake_ip_filter.list可以解决？
例如增加域名*.xxx.yy

**Comment by juewuy** [comment]
@jack338c 如果用了fakeip可以尝试在设置里添加域名过滤

**Comment by juewuy** [comment]
@juewuy 如果有效请将相关服务商域名提供一下

**Comment by jack338c** [comment]
> @juewuy 如果有效请将相关服务商域名提供一下

晚点等域名IP固定后再测试反馈结果

**Comment by jack338c** [comment]
刚测试，在路由器/etc/ShellCrash/configs/fake_ip_filter.list加了*.xxx.yy 后
目前还是没解决

**Comment by juewuy** [comment]
@jack338c 尝试把相关域名和内网IP写入路由器hosts文件

**Comment by jack338c** [comment]
> @jack338c 尝试把相关域名和内网IP写入路由器hosts文件

我在openwrt路由器的/etc/dnsmasq.conf加了条address=/*.xxx.yy/10.20.30.217
尝试了没有用,不是很懂这方面，这个应该是域名劫持吧

10.20.30.217是局域网中的nas，10.20.30.217的443端口转发到openwrt（主)的9876上去了，原本用域名https//:*.xxx.yy:9876形式就可以访问（无论用公网还是内网）

**Comment by juewuy** [comment]
@jack338c etc/hosts

**Comment by jack338c** [comment]
> @jack338c etc/hosts

非常感谢！
我再研究研究

**Comment by jack338c** [comment]
@juewuy 今天发现应该是路由器固件问题，因为重置后还是问题依旧，非常抱歉给您添麻烦了。
