### ISSUE TITLE
[Feature] 有没有可能在基础的Clash内核下，开启CN_IP绕过内核？

### ISSUE THREAD

**Issue by bettermanbao** [juewuy/ShellCrash#711]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

首先感谢作者开发这么好的shell模式的clash，我有几个16M Flash/ 64M RAM的路由器，因为配置比较低，只能运行基础的Clash内核。举例TP-Link的WR802N，在停用Clash的情况下，无线可以跑满100Mb，但是运行Clash后，国内网站直连测速直接降到25-30Mb，看到CPU被clash占满了。

所以想请问一下，我知道现在基础版的Clash已经移除了Redir-Host，只保留了fake-ip模式。在fake-ip模式下，有没有可能开启CN_IP绕过内核？感谢！

**Comment by bettermanbao** [comment]
我想到的work around是，能否在内核选择中增加一个最后支持Redir-Host版本的Clash，选择老版本的内核后，可以开启CN_IP绕过内核。

**Comment by juewuy** [comment]
出于安全原因考虑，不会添加，实在有需求可以使用老版本脚本

**Comment by jiejianshiwaxinge** [comment]
16M Flash/ 64M RAM的路由器配置太拉跨了，换个MT7981 128M+256M的也就100元。128M+256M,这是科学上网的最低配置了
