### ISSUE TITLE
asus ax56u v2官方最新固件下使用crash

### ISSUE THREAD

**Issue by alancheng2019** [juewuy/ShellCrash#712]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

asus ax56u v2官方最新固件下路由器重启后crash无法自动启动运行

**Comment by alancheng2019** [comment]
输入crash显示no found,需要重新安装后才能使用运行。

**Comment by juewuy** [comment]
华硕最新固件封堵了之前的自启方式
需要参考 https://www.52asus.com/forum.php?mod=viewthread&tid=18602
进行配置
