### ISSUE TITLE
[Bug] 阿里云云服务器安装后，专用的软件源mirrors.cloud.aliyuncs.com无法联通

### ISSUE THREAD

**Issue by XYZliang** [juewuy/ShellCrash#713]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

应该是和dns解析有关，目前采用的是[这个配置](https://github.com/juewuy/ShellCrash/issues/675#issuecomment-2201549897),meta内核，一键配置加密DNS：
 1 切换防火墙运行模式:  Redir模式
 2 切换DNS运行模式：    redir_host
 3 跳过本地证书验证：   已开启   ————解决节点证书验证错误
 4 只代理常用端口：     未开启   ————用于过滤P2P流量
 5 过滤局域网设备：     未开启   ————使用黑/白名单进行过滤
 7 屏蔽QUIC流量:        未开启   ————优化视频性能
 8 CN_IP绕过内核:       未开启   ————优化性能，不兼容Fake-ip

 1 修改基础DNS
 2 修改PROXY-DNS
 3 重置默认DNS配置
 4 一键配置加密DNS
 5 hosts优化：          已开启  ————调用本机hosts并劫持NTP服务
 6 Dnsmasq转发：        未开启  ————不推荐使用
 7 禁用DNS劫持：        未禁用  ————搭配第三方DNS使用

请问应该如何解决？当然换个公网源也可以解决问题，但是为了稳定还是用阿里云服务器内部专用的这个

**Comment by juewuy** [comment]
@XYZliang 无法定位问题，请先参考面板日志确认是不是规则导致的

**Comment by XYZliang** [comment]
> @XYZliang 无法定位问题，请先参考面板日志确认是不是规则导致的

当时有查看，规则并没有进行任何转发，这个域名直接直连了。
我尝试 ping和 nslookup，似乎问题在于没法解析这个域名ip

**Comment by juewuy** [comment]
@XYZliang DNS模式尝试使用fakeip

**Comment by juewuy** [comment]
@super-organism 将内置DNS地址指向本机，很明显是因为对应地址只有运营商内部DNS服务器才会提供解析

**Comment by XYZliang** [comment]
> @XYZliang 请问你这个问题解决了么 我在最新版本也遇到了,腾讯云的镜像地址mirrors.tencentyun.com解析不到， 在版本1.9.1rc9的2-9 DNS模式 fake-ip其他均为默认 加入到了过滤列表，2-2-4-1增加了基础DNS127.0.0.53（不开启时的默认dns）都无法解决
> 
> 以下为不开启crash正常解析 root@VM-16-4-debian:~# nslookup mirrors.tencentyun.com Server: 127.0.0.53 Address: 127.0.0.53#53
> 
> Non-authoritative answer: Name: mirrors.tencentyun.com Address: 169.254.0.3
> 
> 以下为报错： root@VM-16-4-debian:~# nslookup mirrors.tencentyun.com Server: 127.0.0.53 Address: 127.0.0.53#53
> 
> *** Can't find mirrors.tencentyun.com: No answer
> 
> @juewuy 如无法复现，可私信联系，用我的服务器进行测试

阿里云内网用的是http://mirrors.cloud.aliyuncs.com/ubuntu吧
我测试是正常的

**Comment by Einck0** [comment]
> @XYZliang 请问你这个问题解决了么 我在最新版本也遇到了,腾讯云的镜像地址mirrors.tencentyun.com解析不到， 在版本1.9.1rc9的2-9 DNS模式 fake-ip其他均为默认 加入到了过滤列表，2-2-4-1增加了基础DNS127.0.0.53（不开启时的默认dns）都无法解决
> 
> 以下为不开启crash正常解析 root@VM-16-4-debian:~# nslookup mirrors.tencentyun.com Server: 127.0.0.53 Address: 127.0.0.53#53
> 
> Non-authoritative answer: Name: mirrors.tencentyun.com Address: 169.254.0.3
> 
> 以下为报错： root@VM-16-4-debian:~# nslookup mirrors.tencentyun.com Server: 127.0.0.53 Address: 127.0.0.53#53
> 
> *** Can't find mirrors.tencentyun.com: No answer
> 
> @juewuy 如无法复现，可私信联系，用我的服务器进行测试

请问解决了吗，我也是这个问题，也做了相同的尝试同意不行

**Comment by Whuihuan** [comment]
> @XYZliang 请问你这个问题解决了么 我在最新版本也遇到了,腾讯云的镜像地址mirrors.tencentyun.com解析不到， 在版本1.9.1rc9的2-9 DNS模式 fake-ip其他均为默认 加入到了过滤列表，2-2-4-1增加了基础DNS127.0.0.53（不开启时的默认dns）都无法解决
> 
> 以下为不开启crash正常解析 root@VM-16-4-debian:~# nslookup mirrors.tencentyun.com Server: 127.0.0.53 Address: 127.0.0.53#53
> 
> Non-authoritative answer: Name: mirrors.tencentyun.com Address: 169.254.0.3
> 
> 以下为报错： root@VM-16-4-debian:~# nslookup mirrors.tencentyun.com Server: 127.0.0.53 Address: 127.0.0.53#53
> 
> *** Can't find mirrors.tencentyun.com: No answer
> 
> @juewuy 如无法复现，可私信联系，用我的服务器进行测试

基础DNS换为183.60.83.19,183.60.82.98
