### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Z0221** [juewuy/ShellCrash#714]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

你好,路由器是小米ax3000t,固件版本 MiWiFi 稳定版 1.0.64
已使用了快1个月,之前换过订阅链接没问题,这次换链接后,服务无法启动,手动启动也报错,已经卸载重装,并尝试安装其他版本的,换过其他链接,均无效
![image](https://github.com/user-attachments/assets/03f86b1a-a826-4ee6-b961-bf89fc29d89d)

**Comment by Z0221** [comment]
麻烦看下如何解决,谢谢

**Comment by Z0221** [comment]
@juewuy 那应如何删除呢，或者怎么查是否是内存不足。
但我个人感觉不是内存不足吧，我路由器买来没干什么，里面应该没什么东西，每次导入链接时选择的备份也应该是覆盖吧

**Comment by juewuy** [comment]
@Z0221 更新界面有显示剩余空间

**Comment by juewuy** [comment]
@Z0221 可以尝试更换安装位置或者使用小闪存模式

**Comment by Z0221** [comment]
这上面的回复好像延迟比较大,能否添加你的其他联系方式,tg上我加了频道,但讨论是私密的也进不去
![image](https://github.com/user-attachments/assets/e64629bf-8fcf-447e-81c1-1e5327cc0503)

**Comment by Z0221** [comment]
@juewuy

**Comment by juewuy** [comment]
换一下生成方式，或者多次尝试
