### ISSUE TITLE
无法连接到面板

### ISSUE THREAD

**Issue by knbnaz** [juewuy/ShellCrash#717]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

![QQ_1722141590488](https://github.com/user-attachments/assets/ac6c9109-162e-4bba-a389-9d9eb8af79b4)
无法连接到面板，密码也没错

**Comment by knbnaz** [comment]
> ### Verify steps
> * [x]   我已经在 [Issue Tracker](%E2%80%A6%E2%80%A6/) 中找过我要提出的问题 I have searched on the [issue tracker](%E2%80%A6%E2%80%A6/) for a related issue.
> * [x]   我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists.
> * [x]   我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题
> 
> ### Description
> ![QQ_1722141590488](https://private-user-images.githubusercontent.com/107289432/352789752-ac6c9109-162e-4bba-a389-9d9eb8af79b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxNDE5NDMsIm5iZiI6MTcyMjE0MTY0MywicGF0aCI6Ii8xMDcyODk0MzIvMzUyNzg5NzUyLWFjNmM5MTA5LTE2MmUtNGJiYS1hMzg5LTlkOWViOGFmNzliNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOFQwNDQwNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00Y2U4YWJhZmFhMmRmYjQ2N2E4NzdjYzk2NjM4NGU5MzU2OGRkYmZlYWEzNmUzZDE2M2EwYzZiOTdkMmI1ZmM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BIIfsvw0Y1OJU6KV6YKrwehBGh9HyT8VwVVwj7Cx03w) 无法连接到面板，密码也没错
![image](https://github.com/user-attachments/assets/38902f1e-c8f6-4449-9999-8bf1f96e9ae8)

**Comment by juewuy** [comment]
那就去安装本地面板
