### ISSUE TITLE
[Feature] 能不能给sing-box还有其他内核加个调用mosdns来分流以及dns泄漏等功能呀

### ISSUE THREAD

**Issue by star8618** [juewuy/ShellCrash#719]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

能不能给sing-box还有其他内核加个调用mosdns来分流以及dns泄漏等功能呀

**Comment by juewuy** [comment]
singbox完全不需要搭配mosdns使用
