### ISSUE TITLE
[Bug] 在docker建立后，无法访问面板

### ISSUE THREAD

**Issue by zhuwei** [juewuy/ShellCrash#720]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

开启了面板公网访问也不行
![image](https://github.com/user-attachments/assets/7d3307de-6473-48b8-a3d4-2e79c8842206)

**Comment by juewuy** [comment]
后端地址也要改为你具体能访问的地址例如http://192.168.1.8:9999

**Comment by zhuwei** [comment]
> 后端地址也要改为你具体能访问的地址例如http://192.168.1.8:9999

改了也不行。。。画面刷新后自动恢复成了172.20.0.2

**Comment by juewuy** [comment]
也可能是建立容器时未放行相关端口
