### ISSUE TITLE
[Bug]  jdbc 連線無法代理

### ISSUE THREAD

**Issue by sam0324sam** [juewuy/ShellCrash#721]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

試過各種組合
在 shellcrash + meta 內核什麼模式都試過了，劫持也都劫持了，socks5 也試過了
但是 jdbc 連線資料庫的連線流量就是不會被代理
從面板中就是沒看到連線
debug模式下沒有任何錯誤

改用 windows 的 Clash Verge + meta 內核同一個訂閱只要開啟 tun 就可以正確代理 jdbc 的流量

我目的是要代理java程式的mysql連線

**Comment by juewuy** [comment]
@sam0324sam 不是很清楚jdbc的原理，但是如果socks5都无效，那么问题就不是我能解决的了
通常来说，使用透明路由时，禁用绕过cn以及常用端口过滤可以让更多流量进入内核

**Comment by sam0324sam** [comment]
可是桌面版開clash就可以
很奇怪

jdbc也是走tcp 不應該攔截不到才是
