### ISSUE TITLE
[Bug] 1.9.1beta13 劫持dns无效 面板出现大量的dns请求

### ISSUE THREAD

**Issue by dr-forget** [juewuy/ShellCrash#722]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

1.9.1beta13 clashMeta 劫持dns无效 面板出现大量的dns请求

1.9.0 正常

<img width="700" alt="image" src="https://github.com/user-attachments/assets/5e849548-0000-41d2-86d3-ee75e6255e3d">

**Comment by juewuy** [comment]
https://github.com/juewuy/ShellCrash/commit/b524c6e32a521e9ed699463ebbb4abc133e4430d
