### ISSUE TITLE
[Bug] 访问面板提示404 page not found

### ISSUE THREAD

**Issue by AvatarQing** [juewuy/ShellCrash#723]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

面板地址是 http://192.168.31.1:9999/ui/
这个地址就是启动服务后提示的。

安装了Yacd面板，/data/ShellClash/ui下有文件：
```
root@XiaoQiang:/data/ShellCrash/ui# ls
CNAME                             pac
_headers                          registerSW.js
apple-touch-icon-precomposed.png  sw.js
assets                            yacd-128.png
index.html                        yacd-64.png
manifest.webmanifest              yacd.ico
```

路由器是红米AX6000。

试过重新安装面板、重新安装ShellClash、清除浏览器缓存、换浏览器打开、浏览器隐私模式打开，都不能打开面板。

ShellClash版本信息如下：

```
欢迎使用ShellCrash！		版本：1.9.1beta13
Clash服务正在运行（Redir模式），已设置开机启动！
当前内存占用：29672 kB，已运行：00小时03分13秒
TG频道：https://t.me/ShellClash
-----------------------------------------------
 1 启动/重启服务
 2 内核功能设置
 3 停止内核服务
 4 内核启动设置
 5 配置自动任务
 6 导入配置文件
 7 内核进阶设置
 8 其他工具
 9 更新/卸载
-----------------------------------------------
 0 退出脚本
请输入对应数字 > 1
-----------------------------------------------
服务已启动！
请使用 http://192.168.31.1:9999/ui 管理内置规则
```
```
当前目录(/data/ShellCrash)剩余空间：23.6M
-----------------------------------------------
 1 更新管理脚本    1.9.1beta13 > 1.9.0release stable
 2 切换内核文件    v1.18.5 > v1.18.1
 3 更新数据库文件	> 20240302
 4 安装本地Dashboard面板
 5 安装/更新本地根证书文件
 6 查看PAC自动代理配置
-----------------------------------------------
 7 切换安装源及安装版本
 8 配置自动更新
 9 卸载ShellCrash
-----------------------------------------------
99 鸣谢！
-----------------------------------------------
 0 返回上级菜单
-----------------------------------------------
```

当前内核： meta v1.18.5
当前系统处理器架构： arm64

当前版本：稳定版 当前源：Cloudflare_CDN源

**Comment by juewuy** [comment]
@AvatarQing 是否自定义了user.yaml？以及去掉/ui能否有内核信息返回

**Comment by AvatarQing** [comment]
> @AvatarQing 是否自定义了user.yaml？以及去掉/ui能否有内核信息返回

还没有自定义user.yaml，/data/ShellCrash、/data/ShellCrash/yamls都没有user.yaml。
去掉/ui，访问http://192.168.31.1:9999/返回的是{"hello":"clash"}

**Comment by juewuy** [comment]
@AvatarQing 尝试更换其他面板

**Comment by AvatarQing** [comment]
试了所有面板都不行，安装完后打开还是404.
有的时候安装面板会提示 curl: (28) SSL connection timeout ，不知是否是这个问题，是不是有一些东西没安装上？                                    

```
请选择面板安装类型：
-----------------------------------------------
 1 安装Yacd面板(约1.1mb)
 2 安装Yacd-Meta魔改面板(约1.5mb)
 3 安装MetaXD面板(约1.5mb)
 4 安装基础面板(约500kb)
 5 安装Meta基础面板(约800kb)
 9 卸载本地面板
 0 返回上级菜单
请输入对应数字 > 2
-----------------------------------------------
请选择面板安装目录：
-----------------------------------------------
 1 在/data/ShellCrash/ui目录安装
 2 在/www/clash目录安装
-----------------------------------------------
 0 返回上级菜单
请输入对应数字 > 1
-----------------------------------------------
正在连接服务器获取安装文件…………
curl: (28) SSL connection timeout                                              

####                                                                        5.7%
```

**Comment by juewuy** [comment]
@AvatarQing 尝试/www/clash目录

**Comment by AvatarQing** [comment]
www目录是只读的创建不了文件夹，面板下载后解压不了
```
root@XiaoQiang:/www# mkdir clash
mkdir: can't create directory 'clash': Read-only file system
```

不过又是root登陆的：
```
root@XiaoQiang:/www# id
uid=0(root) gid=0(root)
```

不行就放弃了。。

**Comment by juewuy** [comment]
@AvatarQing 不行就用在线面板吧

**Comment by AvatarQing** [comment]
通过[yacd在线面板](https://yacd.metacubex.one/#/configs)配置后端地址，填写以下的后端地址都提示Failed to connect。
http://192.168.31.1:9999
http://192.168.31.1:9090

路由器在局域网的ip是192.168.31.1

/data/ShellCrash/config.yaml 中 external-controller: :9999
external-controller不管修改成什么，每次clash服务重启后都会变成:9999。

部分config.yaml配置：
```
mixed-port: 7890
redir-port: 7892
tproxy-port: 7893
authentication: [""]
allow-lan: true
mode: Rule
log-level: info
ipv6: true
external-controller: :9999
external-ui: ui
secret:
tun: {enable: false}
experimental: {ignore-resolve-fail: true, interface-name: en0}
```

**Comment by juewuy** [comment]
尝试用singbox内核呢？

**Comment by AvatarQing** [comment]
切换到singbox内核好了

**Comment by zenvzenv** [comment]
我也遇到了同样的问题，切换成singbox内核也没好，请问应该怎么弄
浏览器访问http://192.168.31.1:9999/ ，返回的是{"hello":"clash"}
浏览器访问http://192.168.31.1:9999/ui，返回404 page not found

**Comment by juewuy** [comment]
@zenvzenv 更新里安装本地面板

**Comment by zenvzenv** [comment]
我是用的版本是1.9.1rc9，已经安装了Yacd本地面板，但 http://[192.168.31.1:9999/ui/](http://192.168.31.1:9999/ui/) 还是404 page not found
其余配置没有改动
www目录是只读的创建不了文件夹，面板下载后解压不了

**Comment by juewuy** [comment]
手动解压上传，检查目录空间是否不足

**Comment by zenvzenv** [comment]
磁盘空间是充足的，还有30多M，也手动上传文件试过了，还是不行😥

**Comment by juewuy** [comment]
@zenvzenv 什么设备/系统

**Comment by zenvzenv** [comment]
红米路由器AX6000

**Comment by Maozai-Teng** [comment]
我也遇到了相同的情况，然后找到解决方法了~：）
问题原因是没有允许在 https 网站加载 http 内容。
解决方式只要对第三方部署的面板设置允许不安全内容加载即可。
（我的是360极速浏览器，这样子设置就行了）
![Image](https://github.com/user-attachments/assets/d72f8276-baf2-4f88-aad6-6f6e0760e130)

**Comment by Maozai-Teng** [comment]
上面那个只能暂时解决，完美方法是关掉这个网站的安全设置

![Image](https://github.com/user-attachments/assets/249a475b-c11d-46f7-8758-0a29e784c90c)

**Comment by fossilya** [comment]
我今天在重新安装的时候，也遇到了同样的问题，发现是重新安装之后，原来运行的clash进程没有结束，kill掉之后重启，就没有404这个问题了，希望对你有帮助
