### ISSUE TITLE
[Bug] 无法访问pincong.rocks

### ISSUE THREAD

**Issue by chuwza** [juewuy/ShellCrash#725]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

大佬你好，我是OpenWrt 22.03.5安装的ShellCrash，我发现很奇怪的是无法访问pincong.rocks（机场没有禁，因为使用Clash For Windows就能访问）
![image](https://github.com/user-attachments/assets/d0266079-1550-4143-8c70-d9111702dde5)

第一个表现为访问过后，连接里压根没有pincong.rocks，
![image](https://github.com/user-attachments/assets/fb63316e-719d-495b-bfd5-91db18457e61)

第二个表现是OpenWrt ping pincong.rocks，返回
PING pincong.rocks (0.0.0.0): 56 data bytes
64 bytes from 127.0.0.1: seq=0 ttl=64 time=0.103 ms
64 bytes from 127.0.0.1: seq=1 ttl=64 time=0.143 ms
64 bytes from 127.0.0.1: seq=2 ttl=64 time=0.154 ms
64 bytes from 127.0.0.1: seq=3 ttl=64 time=0.123 ms
64 bytes from 127.0.0.1: seq=4 ttl=64 time=0.148 ms

![image](https://github.com/user-attachments/assets/ae70f7c7-9f16-459c-a6fd-24d5d78f25b0)

我这边两台不同地点的OpenWrt都是这样的表现，并且关掉ShellCrash或者依然打开ShellCrash的情况下，打开Clash For Windows就又能访问pincong.rocks了，所以排除机场的问题和网络本身的问题，貌似问题就是出在ShellCrash上😭

不知道大佬能不能复现这个问题呢？

所以请问是什么问题呢？还是ShellCrash把pincong.rocks屏蔽了？（这应该不可能吧）

**Comment by juewuy** [comment]
@chuwza 应该是DNS污染

**Comment by chuwza** [comment]
> @chuwza 应该是DNS污染

感谢大佬回复，我试了一下，关闭“5 hosts优化：调用本机hosts并劫持NTP服务”，就能访问了，但是很多头像加载不出，有办法解决吗？
![image](https://github.com/user-attachments/assets/206142ae-601a-425e-8126-4d4d3464e7ff)

**Comment by juewuy** [comment]
@chuwza 尝试DNS用fakeip活着mix模式

**Comment by xiandu999-yu** [comment]
DNS污染，倒是换DNS试试啊...

**Comment by chuwza** [comment]
> DNS污染，倒是换DNS试试啊...换模式有什么用...

并没有……最后靠换fake ip模式解决……

**Comment by xiandu999-yu** [comment]
![image](https://github.com/user-attachments/assets/ff021c32-621c-48b9-bc7a-315474e8b7d0)
![image](https://github.com/user-attachments/assets/8884f50f-1635-4f6e-b41a-8bf41a28e164)
![image](https://github.com/user-attachments/assets/b6555c9c-b920-40b0-bed2-490352b113c4)
![image](https://github.com/user-attachments/assets/925c709f-fd60-465e-9e5e-457aebc89377)
我的DNS构成[doge]
