### ISSUE TITLE
[Bug] sing-box 内核，DNS mix 模式，domain_regex 列表匹配规则不对

### ISSUE THREAD

**Issue by ovnrain** [juewuy/ShellCrash#726]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

```json
{
  "domain_regex": [
    "time.*.com",
    "time.*.gov",
    "time.*.edu.cn",
    "time.*.apple.com",
    "time1.*.com",
    "time2.*.com",
    "time3.*.com",
    "time4.*.com",
    "time5.*.com",
    "time6.*.com",
    "time7.*.com",
    "ntp.*.com",
    "ntp1.*.com",
    "ntp2.*.com",
    "ntp3.*.com",
    "ntp4.*.com",
    "ntp5.*.com",
    "ntp6.*.com",
    "ntp7.*.com",
    "xbox.*.*.microsoft.com",
    ".*.*.xboxlive.com",
    "xbox.*.microsoft.com",
    "stun.*.*",
    "stun.*.*.*",
    ".+.stun.*.*",
    ".+.stun.*.*.*",
    ".+.stun.*.*.*.*",
    ".+.stun.*.*.*.*.*"
  ],
  "server": "dns_direct"
}
```

上面是 DNS mix 模式生成的一段配置，但其实字符串形式的正则表达式写法不对，如果要匹配 `.`，应该使用双反斜杠进行转义。比如官方文档 https://sing-box.sagernet.org/zh/configuration/dns/rule/ 有写：

```json
{
  "domain_regex": ["^stun\\..+"]
}
```

以第一个 `time.*.com` 为例，目前它可以匹配非常多的范围，只要域名里出现 timexxxxxxcom 形式的字符串就会被匹配，比如它可以匹配纽约时报的域名 `cn.nytimes.com`，然后由于使用了 `dns_direct`，假如它是一个被墙的域名，很有可能得到一个被污染的 IP，就可能导致无法访问

所以正确的写法应该是 `time\\..*\\.com`，其他同理

**Comment by juewuy** [comment]
https://github.com/juewuy/ShellCrash/commit/b524c6e32a521e9ed699463ebbb4abc133e4430d
