### ISSUE TITLE
[Bug] crash自身的自动任务有些问题

### ISSUE THREAD

**Issue by ydoKFVJQDymJcb** [juewuy/ShellCrash#727]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

通过crash自身的自动任务，设置了路由器重启，在cron也看见了
`0 6 * * 2,4,6 /etc/ShellCrash/task/task.sh 122 在每周2,4,6的6点整重启路由设备(慎用)`
到时间后路由器日志也有
`Thu Aug 8 06:00:00 2024 cron.err crond[3901]: USER root pid 3343 cmd /etc/ShellCrash/task/task.sh 122 在每周2,4,6的6点整重启路由设备(慎用)`
但实际路由器并没有重启
我之后通过crash添加了自定义任务
`202#reboot#reboot`
再设定自动任务
`0 11 * * 2,4,6 /etc/ShellCrash/task/task.sh 202 在每周2,4,6的11点整reboot`
任务就可以生效

防火墙重启后重设透明路由防火墙
也是有问题的

另外设置10点的任务会变成`0 10 * * 2,4,6 /etc/ShellCrash/task/task.sh 202 在每周2,4,6的1日点整reboot`，10点变成了1日点

**Comment by juewuy** [comment]
直接使用reboot命令可能导致一些硬件时间同步而产生的循环重启等问题，所以添加了touch /etc/banner，可以自行添加命令解决
时间这个我就不是很清楚了，本地无法复现
