### ISSUE TITLE
[Feature] Crash使用SingBox时自动生成的配置文件中`inbounds`增加`domain_strategy`可选项

### ISSUE THREAD

**Issue by ydoKFVJQDymJcb** [juewuy/ShellCrash#728]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

不配置[domain_strategy](https://sing-box.sagernet.org/configuration/shared/listen/#domain_strategy)时
singbox 默认不会用域名去匹配ip规则
作为小白用户的我认为国内有geoip兜底了
结果造成国内流量走代理（度盘通过`antpcdn.com`走了我1个G，甚至我现在去下载度盘客户端，连接都是`https://d8caa5-1956185688.antpcdn.com:19001/b/pkg-ant.baidu.com/issue/netdisk/yunguanjia/BaiduNetdisk_7.44.5.2.exe`）

虽然我知道可以自行上传`inbounds.json`覆盖配置
但还是希望能增加可选项，减少后来人踩坑
在`inbounds`中添加`"domain_strategy":"prefer_ipv4"`或`"domain_strategy": "prefer_ipv6"`
用户可以选择不添加

---

再补充一个我知道的国内流量走代理会导致的问题
家中的部分智能家居会联网失败。有些和地理位置挂钩的软件也会受影响，
比如天气（`api.weathercn.com`）另外我是发现洗衣机（`access.smartmidea.net`）没法遥控后才排查发现geoip未被使用，走代理了。 
之前用clash时，就算加了`no-resolve`也没这个情况。应该和singbox的设计有关。

**Comment by juewuy** [comment]
@ydoKFVJQDymJcb 但是这个默认值应该就是ipv4优先，而且应该对解决你遇到的问题没什么帮助

**Comment by juewuy** [comment]
@ydoKFVJQDymJcb 好吧，检测一下是否有geoip再加

**Comment by Wil1em** [comment]
@juewuy 不建议内置"domain_strategy":"prefer_ipv4"，更建议改为可手动开关的可选项，实测更新后多了该选项后对没有启用ipv6（仅ipv4）的设备环境下会出问题，观察下貌似dns会多出ipv6的查询导致访问国内网站变慢，手动在脚本中删去该选项后beta14版本运行恢复正常

**Comment by Wil1em** [comment]
@ydoKFVJQDymJcb 我这边是电脑访问斗鱼网站看直播时出现问题，观看主播直播时会提示查询失败、弹幕功能也会受到影响，使用同样的配置删除domain_strategy就恢复正常了

**Comment by shallbytwo** [comment]
不建议加 这不是shellcrash的配置，这更应该是使用singbox内核的配置问题
