### ISSUE TITLE
[Bug] shellclash部署后，xbox 无法在游戏内联机对战

### ISSUE THREAD

**Issue by vonnycsl** [juewuy/ShellCrash#729]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

路由器型号斐讯k3，梅林固件，看面板的记录，微软了系列连接已经是direct，但是在xsx xss内玩地平线4和5 始终无法联机对战。截图奉上，希望能告知原因。谢谢
![Uploading 屏幕截图 2024-08-11 052022.png…]()

**Comment by juewuy** [comment]
截图打不开
暂时能提供的解决办法就是使用局域网设备过滤
