### ISSUE TITLE
[Feature] https证书错误

### ISSUE THREAD

**Issue by mymicroblog** [juewuy/ShellCrash#730]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

用的sing-box 1.9.3内核，访问https被墙网站全部报证书错误
<img width="531" alt="image" src="https://github.com/user-attachments/assets/460531a9-9c50-4315-bdea-62eeb2125ae0">

更新本地根证书文件，也不行。
配置如下：
<img width="612" alt="image" src="https://github.com/user-attachments/assets/fa6d952d-0599-4d83-87dd-6980a3631f5d">

**Comment by juewuy** [comment]
@mymicroblog DNS污染

**Comment by mymicroblog** [comment]
> @mymicroblog DNS污染

按文档设置了fake-ip模式、关闭安全DNS还是没解决

**Comment by juewuy** [comment]
@mymicroblog 尝试禁用ipv6

**Comment by honeway** [comment]
我遇到这个问题是因为之前在浏览器里设置了 自定义的DNS url，取消就可以了。供参考。

**Comment by mymicroblog** [comment]
mix模式解决了
