### ISSUE TITLE
[Feature]  ShellCrash可以添加自定义规则模板吗？好像没有这个功能。。

### ISSUE THREAD

**Issue by gxutmj** [juewuy/ShellCrash#731]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

ShellCrash可以添加自定义规则模板吗？好像没有这个功能。
![屏幕截图 2024-08-11 224229](https://github.com/user-attachments/assets/6a00f29b-0ceb-41fe-89a6-758fdf98af64)

**Comment by juewuy** [comment]
可以用6-2实现任意自定义的后端地址及模版
