### ISSUE TITLE
[Bug] 不支持shadowsocks 2022在线配置生成

### ISSUE THREAD

**Issue by qzydustin** [juewuy/ShellCrash#732]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

复现方式：
版本：1.9.1beta13，内核sing-box 1.9.0
菜单6-1
导入ss://MjAyMi1ibGFrZTMtYWVzLTEyOC1nY206VEVTVFBBU1NXT1JEQDEyNy4wLjAuMTo4MDgw
FATAL[0000] parse outbound[3]: bad key length, required 16, got 9
自定义配置文件校验失败，请检查【/etc/ShellCrash/jsons/】文件！

**Comment by juewuy** [comment]
用6-3生成
