### ISSUE TITLE
[Bug] 安装后 /etc/passwd里，自动增加了一个root用户？？

### ISSUE THREAD

**Issue by esojourn** [juewuy/ShellCrash#735]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

![image](https://github.com/user-attachments/assets/cceee862-7a14-4cf4-aaae-b65008c7b315)
偶然查看 /etc/passwd。看到这个很震惊。可以解释一下吗？
为何新增用户？而且用户ID是0？
也希望能请其他用户看一下，是否有同样的用户出现？

**Comment by bsdcpp** [comment]
大佬说的是，只有在你开启了劫持本机的时候才会有这个用户
