### ISSUE TITLE
[Bug] LXC下 Tproxy 无法启用

### ISSUE THREAD

**Issue by soulwhisper** [juewuy/ShellCrash#736]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

我看过其他类似 issue 的内容和相关的源码了。
Proxmox 中 LXC 承继 proxmox 主机启用的内核模块，"modprobe" 这条指令在 LXC 中是默认报错的。
源码中通过 `modprobe nft_tproxy` 的方式判定系统是否支持相关模块的方式在 LXC 中行不通，建议增加 LXC 选项/说明，通过 `lsmod | grep nft` 判断 LXC 内是否包含相关模块。
在 BUG 修复前，应该只有 物理机 / WSL2 / VM 这类有内核隔离的部署方式支持 modprobe

示例：
1，LXC 中 modprobe 默认报错，报错中的目录不存在于 LXC 中
![image](https://github.com/user-attachments/assets/7b3b99e4-2dfd-4339-b361-52b5b4152481)
2，同个LXC中，运行`lsmod | grep nft`
![image](https://github.com/user-attachments/assets/24232766-8064-4312-95c7-6b261897f439)

**Comment by juewuy** [comment]
https://github.com/juewuy/ShellCrash/commit/f359cb866e629d8a543d0cf4a9c34cfb727ce54e
