### ISSUE TITLE
[Bug] SingBox内核，设置里vmess节点的tls里insecure=true，依然无法联网。

### ISSUE THREAD

**Issue by honeway** [juewuy/ShellCrash#739]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

ss节点是正常的。

![image](https://github.com/user-attachments/assets/c6d9de84-6765-41a2-902f-ccdc189d514f)

![image](https://github.com/user-attachments/assets/d2e1b36c-388f-438d-ac87-f6217b10f171)

**Comment by honeway** [comment]
是用的内置的在线生成。 SS的节点是正常的。 切换成clash内核，则 SS和Vmess节点都可以正常。

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: juewuy ***@***.***>
发送时间: Sunday, August 25, 2024 9:01:00 PM
收件人: juewuy/ShellCrash ***@***.***>
抄送: Henry ***@***.***>; Author ***@***.***>
主题: Re: [juewuy/ShellCrash] [Bug] SingBox内核，设置里vmess节点的tls里insecure=true，依然无法联网。 (Issue #739)


信息不足无法判断原因，建议先用脚本内置的方式生成配置而不是使用手搓

―

**Comment by honeway** [comment]
切换内核时重置后，可以了。 clash内核和 singbox内核都可以上网了。 不过 singbox内核时，web ui代理界面， vmess节点不显示ping值。这个是正常的吗？clash内核正常。

**Comment by juewuy** [comment]
那就有可能是内核方面的某些问题了，我这里无法解决

**Comment by ajmz** [comment]
> 那就有可能是内核方面的某些问题了，我这里无法解决

1.9.1脚本，singbox内核，也没法用vmess节点在线生成配置文件。
切换meta内核，相同的vmess节点链接，就能生成。
再切换回singbox内核，保留配置文件，singbox可以识别vmess的配置文件，并正常启动和使用。
