### ISSUE TITLE
[Bug] Unraid安装并启动之后，丢失ipv6

### ISSUE THREAD

**Issue by tediorelee** [juewuy/ShellCrash#741]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

已参考过#248，使用tproxy模式并打开所有ipv6选项，启动之后丢失ipv6，表现为ddns无法检测到ipv6地址，`curl test.ipw.cn`也不只能返回v4地址. unraid不支持`ip6tables --table nat --flush clashv6`命令

**Comment by juewuy** [comment]
这种情况就关掉ipv6劫持，只打开ipv6dns，应该是ip6tables功能不完整导致的

**Comment by tediorelee** [comment]
> 这种情况就关掉ipv6劫持，只打开ipv6dns，应该是ip6tables功能不完整导致的

好的, 今晚尝试一下
