### ISSUE TITLE
[Bug] telegram改了个名被bot给ban了🤣

### ISSUE THREAD

**Issue by kingsey** [juewuy/ShellCrash#742]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

₍₍٩( ᐛ )۶₎₎♪ [753199101] 想要被群组接受，你的名字和姓氏必须不能有阿拉伯字符. 
处理: 已踢出 ❗️
改了个颜文字的名称，然后一说话直接被ban了🤣，改名加回去了。现在在群里，但是被禁言中。有空看能解一下吗

**Comment by juewuy** [comment]
请在群内私聊管理员
