### ISSUE TITLE
[Bug]  openwrt 安装shellcrash 启用tun模式  有时提示“找不到tun模块，放弃启动tun相关防火墙规则！” 

### ISSUE THREAD

**Issue by gxutmj** [juewuy/ShellCrash#746]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

[Bug]  openwrt 安装shellcrash 启用tun模式  有时提示“找不到tun模块，放弃启动tun相关防火墙规则！” 需要重启几个才可以。如何解决？

**Comment by juewuy** [comment]
@gxutmj 这种一般是性能问题，建议使用tproxy模式
