### ISSUE TITLE
[Bug] 卸载后不会一起删除网卡，导致服务器DNS被劫持

### ISSUE THREAD

**Issue by dogpem** [juewuy/ShellCrash#747]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

卸载后不会一起删除网卡，导致服务器DNS被劫持，导致服务器不可用
找了很久，才想起来是这个的问题😫

**Comment by juewuy** [comment]
正常是肯定可以卸载的，请提供具体问题截图
