### ISSUE TITLE
support for juicity

### ISSUE THREAD

**Issue by dasfdsa123** [juewuy/ShellCrash#748]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

tuic is no longer maintained.
we need new protocol to replace tuic.
Juicity is an improvement over tuic and is currently being actively updated.

**Comment by juewuy** [comment]
It's not my job, and support may not be provided by upstream
