### ISSUE TITLE
[question] 怎么手动添加分流策略呢

### ISSUE THREAD

**Issue by jiashu1024** [juewuy/ShellCrash#749]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

你好，请教一下，像用qx临时给一些域名添加分流让他走别的策略组操作起来很方便，但是qx很多协议不支持。用shellcrash的话，有什么方式可以便捷的添加这种规则呢？

**Comment by juewuy** [comment]
@jiashu1024 6-6
