### ISSUE TITLE
[Bug] YACD面板无法显示内存信息

### ISSUE THREAD

**Issue by ixbcqq** [juewuy/ShellCrash#750]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

为啥YACD面板无法显示内存信息呢？我的路由器是redmi AX6000。
![image](https://github.com/user-attachments/assets/6c6bf46e-3598-4cc5-a3dd-5bc54f1ed387)
![image](https://github.com/user-attachments/assets/cb5f0cc4-331b-4568-ad6f-8c2e27ef0db8)

**Comment by juewuy** [comment]
尝试更换内核，这不是我能解决的问题

**Comment by ixbcqq** [comment]
> 尝试更换内核，这不是我能解决的问题

感谢回复，不折腾这些了哈哈，能用就行
