### ISSUE TITLE
[Bug] ax9000上一直报错

### ISSUE THREAD

**Issue by EuHs** [juewuy/ShellCrash#751]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

ax9000突然报错，无论重装多少次，装好后重启服务都这样：
/data/ShellCrash/start.sh: line 26: can't open /tmp/ShellCrash/web_proxies: no such file
sed: /tmp/ShellCrash/cron_root: No such file or directory
mv: can't rename '/tmp/ShellCrash/shellcrash_pac': No such file or directory
FATAL[0000] decode config at /tmp/ShellCrash/jsons/outbounds.json: server: json: unknown field "server"
自定义配置文件校验失败，请检查【/data/ShellCrash/jsons/】文件！
尝试使用基础配置文件启动~

**Comment by juewuy** [comment]
@EuHs 检查/tmp目录是否存在异常，比如说空间不足，有日志文件过大等
