### ISSUE TITLE
Singbox-p内核，在lxc容器中无法使用tproxy和tun模式

### ISSUE THREAD

**Issue by hww-png** [juewuy/ShellCrash#753]
![image](https://github.com/user-attachments/assets/cf1bd4e9-9ac2-46d2-bfdb-d5c551181a07)![image](https://github.com/user-attachments/assets/a057e609-2501-4a56-b69d-a186d72e1d90)

**Comment by juewuy** [comment]
这是因为宿主机缺少相关依赖

**Comment by hww-png** [comment]
> 这是因为宿主机缺少相关依赖

**Comment by hww-png** [comment]
> 这是因为宿主机缺少相关依赖

麻烦大佬告知一下需要安装哪几个依赖，谢谢

**Comment by juewuy** [comment]
@hww-png 启动或者切换模式时有提示

**Comment by hww-png** [comment]
> @hww-png 启动或者切换模式时有提示

切换tproxy模式时，上图有显示缺少nft_proxy内核，但是我用apt list｜ grep proxy 没有看到可以安装的文件

**Comment by juewuy** [comment]
@hww-png 那应该就是不支持吧，你可以尝试一下最新测试版
