### ISSUE TITLE
[Bug] 每次重启之后SSH的公钥都被重置了

### ISSUE THREAD

**Issue by persiliao** [juewuy/ShellCrash#754]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

每次重启之后SSH的公钥都被重置了，导致需要删除本地的known_hosts文件中的行，才能重新进行连接
![image](https://github.com/user-attachments/assets/b0e78543-9798-4b6d-8840-406658c5d2f0)

**Comment by juewuy** [comment]
工具里重新设置一下小米软固化

**Comment by persiliao** [comment]
试了几次，重启之后问题依旧

**Comment by persiliao** [comment]
设备是小米AX3000T 系统现在是最新版的，之前刷过47版的，然后升级后的，Clash功能正常，SSH功能也能正常使用

**Comment by juewuy** [comment]
@persiliao 去安装目录看是否存在密钥文件，如果存在就删掉，如果不存在就把系统的密钥复制一份进去

**Comment by persiliao** [comment]
@juewuy 问题解决了，通过看源码才知道，原来我之前47版本的时候装了一个auto ssh的脚本，然后ShellCrash里面同样也有一个auto ssh的操作，然后就冲突了，导致的，我卸载了我之前的auto ssh，然后就正常了。 感谢大佬，回复真及时
