### ISSUE TITLE
[Bug] 华硕天选路由器redict模式连接不进入核心

### ISSUE THREAD

**Issue by YANGTIANZHEN1** [juewuy/ShellCrash#755]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

 v1.9.1beta15脚本sing-box 1.10.0-alpha.29-067c81a7内核，华硕天选路由器redict模式连接不进入核心且无法切换tproxy模式。用 v1.9.1beta13可以正常使用。

**Comment by juewuy** [comment]
尝试更新最新版本
