### ISSUE TITLE
[Feature] 如何修改 fake-ip 的网段？

### ISSUE THREAD

**Issue by jearton** [juewuy/ShellCrash#756]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

默认是198.18.0.0/16，我想修改这个

**Comment by juewuy** [comment]
@jearton 不支持修改
