### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by kimmmmmmmy** [juewuy/ShellCrash#757]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

能不能优化一下内存使用 之前1.8几的时候用singbox即使长时间大流量使用最高占用内存也100多M结束进程后还会自动优化内存 现在1.9多看一点yt不到3个小时就内存占用300多M 之后直接爆内存 而且结束进程后内存也没有自动优化减少使用

**Comment by juewuy** [comment]
@kimmmmmmmy 正常使用内存通常不会超过60mb，超过的话需要自行结合面板日志连接等信息排查原因

**Comment by calvin886886** [comment]
我的环境是ax3600 一样是到1.9.不到两小时就会奔溃打不开网页.现在要降级还一直搞不定

**Comment by juewuy** [comment]
@calvin886886 请观察面板日志和链接有无异常流量
