### ISSUE TITLE
[Bug] 1.9.1rc2 自动任务 更新并重启 导致无法连接网络

### ISSUE THREAD

**Issue by dr-forget** [juewuy/ShellCrash#760]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

<img width="412" alt="image" src="https://github.com/user-attachments/assets/01d3ee28-cb5b-4bc6-9efb-d55350e231a1">
<img width="667" alt="image" src="https://github.com/user-attachments/assets/cd8c44a2-b75f-4058-9d2f-961227a0d080">
<img width="793" alt="image" src="https://github.com/user-attachments/assets/a47fc3d1-90b4-4222-9854-0cb6b5822022">
<img width="457" alt="image" src="https://github.com/user-attachments/assets/8a6eb70a-dd07-4c5c-aca5-7583eb1fd2e4">
界面均显示启动成功 无异常 但是 web UI界面的内存管理  无法读取  一直是0  也无法联网 
<img width="2530" alt="image" src="https://github.com/user-attachments/assets/49baaf6b-f99a-4795-867e-79c1e311f279">
（这图是手动启动成功的图，如果自动任务的 话  这个地方就一直是0  手动重启则恢复成功）
系统版本：debian12.5

**Comment by juewuy** [comment]
@dr-forget 之前版本正常吗？这块代码很久没有改动过了

**Comment by dr-forget** [comment]
> @dr-forget 之前版本正常吗？这块代码很久没有改动过了

1.9.0 正常的 更新公测版以后  两个版本都有这问题

**Comment by juewuy** [comment]
@dr-forget OK，我回头看一下

**Comment by juewuy** [comment]
本地无法复现，请提供一下问题复现后的8-1-4结果

**Comment by dr-forget** [comment]
> 本地无法复现，请提供一下问题复现后的8-1-4结果

@juewuy 大佬复现了  版本1.9.1 rc3
<img width="597" alt="image" src="https://github.com/user-attachments/assets/54a4ba74-9203-4f93-a81a-28fc175b25c0">
<img width="707" alt="image" src="https://github.com/user-attachments/assets/84d3c934-656c-423a-ab72-89e00f21f291">
<img width="428" alt="image" src="https://github.com/user-attachments/assets/0edf0d6e-d0dc-44ba-ad4e-23c061be1b64">
<img width="2371" alt="image" src="https://github.com/user-attachments/assets/36ba14cf-4df8-4e3c-a51f-5c876c911f84">

**Comment by dr-forget** [comment]
> 本地无法复现，请提供一下问题复现后的8-1-4结果

很奇怪  如果我手动 立即执行一次  就没有问题  如何是定时任务触发  就有这问题

**Comment by juewuy** [comment]
> > 本地无法复现，请提供一下问题复现后的8-1-4结果
> 
> 很奇怪  如果我手动 立即执行一次  就没有问题  如何是定时任务触发  就有这问题

这可能是定时任务本身权限不足的原因导致的，我这边没什么好的解决办法

**Comment by dr-forget** [comment]
> 本身权限不足的原因导致的，我这边没什么好的解决办法，确保定时任务是写在root用户文件

这个要怎么看呢   什么都没动过  1.9.0版本是正常的

**Comment by juewuy** [comment]
@dr-forget 我不确定，事实上这块儿代码我也没动过

**Comment by dr-forget** [comment]
大佬 我更新到1.9.1rc9 了这个问题还是存在    自动更新重启以后 路由规则没有了  
Error: No such file or directory
list table inet shellcrash

**Comment by dr-forget** [comment]
大佬 自定义了一条启动命令行 前面sudo 就行了  sudo $CRASHDIR/start.sh update_config

**Comment by juewuy** [comment]
@dr-forget 什么设备

**Comment by dr-forget** [comment]
@juewuy  mini 主机 系统是debian12.5
