### ISSUE TITLE
[Bug] 6-6-5修改后启动报错

### ISSUE THREAD

**Issue by Become-ILLUSORY** [juewuy/ShellCrash#761]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

依据6-6-5，进行了修改dns,log,inbounds，后启动报错
“[root@OpenWrt:11:28 AM ~] # 服务启动失败！请查看报错信息！详细信息请查看/tmp/ShellCrash/core_test.log
+0000 2024-09-10 03:28:58 ERROR router: failed to initialize geosite: read geosite: code category-ads-all not exists!
+0000 2024-09-10 03:28:58 ERROR router: failed to initialize geosite: read geosite: code geolocation-!cn not exists!
+0000 2024-09-10 03:28:58 ERROR router: failed to initialize geosite: read geosite: code geolocation-!cn not exists!
FATAL[0000] start service: initialize inbound/mixed[mixed-in]: listen tcp 0.0.0.0:4399: bind: address already in use”
当取消修改inbounds时则可以正常运行。

{
  "inbounds": [
    {
      "type": "mixed",
      "tag": "mixed-in",
      "listen": "::",
      "listen_port": 4399,
      "domain_strategy": "prefer_ipv4",
      "tcp_fast_open": true,
      "tcp_multi_path": true,
      "users": [
        {
          "username": "xxxx",
          "password": "xxx"
        }
      ],
      "sniff": false
    },
    {
      "type": "direct",
      "tag": "dns-in",
      "listen": "::",
      "listen_port": 1053,
      "domain_strategy": "prefer_ipv4",
      "tcp_fast_open": true,
      "tcp_multi_path": true
    },
    {
      "type": "redirect",
      "tag": "redirect-in",
      "listen": "::",
      "listen_port": 7892,
      "domain_strategy": "prefer_ipv4",
      "tcp_fast_open": true,
      "tcp_multi_path": true,
      "sniff": true,
      "sniff_override_destination": true
    },
    {
      "type": "tproxy",
      "tag": "tproxy-in",
      "listen": "::",
      "listen_port": 7893,
      "domain_strategy": "prefer_ipv4",
      "tcp_fast_open": true,
      "tcp_multi_path": true,
      "sniff": true,
      "sniff_override_destination": true
    }
  ]
}

**Comment by Become-ILLUSORY** [comment]
@juewuy 取消修改inbounds,改为修改outbounds,且仅通过更改所有匹配项修改了节点tag，报错FATAL[0000] start service: outbound tag DIRECT duplicated

**Comment by juewuy** [comment]
@Become-ILLUSORY 如果你不了解如何使用及修改内核配置文件，请不要自行修改

**Comment by Become-ILLUSORY** [comment]
> @Become-ILLUSORY 如果你不了解如何使用及修改内核配置文件，请不要自行修改

但是同样的，我裸核可以跑通 0.o

**Comment by juewuy** [comment]
@Become-ILLUSORY 那就请自行debug，这里不负责教学
