### ISSUE TITLE
[Bug] 1.9.1.rc2 依旧存在大量的 `iptables: No chain/target/match by that name.` 错误

### ISSUE THREAD

**Issue by abcfy2** [juewuy/ShellCrash#763]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

问题描述应该跟 #758 一样，升级到 1.9.1.rc2之后，无论延迟启动设置多长时间，甚至禁用，都无法解决这个错误

**Comment by juewuy** [comment]
那我无法定位问题原因了，之前不是说问题已经解决了吗

**Comment by abcfy2** [comment]
之前的rc1版本问题没有了，更新到rc2这个问题又出现了，这两天我debug一下脚本看看，到底是哪里出的问题

**Comment by abcfy2** [comment]
暂时关闭，升级到rc3版本又没这个问题了
