### ISSUE TITLE
[Bug] 路由器开启IPv6，发现dns泄漏，关闭ipv6后正常

### ISSUE THREAD

**Issue by shallbytwo** [juewuy/ShellCrash#766]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

路由器是红米AX6000，在网络设置里开启ipv6可以获取公网ip，shellcrash内核使用的是sing-box 1.9.4。
不开启ipv6前，未发现dns泄漏，开启后测试出现DNS泄漏，不管shellcrash内开启与否“代理ipv6流量”功能都一样。
排查原因时，将shellcrash配置DNS.rule设置所有规则走google的DOH，路由规则也全改为走代理，仍然出现泄漏。
停止运行shellcrash测试：同配置使用电脑/手机上singbox客户端在一样网络环境（连接路由器WI-FI）测试无dns泄漏。

怀疑是开启IPV6后，shellcrash未全面接管DNS导致，希望作者有空测试排查下，谢谢。

ip6tables -L结果如下：
[iptables.txt](https://github.com/user-attachments/files/16997140/iptables.txt)

测试泄漏时部分sellcrash日志如下：
[infodebug.txt](https://github.com/user-attachments/files/16997143/infodebug.txt)

**Comment by shallbytwo** [comment]
结论：是因为开启了“过滤局域网设备”功能导致ipv6无法被shellcrash处理，使用mac地址过滤解决问题。

**Comment by shallbytwo** [comment]
已解决

**Comment by Kulov233** [comment]
遇到了同样的问题，感谢老哥提供的解决方案。感觉可以在按IP过滤局域网设备时加个提示，比如“如果局域网设备开启了IPv6则请优先使用设备MAC进行过滤，否则可能导致内核DNS失效”
