### ISSUE TITLE
[Bug] be86u 官方固件使用稳定版，singbox内核、meta内核访问jd部分页面打不开，用的tproxy模式，dns是redirect

### ISSUE THREAD

**Issue by El1ter** [juewuy/ShellCrash#767]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

![Uploading bug.jpg…]()

**Comment by juewuy** [comment]
@El1ter 请首先尝试测试版

**Comment by El1ter** [comment]
24-09-14 17:21:01[ warn ][TCP] dial Domestic (match DomainSuffix/jd.com) 192.168.50.161:61077 --> qdsdk.jd.com:443 error: connect failed: dial tcp 117.72.226.3:443: i/o timeout connect failed: dial tcp [2408:8719:64:91:8000::3]:443: connect: cannot assign requested address
24-09-14 17:20:56[ warn ][TCP] dial Domestic (match DomainSuffix/jd.com) 192.168.50.161:61076 --> qdsdk.jd.com:443 error: connect failed: dial tcp 117.72.226.3:443: i/o timeout connect failed: dial tcp [2408:8719:64:91:8000::3]:443: connect: cannot assign requested address
24-09-14 17:20:55[ warn ][TCP] dial Domestic (match DomainSuffix/jd.com) 192.168.50.161:61075 --> qdsdk.jd.com:443 error: connect failed: dial tcp 117.72.226.3:443: i/o timeout connect failed: dial tcp [2408:8719:64:91:8000::3]:443: connect: cannot assign requested address
24-09-14 17:20:55[ warn ][TCP] dial Domestic (match DomainSuffix/jd.com) 192.168.50.161:61074 --> qdsdk.jd.com:443 error: connect failed: dial tcp 117.72.226.3:443: i/o timeout connect failed: dial tcp [2408:8719:64:91:8000::3]:443: connect: cannot assign requested address
24-09-14 17:20:51[ warn ][TCP] dial Domestic (match DomainSuffix/jd.com) 192.168.50.161:61073 --> qdsdk.jd.com:443 error: connect failed: dial tcp 117.72.226.3:443: i/o timeout connect failed: dial tcp [2409:8c38:c50:603:8000::3]:443: connect: cannot assign requested address
24-09-14 17:20:49[ warn ][TCP] dial Domestic (match DomainSuffix/jd.com) 192.168.50.161:61071 --> qdsdk.jd.com:443 error: connect failed: dial tcp 117.72.226.3:443: i/o timeout connect failed: dial tcp [2409:8c38:c50:603:8000::3]:443: connect: cannot assign requested address
24-09-14 17:20:49[ warn ][TCP] dial Domestic (match DomainSuffix/jd.com) 192.168.50.161:61069 --> qdsdk.jd.com:443 error: connect failed: dial tcp 117.72.226.3:443: i/o timeout connect failed: dial tcp [2409:8c38:c50:603:8000::3]:443: connect: cannot assign requested address
24-09-14 17:20:46[ warn ][TCP] dial Domestic (match DomainSuffix/jd.com) 192.168.50.161:61061 --> imgcps.jd.com:443 error: connect failed: dial tcp 117.72.226.3:443: i/o timeout

**Comment by El1ter** [comment]
24-09-14 17:43:34[ warn ][TCP] dial Domestic (match DomainSuffix/jd.com) 192.168.50.161:61536 --> imgcps.jd.com:443 error: connect failed: dial tcp 117.72.226.3:443: i/o timeout
24-09-14 17:43:39[ warn ][TCP] dial Domestic (match DomainSuffix/jd.com) 192.168.50.161:61539 --> imgcps.jd.com:443 error: connect failed: dial tcp 117.72.226.3:443: i/o timeout
24-09-14 17:43:45[ warn ][TCP] dial Domestic (match DomainSuffix/jd.com) 192.168.50.161:61544 --> ipay.jd.com:443 error: connect failed: dial tcp 117.72.226.3:443: i/o timeout connect failed: dial tcp [2408:8719:64:1f:8000::3]:443: connect: cannot assign requested address dial tcp [2408:8719:64:91:8000::3]:443: connect: cannot assign requested address
24-09-14 17:43:45[ warn ][TCP] dial Domestic (match DomainSuffix/jd.com) 192.168.50.161:61543 --> ipay.jd.com:443 error: connect failed: dial tcp 117.72.226.3:443: i/o timeout connect failed: dial tcp [2409:8c38:c50:603:8000::3]:443: connect: cannot assign requested address
24-09-14 17:43:43[ warn ][TCP] dial Domestic (match DomainSuffix/jd.com) 192.168.50.161:61542 --> imgcps.jd.com:443 error: connect failed: dial tcp 117.72.226.3:443: i/o timeout
24-09-14 17:43:42[ warn ][TCP] dial Domestic (match DomainSuffix/jd.com) 192.168.50.161:61541 --> imgcps.jd.com:443 error: connect failed: dial tcp 117.72.226.3:443: i/o timeout

已经更新至1.9.1rc2，meta v1.18.7，还是有问题

**Comment by juewuy** [comment]
@El1ter 看不出来问题，感觉像是DNS污染

**Comment by juewuy** [comment]
@El1ter 访问https://117.72.226.3，后明显感觉浏览器出现异常，怀疑是病毒网站

**Comment by El1ter** [comment]
> @El1ter 看不出来问题，感觉像是DNS污染

有办法解决么

**Comment by El1ter** [comment]
> @El1ter 访问[https://117.72.226.3，后明显感觉浏览器出现异常，怀疑是病毒网站](https://117.72.226.3%EF%BC%8C%E5%90%8E%E6%98%8E%E6%98%BE%E6%84%9F%E8%A7%89%E6%B5%8F%E8%A7%88%E5%99%A8%E5%87%BA%E7%8E%B0%E5%BC%82%E5%B8%B8%EF%BC%8C%E6%80%80%E7%96%91%E6%98%AF%E7%97%85%E6%AF%92%E7%BD%91%E7%AB%99)

这是jd钱包的一个综合页面，怎么会这样，反正用流量是没问题

**Comment by El1ter** [comment]
问题解决了，dns解析的问题，阿里和腾讯的dns解析jd的域名有问题，换成运营商的dns就正常了
