### ISSUE TITLE
[Feature] 支持 Clash.Meta rule-anchor 配置方式

### ISSUE THREAD

**Issue by steveqx** [juewuy/ShellCrash#769]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

Clash.meta 的 rule-anchor 可以方便简化重复性的配置

Config Example
rule-anchor:
  ip: &ip {type: http, interval: 86400, behavior: ipcidr, format: mrs}
  domain: &domain {type: http, interval: 86400, behavior: domain, format: mrs}
rule-providers:
  private_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs"
  cn_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs"
  biliintl_domain:

希望添加 rule-anchor
scripts/start.sh Line 441 

yaml_char='proxies proxy-groups proxy-providers rules rule-providers'
改为
yaml_char='proxies proxy-groups proxy-providers rules rule-anchor rule-providers'

**Comment by juewuy** [comment]
下个版本适配meta内核mix模式时会考虑添加

**Comment by AquanJSW** [comment]
这个问题也困扰我很久了，是否可以考虑用`yq`进行anchor解析 (例如`cat src.yaml | yq -o json | yq -o yaml -P > dst.yaml`)，并将`yq`设置为可选依赖？

毕竟anchor本身没有约束，例如我所使用的`health-check`，且可能出现在任何地方

这种情况下加入`yaml_char`的价值并不大

@juewuy

**Comment by juewuy** [comment]
大部分设备都没有预装jq或者yq，我拿什么预置这种命令

**Comment by AquanJSW** [comment]
我的意思是需要anchor的一般都是自己配置config的高级用户，这个时候让用户自己部署yq就行了
脚本里的这一行yq命令设为不抛出错误就行了

**Comment by juewuy** [comment]
@AquanJSW 所以为什么不加到user.yaml里？

**Comment by AquanJSW** [comment]
@juewuy 也是个方法，我只是觉得mihomo本身可以解析的配置，用ShellCrash却不能直接用，才有的这个workaround

确实，正如你所言，引入了额外的依赖不太优雅
