### ISSUE TITLE
[Bug] N1盒子的openwrt系统无法运行

### ISSUE THREAD

**Issue by siren202101** [juewuy/ShellCrash#776]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

注意：安装ShellCrash至少需要预留约1MB的磁盘空间
 1 在/etc目录下安装(适合root用户)
 2 在/usr/share目录下安装(适合Linux系统)
 3 在当前用户目录下安装(适合非root用户)
 4 在外置存储中安装
 5 手动设置安装目录
 0 退出安装
-----------------------------------------------
请输入相应数字 > 1
df: /etc: can't find mount point
目标目录/etc空间剩余：
确认安装？(1/0) > 

请输入相应数字 > 1
df: /etc: can't find mount point
目标目录/etc空间剩余：
确认安装？(1/0) > 1
-----------------------------------------------
开始从服务器获取安装文件！
-----------------------------------------------
################################################################################################################################################################################### 100.0%
-----------------------------------------------
开始解压文件！
root@OpenWrt:~# 
然后就没然后了。。。。。。。
大佬如何解决？

**Comment by juewuy** [comment]
@siren202101 换个目录

**Comment by siren202101** [comment]
> @siren202101 换个目录

所有选项都试过了。。。。

**Comment by juewuy** [comment]
@siren202101 那感觉是系统有问题吧，可能有文件锁或者目录没挂载
