### ISSUE TITLE
[Feature] Add some fake-ip-filter

### ISSUE THREAD

**Issue by S8Cloud** [juewuy/ShellCrash#777]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

Pixel 手机上请求相关地址用于AI等内置服务，判断 IP 是否在符合国家
现行规则
```
lens.l.google.com
stun.l.google.com
na.b.g-tun.com
```
修改为
```
+.l.google.com
+.g-tun.com
+.googleapis.com
```

Wifi Calling 部分添加如下地址：
```
+.ls.apple.com
+.ondemandconnectivity.com
```
[Source](https://shuzijumin.com/thread-3552-1-1.html)

仅供参考

**Comment by juewuy** [comment]
好的，已经添加，下次请修改后直接pr过来即可

**Comment by juewuy** [comment]
此次修改引发了大面积的网络问题，本次更新会被回退，请妥善给出更详细的域名列表以解决此问题

**Comment by juewuy** [comment]
@S8Cloud googleapis.com应用范围太广泛，会导致部分用户谷歌系APP无法打开，最好能具体到下一级域名

**Comment by juewuy** [comment]
@S8Cloud 我觉得还是单独解决你提出的某些AI服务访问的问题，其他问题等遇到再处理，另外singbox的DNS实现逻辑不一样，相对也更怕污染

**Comment by kingsey** [comment]
> ```
> phosphor-pa.googleapis.com
> beryllium-pa.googleapis.com
> # g-tun 前缀较多
> +.g-tun.com
> *.ba.l.google.com
> ```
> 
> <img alt="image" width="250" src="https://private-user-images.githubusercontent.com/27051990/371501807-a3bd2aa3-171b-4277-8032-d4ec64562e77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0ODg0MTUsIm5iZiI6MTcyNzQ4ODExNSwicGF0aCI6Ii8yNzA1MTk5MC8zNzE1MDE4MDctYTNiZDJhYTMtMTcxYi00Mjc3LTgwMzItZDRlYzY0NTYyZTc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI4VDAxNDgzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3Y2I2MWVmYTFhNDlmYWRmNzY1M2EwNjBlM2RkNzQyNDYzMmJiMGRlZWFkODJkMzg0NTVlYjQzZDM4ZWE5YzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2GVUhxlUFudGPAjljSyUUj44bVC-NGYdt4fG9taWsHI"> <img alt="image" width="357" src="https://private-user-images.githubusercontent.com/27051990/371505785-eee1bde4-e33c-46d0-bdbd-5b6e3a799035.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0ODg0MTUsIm5iZiI6MTcyNzQ4ODExNSwicGF0aCI6Ii8yNzA1MTk5MC8zNzE1MDU3ODUtZWVlMWJkZTQtZTMzYy00NmQwLWJkYmQtNWI2ZTNhNzk5MDM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI4VDAxNDgzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1MjMyODg4YzY4YWU2Nzc0YzFhMjI4MWUxMzA4NTI0NDMyN2ZmYWQ2NzNkN2RiOTU4Y2UwM2EyNDFiMmMwOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ED6MuamKFPQQ8xWZ3xIhRsvZ9uEWCtUg1M7I2Y6H8HY">
> 但是仍然需要在 fallback-filter 添加 g-tun.com, google.com, googleapis.com

用nameserver-policy吧，fallback-filter这种老旧配置该退休了 : )

**Comment by juewuy** [comment]
看不到图片，fallback主要还是为了兼容老版本内核

**Comment by juewuy** [comment]
话说回来，我还是没弄懂为什么fake-ip下这些地址会出现问题？

**Comment by juewuy** [comment]
@S8Cloud 但是这和分流有关，和fakeip似乎并没有关联，原则上只要分流正确，fakeip直接发送远端，直接由服务器进行访问，似乎并没有被谷歌抓包的道理
另外就是过于小众的需求，还请尝试使用脚本提供的自定义fakeipfilter列表功能

**Comment by kingsey** [comment]
> googleapi 在国内有服务器，解析出 geoip:cn 也有可能 [2dust/v2rayNG#1234](https://github.com/2dust/v2rayNG/issues/1234)

访问http://www.youtobe.com/red，如果提示Premium在您所在的国家/地区尚未推出，那就是节点服务器被送中了，googleapi会被扔回国内的服务器
