### ISSUE TITLE
[Bug] 命令运行无响应

### ISSUE THREAD

**Issue by DreamsCat** [juewuy/ShellCrash#778]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

运行命令后，会一直卡住无法继续下一步:
<img width="650" alt="image" src="https://github.com/user-attachments/assets/ace3a9cc-5c61-4118-9e68-a9e451819b10">
也无法打开 Debug 模式，输入之后也一直卡着，想更新也一样，运行了就无响应了，现在想启动都启动不了，不知道如何排查，想开启 Debug 模式输出异常日志，还是一样输入命令后就无反应了，之前稳定用了有半年，最近出现的。

**Comment by juewuy** [comment]
@DreamsCat 尝试卸载重装

**Comment by DreamsCat** [comment]
> @DreamsCat 尝试卸载重装

运行卸载命令也无反应，那我直接手工删吧

**Comment by juewuy** [comment]
@DreamsCat 直接覆盖安装

**Comment by DreamsCat** [comment]
> @DreamsCat 直接覆盖安装

好的，我覆盖安装试试

**Comment by Cathgao** [comment]
你是不是按一个教程用了mihomo内核并且加了自动更新mihomo的自动任务，然后又在脚本里切换到了singbox？我今天就遇到了这个问题，原因就是前面说的。去目录把mihomo内核删了之后就不会卡住了

**Comment by DreamsCat** [comment]
> 你是不是按一个教程用了mihomo内核并且加了自动更新mihomo的自动任务，然后又在脚本里切换到了singbox？我今天就遇到了这个问题，原因就是前面说的。去目录把mihomo内核删了之后就不会卡住了

您好，请问一下 mihomo内核在什么目录？我没有按一个教程用了mihomo内核并且加了自动更新mihomo的自动任务，但是我试过切换到 singbox 脚本

**Comment by Cathgao** [comment]
删除cshellclash安装目录和/tmp/shellclash目录下所有类似于`crashcore.*`的大文件

**Comment by DreamsCat** [comment]
> 停止服务 删除cshellclash安装目录和/tmp/shellclash目录下所有类似于`crashcore.*`的大文件 然后再脚本里再次更新需要的核心

感谢，我清理了好像还是有点问题，我把所有目录全删了，然后重启路由器重新安装就可以了，再次感谢
