### ISSUE TITLE
[Feature]2022-blake3-aes-128-gcm算法的节点

### ISSUE THREAD

**Issue by mib1125** [juewuy/ShellCrash#779]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

目前似乎不支持2022-blake3-aes-128-gcm算法的节点，订阅列表里有这类节点的话会导致服务启动失败，是不是可以增加支持啊，或者能跳过也行。
![QQ_1727016733451](https://github.com/user-attachments/assets/11189655-e30d-4119-b3aa-9bc4fb786eb3)

**Comment by juewuy** [comment]
@mib1125 更换内核
