### ISSUE TITLE
多入口及多出口

### ISSUE THREAD

**Issue by RecursionHs** [juewuy/ShellCrash#785]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

![image](https://github.com/user-attachments/assets/b76752f5-b07e-4323-a853-8e95c1fa72f8)
![image](https://github.com/user-attachments/assets/60ee0db5-efcb-4b8a-b8df-90da073a12a8)

 通过 将clash yaml配置转换为上面图的 yaml 配置倒入到通过windows 下 v2rayN。可以实现一个端口对应一个机场节点。

我现在想在linux下实现，该如何实现呢？

**Comment by juewuy** [comment]
@RecursionHs 6-6，参考提示

**Comment by RecursionHs** [comment]
> @RecursionHs 6-6，参考提示

谢谢哥，大概看了下好像是那么回事，我找时间研究下，如果ok的话，我把配置贴上来，方便以后的兄弟。

**Comment by RecursionHs** [comment]
> @RecursionHs 6-6，参考提示

你是我的神啊哥，我昨天研究了一天，还不如你这一句话。


/etc/ShellCrash/yamls/others.yaml
这个配置文件中专门有#listeners的配置，加入多端口的配置即可
如：
```shell
listeners:
  - name: mixed3
    type: mixed
    port: 42003
    proxy: 香港|HK01
  - name: mixed4
    type: mixed
    port: 42004
    proxy: 香港|HK02
  - name: mixed5
    type: mixed
    port: 42005
    proxy: 香港|HK03
``` 

重启crash，可以看到监听端口已经ok
