### ISSUE TITLE
[Feature] singbox 的配置文件修改后重启会恢复默认配置

### ISSUE THREAD

**Issue by BANG404** [juewuy/ShellCrash#787]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

由于校园网的DNS是固定的，禁用别的DNS，我想修改DNS文件中dns_resolver的address ，但每次修改完重启服务的时候都会变回223.5.5.5

**Comment by BANG404** [comment]
希望出个自定义dns_resolver地址的功能

**Comment by Alwayswithme** [comment]
`/etc/ShellCrash/jsons/`
自定义singbox模块

2-2-4 DNS进阶设置 都实现不了？
