### ISSUE TITLE
[Feature] 出一个对singbox优化的面板

### ISSUE THREAD

**Issue by BANG404** [juewuy/ShellCrash#788]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

目前存在的面板对singbox的交互不好，比如规则，没有clash查阅方便
![image](https://github.com/user-attachments/assets/c5064fb9-3894-4c5b-bc09-e63019587024)

**Comment by juewuy** [comment]
@BANG404 你可以自己尝试编写一个更好的
