### ISSUE TITLE
规则问题

### ISSUE THREAD

**Issue by xiaoqi2020** [juewuy/ShellCrash#790]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

请问大佬，如何自定义规则呀？以前用openwrt的时候可以自己指定某某网站出国还是不出国，crash确实没看到哪里可以自己指定类似的访问规则

**Comment by juewuy** [comment]
@xiaoqi2020 6-6
