### ISSUE TITLE
[Bug] 红米AX3000使用一段时间后死机

### ISSUE THREAD

**Issue by LianXi0954** [juewuy/ShellCrash#791]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

官方新老固件都这样，具体表现为无法上网，手机断开wifi后无法重新连接，电脑进后台特别卡无法加载
刷固件后使用clash没有问题

**Comment by juewuy** [comment]
@LianXi0954 内存不行，官固自身占用太高，需要合理优化规则，用cn绕过
