### ISSUE TITLE
[Bug] openwrt 添加自动更新透明代理5-1-11-8

### ISSUE THREAD

**Issue by bsdcpp** [juewuy/ShellCrash#792]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

https://github.com/juewuy/ShellCrash/blob/2401c2737cecfd1c4c26b718a3eb9ca1723bb7be/scripts/start.sh#L1842
应该是这行，由于新op是fw4，没有匹配到fw3，导致/etc/init.d/firewall每行都会添加重启任务。

改为匹配grep -En "fw[0-9]+ restart"可以解决

**Comment by juewuy** [comment]
将在rc7修复
