### ISSUE TITLE
[Feature] 部分机场开启了UA限制，希望能加一个针对proxy-providers的User-Agent配置

### ISSUE THREAD

**Issue by guluguru** [juewuy/ShellCrash#794]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

RT

**Comment by juewuy** [comment]
@guluguru 比如？

**Comment by juewuy** [comment]
@guluguru 如果是手写的配置文件，需要你更新到支持内核版本
