### ISSUE TITLE
[Feature] 能不能添加服务端支持

### ISSUE THREAD

**Issue by truewhile** [juewuy/ShellCrash#795]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description
现在脚本我看了一下sing-box导入的配置文件是被处理后运行的，配置的inbounds是脚本固定的，能不能把
导入的配置文件里inbounds中type不为tun,mixed,tproxy其他类型保留，毕竟如果有公网ip软路由还能当个中
转，连上路由器的代理就能访问家里网络也是一个应用，passwall等其他应用也有针对服务端的配置

**Comment by juewuy** [comment]
@truewhile 可以使用自定义配置文件功能
https://juewuy.github.io

**Comment by truewhile** [comment]
可以了，弄好了

**Comment by wangyucst** [comment]
> 可以了，弄好了

老哥我也有这个功能需求，可以请教一下吗？
