### ISSUE TITLE
sed: cannot rename /etc/sedGEm9ci: Device or resource busy

### ISSUE THREAD

**Issue by shaoyunhao0107** [juewuy/ShellCrash#796]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

sed: cannot rename /etc/sedGEm9ci: Device or resource busy

**Comment by juewuy** [comment]
@shaoyunhao0107 检查闪存空间，或者检查相关目录权限

**Comment by perry0002** [comment]
我也遇到这个问题了，在 docker中安装了 ubuntu，想在 ubuntu 里面使用 shellcrash。请问这两个文件起什么作用
sed: cannot rename /etc/sedm3sjqn: Device or resource busy
sed: cannot rename /etc/sedPIe3UV: Device or resource busy
