### ISSUE TITLE
[Feature]我不太懂，问的不合适，请别介意。 请问，如何进行用户的流量控制？

### ISSUE THREAD

**Issue by aomidata** [juewuy/ShellCrash#798]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

我想在手机端的app增加用户的流量控制，确保我的两个用户（实际上就是我2个儿子），流量是可控的，避免它们玩物丧志。请问，该怎么配置？

**Comment by juewuy** [comment]
@aomidata clash或者singbox并不是为流控而生的应用，你最多只能手动/定时切断其网络

**Comment by bsdcpp** [comment]
> ### Verify steps
> * [x]   我已经在 [Issue Tracker](%E2%80%A6%E2%80%A6/) 中找过我要提出的问题 I have searched on the [issue tracker](%E2%80%A6%E2%80%A6/) for a related issue.
> * [x]   我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists.
> * [x]   我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题
> 
> ### Description
> 我想在手机端的app增加用户的流量控制，确保我的两个用户（实际上就是我2个儿子），流量是可控的，避免它们玩物丧志。请问，该怎么配置？

我做过一些简单的尝试，在rules:指定某些ip（路由器配静态ip）走sub-rule，例如:
在自己的config里加入
```bash
proxy-groups:
 - name: "🎮 行为管控"
    type: select
    proxies:
      - DIRECT
      - REJECT
      - PASS
    
rules:
 - ....
 - SUB-RULE,(OR,((SRC-IP-CIDR,192.168.2.5/32),(SRC-IP-CIDR,192.168.2.6/32))),Behavior-rule

Behavior: # 自定义上网管控IP
    type: http
    behavior: classical
    path: ./rule_provider/Behavior
    url: url_to_Behavior
    interval: 86400
```
在sc的yamls/others.yaml里添加:
```bash
sub-rules:
  Behavior-rule:
    - RULE-SET,Behavior,REJECT
    - MATCH,🎮 行为管控
```
在url_to_Behavior里加ip/域名，比较粗略。
