### ISSUE TITLE
[Bug] 关于sc和dockerd冲突的问题

### ISSUE THREAD

**Issue by bsdcpp** [juewuy/ShellCrash#801]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

系统ImmortalWrt 23.05.4，干净安装shellcrash最新版

一旦安装dockerd，任何模式应该都会遇到，表现为lan设备无法上网，路由器本身好的。停止sc或者卸载dockerd后解决，调查后发现是
dockerd带了个文件：/etc/sysctl.d/12-br-netfilter-ip.conf，在其中开了如下配置：
```bash
# Do not edit, changes to this file will be lost on upgrades
# /etc/sysctl.conf can be used to customize sysctl settings

# enable bridge firewalling for docker
net.bridge.bridge-nf-call-ip6tables=1
net.bridge.bridge-nf-call-iptables=1
```
不知道是什么问题。

### 以下是gpt的回答 ：
在 OpenWrt 或其他基于 Linux 的系统中，`net.bridge.bridge-nf-call-iptables=1` 和 `net.bridge.bridge-nf-call-ip6tables=1` 这两个参数会将桥接网络的数据包交给 `iptables` 或 `ip6tables` 来处理。启用这些参数后，内核会对通过桥接接口的数据包执行 `iptables` 规则。

**对 `shellcrash` 的影响：**

1. **网络数据包的处理顺序**：启用这两个参数后，所有通过桥接接口的数据包会经过 `iptables` 规则处理，`shellcrash` 可能依赖某些特定的网络流量规则来正常工作。如果这些数据包由于新的 `iptables` 规则被拦截、修改或丢弃，可能会导致 `shellcrash` 无法正常运行。

2. **性能影响**：开启 `net.bridge.bridge-nf-call-iptables` 可能导致桥接网络上的所有数据包都要经过防火墙规则处理，增加了额外的负载，特别是在大量数据流量通过 Docker 容器时。这可能间接影响到与网络性能相关的 `shellcrash` 规则。

3. **防火墙规则优先级**：启用这些选项后，防火墙规则在处理桥接流量时的顺序和优先级可能会变化，从而干扰现有的 `shellcrash` 规则。如果 `shellcrash` 的流量被其他规则提前处理或拦截，就会导致其功能异常。

### 解决方法：

1. **禁用这些选项**：如果 `shellcrash` 依赖的网络规则在启用这些选项后不再工作，最简单的解决方法是禁用 `net.bridge.bridge-nf-call-iptables=0` 和 `net.bridge.bridge-nf-call-ip6tables=0`。

2. **调整 `iptables` 规则**：检查 `iptables` 的防火墙规则，并根据需要调整 `shellcrash` 和 Docker 的规则，以确保两者的流量不冲突。

3. **指定规则作用范围**：在 `iptables` 中更精确地定义哪些接口或流量需要特殊处理，减少与桥接网络的冲突。

通过这些调整，可以避免桥接网络与 `shellcrash` 之间的冲突，同时保留 Docker 网络的正常运行。

想听听大佬的意见。

**Comment by juewuy** [comment]
@bsdcpp 脚本防火墙模式使用iptables即可

**Comment by bsdcpp** [comment]
一样有问题，并且这个bridge-nf-call-iptables配置还有个NAT loopback 的冲突：
https://git.kos.org.cn/aio-3399b/coolsnowwolf_lede/commit/daacfa70716ce48f172862ae987c661a8cb4ef36

**Comment by juewuy** [comment]
@bsdcpp 那你还是把这个配置文件中相关参数改成0吧

**Comment by bsdcpp** [comment]
嗯，基于这两个问题，肯定要设置0的
