### ISSUE TITLE
[Bug]  不知哪里出错

### ISSUE THREAD

**Issue by suocean16** [juewuy/ShellCrash#802]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

我测试了很多个 
https://bigmesub001.azure-api.net/happy/api/v1/client/subscribe?token=092b5ff81736418cc39b2ae04f142e77
类似这样的链接。 （以上url 仅为示意）

每个链接都显示。配置文件校验失败 及时用您推荐的 “https://app.bigmess.org/” 也不行。 

********************************************************
错误提示如下：

是否启动服务以使配置文件生效？(1/0) > 1
-----------------------------------------------
error msg="yaml: line 11: found character that cannot start any token"
自定义配置文件校验失败！将使用基础配置文件启动！
错误详情请参考 /tmp/ShellCrash/error.yaml 文件！

**Comment by suocean16** [comment]
> @suocean16 配置文件有问题

非常感谢你的回复。 我找不到哪里错了。 总是在这里
1  用"在线生成clash配置文件"   写入 URL 。
2  用“本地上传完整配置文件”  拷贝其他clash 的配置文件。
都不可以。 

请您指导。 


![image](https://github.com/user-attachments/assets/56b56a09-0244-4be7-ad5c-510c4a6d7f11)

**Comment by juewuy** [comment]
@suocean16 确认没上传过自定义配置文件吗？或者你可以尝试卸载重装一下

**Comment by suocean16** [comment]
问题的原因是  输入 输入密码时候，使用了特殊字符。 
已经解决。 多谢！

**Comment by lfscqk67** [comment]
> 问题的原因是 输入 输入密码时候，使用了特殊字符。 已经解决。 多谢！

怎么搞的老哥，我也遇到了
