### ISSUE TITLE
[Bug] 已切换到Meta。但是自动订阅并没有增加vless服务器

### ISSUE THREAD

**Issue by ccpaging** [juewuy/ShellCrash#803]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

例如：
vless://12345c01-e58e-4602-8f7c-041edd1c0df8@test.hxxxxxxd.xyz:31014?mode=multi&encryption=none&flow=xtls-rprx-vision&security=reality&sni=www.nvidia.com&fp=chrome&pbk=qhTzYYIg12345YR79oxftqdo1kzL-1_hGJKfqrOliCY&type=vless&headerType=none#%E4%BA%9A%E6%B4%B201

**Comment by juewuy** [comment]
@ccpaging 重新生成配置文件
