### ISSUE TITLE
[Bug] 我的路由器安装shellcrash后工作正常，但是只要一改变网络环境，比如拿去朋友家，就工作异常，内外网都失效，要卸载从装才能使用，有没有好的解决办法呢

### ISSUE THREAD

**Issue by ca972008** [juewuy/ShellCrash#804]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

比如拿去朋友家，WAN口的ip发生改变了，就什么都访问不了，需要卸载后再安装再导入才能使用。

**Comment by juewuy** [comment]
@ca972008 我不会算命

**Comment by ca972008** [comment]
感谢大佬回复，可能是我这个路由器MT300N-V2配置有点低，32+128的，还是要感谢大佬开发，能让这么差的机器流畅的运行科学环境

我再胡乱折腾折腾

**Comment by xd19861224** [comment]
补充：To use xtls-rprx-vision, ensure your server is upgrade to Xray-core v1.8.0+

**Comment by ca972008** [comment]
把内存换成256m后，已经完美解决，更换网络环境后，不需要卸载重装了
