### ISSUE TITLE
最近安装shellclash，总是提示错误，而且有无法正常使用。

### ISSUE THREAD

**Issue by xd19861224** [juewuy/ShellCrash#805]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

最近安装shellclash，无法正常使用,总是提示错误:获取到了配置文件【/tmp/ShellCrash/clash_config.yaml】，但似乎并不包含正确的节点信息！
![image](https://github.com/user-attachments/assets/23682fc6-f3a2-4ee1-bac1-3a025cbaefaf)

**Comment by juewuy** [comment]
@xd19861224 机场限制，换其他方式生成
