### ISSUE TITLE
shellclash错误提示：To use xtls-rprx-vision, ensure your server is upgrade to Xray-core v1.8.0+，请问shellclash如何升级xray？

### ISSUE THREAD

**Issue by xd19861224** [juewuy/ShellCrash#806]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

shellclash错误提示：To use xtls-rprx-vision, ensure your server is upgrade to Xray-core v1.8.0+，请问shellclash如何升级xray？

**Comment by juewuy** [comment]
更新里使用meta或者singbox内核

**Comment by xd19861224** [comment]
我试试
