### ISSUE TITLE
[Bug] 1.9.1rc9 版本的 shellcrash.service 文件丢失

### ISSUE THREAD

**Issue by ALexei-Stukov** [juewuy/ShellCrash#807]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

1. 主要功能没问题。遵循blog的步骤，可以在ubuntu上启动转发并访问google。

2. 【添加开机启动】的功能有Bug。shell显示“添加成功”，但是按 0 返回 menu.sh 的主菜单后，主菜单始终显示“未添加开机启动”。
重启机器，发现确实没有开机启动转发。

3.排查问题，发现存放 service 的文件夹内没有出现 shellcrash.service 。
作为对比：我的笔记本上运行着1.9.1 beat8 版本，我能在存放 service 的文件夹内找到 shellcrash.service 文件
（我的PC系统是ubuntu 22.04，笔记本系统是ubuntu 20.04）

4.已经证实的解决方案：
复制笔记本系统的shellcrash.service，放入PC内，并使其enable。
重启机器，发现可以开机自启动。

5.我希望 shellcrash.service 能自动放在正确的位置。这应该是一个BUG，需要修复。

**Comment by juewuy** [comment]
应该是权限不足，请使用root用户执行脚本

**Comment by Maaafty** [comment]
> 应该是权限不足，请使用root用户而不是sudo命令执行脚本

我在使用root用户安装后也出现了这种情况

**Comment by juewuy** [comment]
问题是本地无法复现你描述的问题
