### ISSUE TITLE
[Bug] MetaXD面板，规则页面没有数据。如果你也在使用管理面板，可以看看问题是否存在

### ISSUE THREAD

**Issue by AndyYuenOk** [juewuy/ShellCrash#810]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

![image](https://github.com/user-attachments/assets/b8fb5abb-583c-4933-9412-f65d86072e4d)
版本：1.9.1rc9
MetaXD管理面板
好像是这个接口404导致的，不知道其他版本和设备有没有问题

**Comment by juewuy** [comment]
无法复现，尝试重启内核或更换内核

**Comment by AndyYuenOk** [comment]
换了meta 内核正常了
