### ISSUE TITLE
[Bug] 小米路由器R4A千兆版，开启shellclash后使用https://www.speedtest.cn/测速只有百兆，关闭后恢复千兆

### ISSUE THREAD

**Issue by dddd64693** [juewuy/ShellCrash#811]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

作者好，我的she设备是小米R4A千兆版，使用的openwrt系统，开启clash后，速度变为百兆了，但是端口连接速率仍然是千兆
下图是开启后的测试
![image](https://github.com/user-attachments/assets/d27b2b63-d407-4558-99cc-62d22733fcf4)
下图是日志中的规则
![image](https://github.com/user-attachments/assets/4688f4e6-c4a4-4e89-a6f3-defc75fe25b5)
下图是关闭后的测试
![image](https://github.com/user-attachments/assets/5f614a9e-2d18-4de6-9e92-4e833f0fc423)
下图是clash的设置情况
![image](https://github.com/user-attachments/assets/fdc480f7-4955-4e22-b07d-eefb7cd5e76d)

另外想问一下，自定义规则在哪边可以设置，

**Comment by calvin886886** [comment]
最近也是感受到了打开网页会慢.要多转个2秒的.关掉clash,秒开,也在找原因,试过换dns,关ipv6

**Comment by dddd64693** [comment]
> 最近也是感受到了打开网页会慢.要多转个2秒的.关掉clash,秒开,也在找原因,试过换dns,关ipv6

是的，感觉会不会所有流量都走了 clash

**Comment by juewuy** [comment]
@dddd64693 启用绕过cn

**Comment by flashlab** [comment]
感觉本地局域网流量也会走clash，比如host安装的kodi通过smb打开本地视频列表会很卡，有办法绕过本地流量或者绕过指定app吗？@juewuy

**Comment by juewuy** [comment]
@flashlab 只要你是正常局域网网段默认就不会走，除非你自定义了保留地址段

**Comment by flashlab** [comment]
> 只要你是正常局域网网段默认就不会走，除非你自定义了保留地址段

@juewuy 为了 wireguard 远程连到 host 也能用梯子，确实增加了一个保留地址段，但是跟本地局域网不是一个段，这个会有影响吗？怎么设置既保留地址段也能绕过局域网流量呢？

**Comment by juewuy** [comment]
@flashlab 可以设置多个，把你需要绕过的都加进去

**Comment by carlchina** [comment]
确实 最近打开国内的网站，或者游戏，比如最新的宝可梦大集结 直接卡着进不去，关掉就好了
