### ISSUE TITLE
[Bug] 微信语音加载速度慢

### ISSUE THREAD

**Issue by repairer7** [juewuy/ShellCrash#812]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

目前安装在istoros上，使用singbox内核，代理模式选择混合模式，DNS选用mix模式（内部选择自建的AGH，外部使用fakeip），已启用域名嗅探功能。
表现形式为微信发送语音，接受时候需要加载很久

**Comment by juewuy** [comment]
@repairer7 启用绕过cn或者检查分流策略
