### ISSUE TITLE
[Bug]  crontab: can't change directory to '/opt/var/spool/cron/crontabs': No such file or directory

### ISSUE THREAD

**Issue by El1ter** [juewuy/ShellCrash#813]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

华硕官方固件，1.9.1rc10 版本，安装方式为usb+下载大师。再安装entware以后，sc重启以及进入管理自动脚本选项时都说找不到这个路径。并且管理自动脚本功能也有问题

**Comment by El1ter** [comment]
user@RT-BE86U-F880:/opt# ll -t
lrwxrwxrwx    1 user root            12 Oct 14 23:46 bin -> /tmp/opt/bin/
lrwxrwxrwx    1 user root            12 Oct 14 23:46 doc -> /tmp/opt/doc/
lrwxrwxrwx    1 user root            12 Oct 14 23:46 etc -> /tmp/opt/etc/
lrwxrwxrwx    1 user root            16 Oct 14 23:46 include -> /tmp/opt/include/
lrwxrwxrwx    1 user root            12 Oct 14 23:46 lib -> /tmp/opt/lib/
lrwxrwxrwx    1 user root            13 Oct 14 23:46 sbin -> /tmp/opt/sbin/
lrwxrwxrwx    1 user root            14 Oct 14 23:46 share -> /tmp/opt/share/
lrwxrwxrwx    1 user root            12 Oct 14 23:46 tmp -> /tmp/opt/tmp/
lrwxrwxrwx    1 user root            12 Oct 14 23:46 usr -> /tmp/opt/usr/
lrwxrwxrwx    1 user root             7 Oct 14 23:44 opt -> tmp/opt/
drwxrwxrwx    2 user root           112 Oct 14 23:44 scripts/
/opt 下面都是 指向 /u盘路径/asusware.arm/* 的软链接

**Comment by El1ter** [comment]
我是通过 https://urouter.ru/binary/entware/install.sh 安装了entware后才出现的这个问题，之前好像没出现过

**Comment by juewuy** [comment]
卸载重装一下脚本

**Comment by El1ter** [comment]
> 卸载重装一下脚本

重新卸载安装了以后，问题依旧

**Comment by juewuy** [comment]
@El1ter 那你手动创建一下这个文件目录试试

**Comment by El1ter** [comment]
> @El1ter 那你手动创建一下这个文件目录试试
/opt 是个只读的文件路径，不让创建。好奇怪，不知道这些链接怎么创建出来的

**Comment by juewuy** [comment]
@El1ter 说明装的entware可能有问题

**Comment by El1ter** [comment]
> @El1ter 说明装的entware可能有问题

能详细说说么，我现在用entware已经装上了adguard home，并且与sc已经共存使用了。目前sc就是有这个路径找不到的问题

**Comment by juewuy** [comment]
@El1ter 你可以尝试按照一下entware环境的crontab看能不能解决，另外adg并不是必须用entware才能运行

**Comment by El1ter** [comment]
> @El1ter 你可以尝试按照一下entware环境的crontab看能不能解决，另外adg并不是必须用entware才能运行

我which了一下cronta，发现路径是/opt/bin/crontab，实际上是u盘地址/arus.arm下面 bin/contab -> /opt/bin/busybox的软链接，不知道是干嘛，现在删掉以后，sc掉的是系统cru就好了。不过adg在官固上不用entware还有啥方法可以装?之前试过直接安装，发现etc/init.d下面没有权限，安装失败了

**Comment by juewuy** [comment]
@El1ter 用shellcrash的自动任务拉起或者参考脚本init.sh使用下载大师拉起

**Comment by El1ter** [comment]
> @El1ter 用shellcrash的自动任务拉起或者参考脚本init.sh使用下载大师拉起

好的，我研究下，谢谢喵佬
