### ISSUE TITLE
[Feature] 是否可以支持自定义分流策略或策略组

### ISSUE THREAD

**Issue by myoungself** [juewuy/ShellCrash#814]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

自己有一套quantumultx的策略，想把这个策略转移到shellclash上来，如果支持自定义也可以

**Comment by myoungself** [comment]
不太懂，如果打包里就能修改ShellClash.ini是不是更好？

**Comment by juewuy** [comment]
6-6
