### ISSUE TITLE
[Bug] 红米AX5400Pro电竞版，tun转发需要重启一次clash meta。并且有随机性自动停止问题

### ISSUE THREAD

**Issue by chsid** [juewuy/ShellCrash#815]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

路由器：红米AX5400Pro电竞版
模式：混合模式
内核：clash meta

路由器启动后，udp转发有问题。tailscale连不上。需要手动重启一次内核，问题解决。

已经尝试过用tproxy，延迟启动，问题依旧。必须要手动重启一次内核。

另外，路由器工作一段时间后（几个小时或者一两天），会出现无法上网。排查发现clash meta内核自动停止。手动重启后问题解决。

想问下这个是什么原因导致的？有无解决办法？

**Comment by juewuy** [comment]
@chsid 没办法定位问题，请提供有问题状态下的防火墙内容（8-1-4）

**Comment by chsid** [comment]
root@XiaoQiang:~# iptables -L
Chain INPUT (policy DROP)
target     prot opt source               destination         
ACCEPT     tcp  --  anywhere             localhost           
miot_input  all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere             /* !fw3 */
input_rule  all  --  anywhere             anywhere             /* !fw3: Custom input rule chain */
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED /* !fw3 */
DROP       all  --  anywhere             anywhere             ctstate INVALID /* !fw3 */
syn_flood  tcp  --  anywhere             anywhere             tcp flags:FIN,SYN,RST,ACK/SYN /* !fw3 */
zone_lan_input  all  --  anywhere             anywhere             /* !fw3 */
zone_wan_input  all  --  anywhere             anywhere             /* !fw3 */
zone_guest_input  all  --  anywhere             anywhere             /* !fw3 */
ACCEPT     tcp  --  0.0.0.0/8            anywhere             tcp dpt:9999
ACCEPT     tcp  --  10.0.0.0/8           anywhere             tcp dpt:9999
ACCEPT     tcp  --  127.0.0.0/8          anywhere             tcp dpt:9999
ACCEPT     tcp  --  100.64.0.0/10        anywhere             tcp dpt:9999
ACCEPT     tcp  --  169.254.0.0/16       anywhere             tcp dpt:9999
ACCEPT     tcp  --  172.16.0.0/12        anywhere             tcp dpt:9999
ACCEPT     tcp  --  192.168.0.0/16       anywhere             tcp dpt:9999
ACCEPT     tcp  --  base-address.mcast.net/4  anywhere             tcp dpt:9999
ACCEPT     tcp  --  240.0.0.0/4          anywhere             tcp dpt:9999
REJECT     tcp  --  anywhere             anywhere             tcp dpt:9999 reject-with icmp-port-unreachable
ACCEPT     tcp  --  0.0.0.0/8            anywhere             tcp dpt:7890
ACCEPT     tcp  --  10.0.0.0/8           anywhere             tcp dpt:7890
ACCEPT     tcp  --  127.0.0.0/8          anywhere             tcp dpt:7890
ACCEPT     tcp  --  100.64.0.0/10        anywhere             tcp dpt:7890
ACCEPT     tcp  --  169.254.0.0/16       anywhere             tcp dpt:7890
ACCEPT     tcp  --  172.16.0.0/12        anywhere             tcp dpt:7890
ACCEPT     tcp  --  192.168.0.0/16       anywhere             tcp dpt:7890
ACCEPT     tcp  --  base-address.mcast.net/4  anywhere             tcp dpt:7890
ACCEPT     tcp  --  240.0.0.0/4          anywhere             tcp dpt:7890
REJECT     tcp  --  anywhere             anywhere             tcp dpt:7890 reject-with icmp-port-unreachable

Chain FORWARD (policy DROP)
target     prot opt source               destination         
ACCEPT     all  --  anywhere             anywhere            
DROP       all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere             PHYSDEV match --physdev-is-bridged
forwarding_rule  all  --  anywhere             anywhere             /* !fw3: Custom forwarding rule chain */
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED /* !fw3 */
DROP       all  --  anywhere             anywhere             ctstate INVALID /* !fw3 */
zone_lan_forward  all  --  anywhere             anywhere             /* !fw3 */
zone_wan_forward  all  --  anywhere             anywhere             /* !fw3 */
zone_guest_forward  all  --  anywhere             anywhere             /* !fw3 */

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
ACCEPT     all  --  anywhere             anywhere             /* !fw3 */
output_rule  all  --  anywhere             anywhere             /* !fw3: Custom output rule chain */
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED /* !fw3 */
DROP       all  --  anywhere             anywhere             ctstate INVALID /* !fw3 */
zone_lan_output  all  --  anywhere             anywhere             /* !fw3 */
zone_wan_output  all  --  anywhere             anywhere             /* !fw3 */
zone_guest_output  all  --  anywhere             anywhere             /* !fw3 */

Chain MINIUPNPD (1 references)
target     prot opt source               destination         
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6882
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6883
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6884
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6885
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6886
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6887
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6888
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6889
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6890
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6891
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6892
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6893
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6894
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6895
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6896
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6897
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6898
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6899
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6900
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6901
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6902
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6903
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6904
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6905
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6906
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6907
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6908
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6909
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6910
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6911
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6912
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6913
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6914
ACCEPT     tcp  --  anywhere             192.168.155.230      tcp dpt:38165
ACCEPT     udp  --  anywhere             192.168.155.230      udp dpt:38165
ACCEPT     tcp  --  anywhere             192.168.155.230      tcp dpt:27784
ACCEPT     udp  --  anywhere             192.168.155.230      udp dpt:27784
ACCEPT     tcp  --  anywhere             192.168.155.230      tcp dpt:38473
ACCEPT     udp  --  anywhere             192.168.155.230      udp dpt:38473
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6915
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6916
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6917
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6918
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6919
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6920
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6921
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6922
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6923
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6924
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6925
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6926
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6927
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6928
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6929
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6930
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6931
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6932
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6933
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6934
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6935
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6936
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6937
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6938
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6939
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6940
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6941
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6942
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6943
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6944
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6945
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6946
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6947
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6948
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6949
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6950
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6951
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6952
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6953
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6954
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6955
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6956
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6957
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6958
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6959
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6960
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6961
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6962
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6963
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6964
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6965
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6966
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6967
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6968
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6969
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6970
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6971
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6972
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6973
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6974
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6975
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6976
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6977
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6978
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6979
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6980
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6981
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6982
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6983
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6984
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6985
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6986
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6987
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6988
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6989
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6990
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6991
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6992
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6993
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6994
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6995
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6996
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6997
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6998
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6999
ACCEPT     udp  --  anywhere             192.168.155.28       udp dpt:41641
ACCEPT     udp  --  anywhere             backup.datahub.family  udp dpt:43031
ACCEPT     udp  --  anywhere             backup.datahub.family  udp dpt:42374
ACCEPT     udp  --  anywhere             backup.datahub.family  udp dpt:56907
ACCEPT     udp  --  anywhere             backup.datahub.family  udp dpt:26378
ACCEPT     udp  --  anywhere             backup.datahub.family  udp dpt:19249
ACCEPT     udp  --  anywhere             backup.datahub.family  udp dpt:21270
ACCEPT     udp  --  anywhere             backup.datahub.family  udp dpt:55708
ACCEPT     udp  --  anywhere             backup.datahub.family  udp dpt:52731
ACCEPT     udp  --  anywhere             backup.datahub.family  udp dpt:46484
ACCEPT     udp  --  anywhere             backup.datahub.family  udp dpt:44648
ACCEPT     udp  --  anywhere             backup.datahub.family  udp dpt:61042
ACCEPT     udp  --  anywhere             backup.datahub.family  udp dpt:41641
ACCEPT     udp  --  anywhere             backup.datahub.family  udp dpt:37279
ACCEPT     tcp  --  anywhere             192.168.155.230      tcp dpt:25436
ACCEPT     udp  --  anywhere             backup.datahub.family  udp dpt:45244
ACCEPT     tcp  --  anywhere             backup.datahub.family  tcp dpt:6881
ACCEPT     udp  --  anywhere             backup.datahub.family  udp dpt:6881
ACCEPT     udp  --  anywhere             backup.datahub.family  udp dpt:60034

Chain forwarding_guest_rule (1 references)
target     prot opt source               destination         

Chain forwarding_lan_rule (1 references)
target     prot opt source               destination         

Chain forwarding_ready_rule (1 references)
target     prot opt source               destination         

Chain forwarding_rule (1 references)
target     prot opt source               destination         
macfilter_wan  all  --  anywhere             anywhere            

Chain forwarding_wan_rule (1 references)
target     prot opt source               destination         

Chain input_guest_rule (1 references)
target     prot opt source               destination         

Chain input_lan_rule (1 references)
target     prot opt source               destination         
macfilter_input  all  --  anywhere             anywhere            

Chain input_ready_rule (1 references)
target     prot opt source               destination         

Chain input_rule (1 references)
target     prot opt source               destination         

Chain input_wan_rule (1 references)
target     prot opt source               destination         

Chain macfilter_input (1 references)
target     prot opt source               destination         

Chain macfilter_wan (1 references)
target     prot opt source               destination         

Chain miot_input (1 references)
target     prot opt source               destination         
ACCEPT     udp  --  anywhere             anywhere             udp spt:54321
ACCEPT     udp  --  anywhere             anywhere             udp spts:bootps:bootpc dpts:bootps:bootpc
DROP       all  --  anywhere             anywhere            

Chain output_guest_rule (1 references)
target     prot opt source               destination         

Chain output_lan_rule (1 references)
target     prot opt source               destination         

Chain output_ready_rule (1 references)
target     prot opt source               destination         

Chain output_rule (1 references)
target     prot opt source               destination         

Chain output_wan_rule (1 references)
target     prot opt source               destination         

Chain reject (3 references)
target     prot opt source               destination         
REJECT     tcp  --  anywhere             anywhere             /* !fw3 */ reject-with tcp-reset
REJECT     all  --  anywhere             anywhere             /* !fw3 */ reject-with icmp-port-unreachable

Chain syn_flood (1 references)
target     prot opt source               destination         
RETURN     tcp  --  anywhere             anywhere             tcp flags:FIN,SYN,RST,ACK/SYN limit: avg 25/sec burst 50 /* !fw3 */
DROP       all  --  anywhere             anywhere             /* !fw3 */

Chain zone_guest_dest_ACCEPT (1 references)
target     prot opt source               destination         
ACCEPT     all  --  anywhere             anywhere             /* !fw3 */

Chain zone_guest_dest_REJECT (1 references)
target     prot opt source               destination         
reject     all  --  anywhere             anywhere             /* !fw3 */

Chain zone_guest_forward (1 references)
target     prot opt source               destination         
forwarding_guest_rule  all  --  anywhere             anywhere             /* !fw3: Custom guest forwarding rule chain */
zone_wan_dest_ACCEPT  all  --  anywhere             anywhere             /* !fw3: Zone guest to wan forwarding policy */
ACCEPT     all  --  anywhere             anywhere             ctstate DNAT /* !fw3: Accept port forwards */
zone_guest_dest_REJECT  all  --  anywhere             anywhere             /* !fw3 */

Chain zone_guest_input (1 references)
target     prot opt source               destination         
input_guest_rule  all  --  anywhere             anywhere             /* !fw3: Custom guest input rule chain */
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:8999 /* !fw3: Hello wifi 8999 */
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:8300 /* !fw3: Hello wifi 8300 */
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:7080 /* !fw3: Hello wifi 7080 */
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:domain /* !fw3: Allow Guest DNS Queries */
ACCEPT     udp  --  anywhere             anywhere             udp dpt:domain /* !fw3: Allow Guest DNS Queries */
ACCEPT     udp  --  anywhere             anywhere             udp spts:bootps:bootpc dpts:bootps:bootpc /* !fw3: Allow Guest DHCP request */
ACCEPT     all  --  anywhere             anywhere             ctstate DNAT /* !fw3: Accept port redirections */
zone_guest_src_REJECT  all  --  anywhere             anywhere             /* !fw3 */

Chain zone_guest_output (1 references)
target     prot opt source               destination         
output_guest_rule  all  --  anywhere             anywhere             /* !fw3: Custom guest output rule chain */
zone_guest_dest_ACCEPT  all  --  anywhere             anywhere             /* !fw3 */

Chain zone_guest_src_REJECT (1 references)
target     prot opt source               destination         
reject     all  --  anywhere             anywhere             /* !fw3 */

Chain zone_lan_dest_ACCEPT (2 references)
target     prot opt source               destination         
ACCEPT     all  --  anywhere             anywhere             /* !fw3 */

Chain zone_lan_forward (1 references)
target     prot opt source               destination         
forwarding_lan_rule  all  --  anywhere             anywhere             /* !fw3: Custom lan forwarding rule chain */
zone_wan_dest_ACCEPT  all  --  anywhere             anywhere             /* !fw3: Zone lan to wan forwarding policy */
ACCEPT     all  --  anywhere             anywhere             ctstate DNAT /* !fw3: Accept port forwards */
zone_lan_dest_ACCEPT  all  --  anywhere             anywhere             /* !fw3 */

Chain zone_lan_input (1 references)
target     prot opt source               destination         
input_lan_rule  all  --  anywhere             anywhere             /* !fw3: Custom lan input rule chain */
ACCEPT     all  --  anywhere             anywhere             ctstate DNAT /* !fw3: Accept port redirections */
zone_lan_src_ACCEPT  all  --  anywhere             anywhere             /* !fw3 */

Chain zone_lan_output (1 references)
target     prot opt source               destination         
output_lan_rule  all  --  anywhere             anywhere             /* !fw3: Custom lan output rule chain */
zone_lan_dest_ACCEPT  all  --  anywhere             anywhere             /* !fw3 */

Chain zone_lan_src_ACCEPT (1 references)
target     prot opt source               destination         
ACCEPT     all  --  anywhere             anywhere             /* !fw3 */

Chain zone_ready_dest_ACCEPT (1 references)
target     prot opt source               destination         

Chain zone_ready_dest_DROP (2 references)
target     prot opt source               destination         

Chain zone_ready_forward (0 references)
target     prot opt source               destination         
forwarding_ready_rule  all  --  anywhere             anywhere             /* !fw3: Custom ready forwarding rule chain */
ACCEPT     all  --  anywhere             anywhere             ctstate DNAT /* !fw3: Accept port forwards */
zone_ready_dest_DROP  all  --  anywhere             anywhere             /* !fw3 */

Chain zone_ready_input (0 references)
target     prot opt source               destination         
input_ready_rule  all  --  anywhere             anywhere             /* !fw3: Custom ready input rule chain */
ACCEPT     udp  --  anywhere             anywhere             udp spts:bootps:bootpc dpts:bootps:bootpc /* !fw3: DHCP for ready */
ACCEPT     all  --  anywhere             anywhere             ctstate DNAT /* !fw3: Accept port redirections */
zone_ready_src_DROP  all  --  anywhere             anywhere             /* !fw3 */

Chain zone_ready_output (0 references)
target     prot opt source               destination         
output_ready_rule  all  --  anywhere             anywhere             /* !fw3: Custom ready output rule chain */
zone_ready_dest_ACCEPT  udp  --  anywhere             anywhere             udp spts:bootps:bootpc dpts:bootps:bootpc /* !fw3: DHCP for ready */
zone_ready_dest_DROP  all  --  anywhere             anywhere             /* !fw3 */

Chain zone_ready_src_DROP (1 references)
target     prot opt source               destination         

Chain zone_wan_dest_ACCEPT (3 references)
target     prot opt source               destination         
DROP       all  --  anywhere             anywhere             ctstate INVALID /* !fw3: Prevent NAT leakage */
ACCEPT     all  --  anywhere             anywhere             /* !fw3 */

Chain zone_wan_dest_DROP (1 references)
target     prot opt source               destination         
DROP       all  --  anywhere             anywhere             /* !fw3 */

Chain zone_wan_dest_REJECT (0 references)
target     prot opt source               destination         
reject     all  --  anywhere             anywhere             /* !fw3 */

Chain zone_wan_forward (1 references)
target     prot opt source               destination         
MINIUPNPD  all  --  anywhere             anywhere            
forwarding_wan_rule  all  --  anywhere             anywhere             /* !fw3: Custom wan forwarding rule chain */
ACCEPT     all  --  anywhere             anywhere             ctstate DNAT /* !fw3: Accept port forwards */
zone_wan_dest_DROP  all  --  anywhere             anywhere             /* !fw3 */

Chain zone_wan_input (1 references)
target     prot opt source               destination         
input_wan_rule  all  --  anywhere             anywhere             /* !fw3: Custom wan input rule chain */
ACCEPT     udp  --  anywhere             anywhere             udp dpt:bootpc /* !fw3: Allow-DHCP-Renew */
ACCEPT     icmp --  anywhere             anywhere             icmp echo-request /* !fw3: Allow-Ping */
ACCEPT     all  --  anywhere             anywhere             ctstate DNAT /* !fw3: Accept port redirections */
zone_wan_src_DROP  all  --  anywhere             anywhere             /* !fw3 */

Chain zone_wan_output (1 references)
target     prot opt source               destination         
output_wan_rule  all  --  anywhere             anywhere             /* !fw3: Custom wan output rule chain */
zone_wan_dest_ACCEPT  all  --  anywhere             anywhere             /* !fw3 */

Chain zone_wan_src_DROP (1 references)
target     prot opt source               destination         
DROP       all  --  anywhere             anywhere             /* !fw3 */
root@XiaoQiang:~#
