### ISSUE TITLE
[Feature] 希望更新配置文件时可以用内核更新

### ISSUE THREAD

**Issue by BANG404** [juewuy/ShellCrash#818]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

我配置文件规则链接很多都是github 上面的，需要代理才能成功，希望能像verge一样可以用内核更新
![image](https://github.com/user-attachments/assets/0fcedecf-dfb1-42af-9d48-a04d992dabfe)

**Comment by juewuy** [comment]
@BANG404 一直都是优先使用节点更新
