### ISSUE TITLE
[Feature] 希望可以将配置文件自动重命名后保存

### ISSUE THREAD

**Issue by github-h** [juewuy/ShellCrash#819]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

1.9.1rc10 使用6-2 完整的订阅信息配置功能时部分机场下载的配置文件并没有后缀名 这会导致脚本识别失败并直接打印了整个配置文件

希望能加一个不管获取的配置文件是何种形式，都自动更名为config.yaml并尝试导入

**Comment by juewuy** [comment]
@github-h 一直都是会自动改名

**Comment by github-h** [comment]
> @github-h 一直都是会自动改名

那好奇这是哪里出了问题
![图片](https://github.com/user-attachments/assets/4e3f609d-239a-44ed-ba14-5ced69edf430)
![图片](https://github.com/user-attachments/assets/a16e8901-ba16-4cd5-933b-35cabc02a6ab)

这个配置文件在线订阅就不太行  上传完整配置文件没啥问题
CFW也能正常导入这个配置文件
![图片](https://github.com/user-attachments/assets/8af19fb7-862c-49c9-87a9-391df24f9937)

**Comment by github-h** [comment]
这个是能正常导入的config
![图片](https://github.com/user-attachments/assets/4d9d7530-102e-4e62-b4cc-dbdd12daf6b6)
![图片](https://github.com/user-attachments/assets/b9585bcc-c3fd-4a88-b886-01672c1d17a2)

这个是不能正常导入的config（打印所有节点信息的）
![图片](https://github.com/user-attachments/assets/f2eb7169-acc4-4e69-9d99-9336c1aa2f1b)
![图片](https://github.com/user-attachments/assets/3a08e79a-faa5-4fb8-85a9-5ef1d26b2c72)

怀疑是不是跟节点配置文件的格式有关？一个是多行一个是一行

**Comment by juewuy** [comment]
```
sed -n "/^proxies:/,/^[a-z]/ { /^[a-z]/d; p; }" "$core_config_new" >"$TMPDIR"/proxies.yaml
        if ! grep -q 'server:' "$TMPDIR"/proxies.yaml && ! grep -q 'proxy-providers:' "$core_config_new"; then
```
这是相关的判断逻辑

**Comment by github-h** [comment]
> ```
>     ```
> ```
> 
> sed -n "/^proxies:/,/^[a-z]/ { /^[a-z]/d; p; }" "$core_config_new" >"$TMPDIR"/proxies.yaml if ! grep -q 'server:' "$TMPDIR"/proxies.yaml && ! grep -q 'proxy-providers:' "$core_config_new"; then
> 
> ```
> 这是相关的判断逻辑
> ```

发现问题了 能否改为判断的是 `server` 而不是 `server:`

![图片](https://github.com/user-attachments/assets/98fac876-47f1-4449-8575-376141595db7)
![图片](https://github.com/user-attachments/assets/c721a981-ceae-425a-9b36-06ba857d35d2)

**Comment by juewuy** [comment]
@github-h OK
