### ISSUE TITLE
[Feature] 是否可以开放在fake-ip模式下开启绕过大陆IP的功能

### ISSUE THREAD

**Issue by lvxj11** [juewuy/ShellCrash#820]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

经过测试，配置好fake-ip-filter后，即使是fake-ip模式也是可以实现大部分cnIP正确分流的。
fake-ip-filter可以支持geosite:cn,private这种格式，还有rule-set:格式

**Comment by juewuy** [comment]
后续会适配meta内核mix模式
