### ISSUE TITLE
[Bug] 1.9.1版本带来的奇怪延迟问题【初步判断是”ipv6-DNS解析“默认打开造成的】

### ISSUE THREAD

**Issue by Maozai-Teng** [juewuy/ShellCrash#821]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

我是最近手机在玩公主连结的时候发现的，延迟会特别的长。具体情况是这个游戏在联网的时候，右上角会出现“正在数据连接”的提示（如下图），之前都是1s就过去了，现在延长到起码5~6s。
【对了，因为我开启了cn_ip绕过内核，这个游戏是大陆的服务器，他是不走流量的，也就是在面板的连接里面，并没有这个游戏相关的连接】
![QQ截图20241107205347](https://github.com/user-attachments/assets/19341123-768a-407e-9e10-05ec02c5d32d)

我是完全卸载重新安装1.9.1之后发现的，rc9和最新的rc10都试过，均有这种情况出现。然后我选择直接shellclash里面回滚版本，回去1.9.0，1.8.0都不行，内核是meta，最新的1.18.7和之前的1.18.1都不行，还是必须等待5，6s。

之后我全部卸载，手动下载了github上面的1.9.0和1.8.0版本重新进行本地安装。这时候meta内核不管是选择1.18.1还是1.18.7，都完全正常了，那个提示1s就通过了。（因此排除meta内核自己和内核版本的问题）
我试过完全关闭shellclash，也是正常的，提示闪1s就通过。（因此排除我本身网络和路由器的问题）

到此为止，通过我的对比试验，那就只剩下是最新这个shellclash 1.9.1的问题了，但具体是什么我也不知道_(:3」 ∠）_

本人路由器小米AX3600+软固化，redir模式+redir_host，关闭ipv6，开启cn_ip绕过内核，启用域名嗅探，用的一键配置加密DNS，其他项目均未改动。目前是本地安装的1.9.0+meta1.18.7，问题消失恢复正常，提示1s就过。
![QQ截图20241107204322](https://github.com/user-attachments/assets/77a052ab-da53-4d3c-b4ae-53d2921e53a4)

如果需要我再提供什么信息可以留言~

**Comment by Maozai-Teng** [comment]
好像我自己找到问题所在了，1.9.1rc默认会打开【ipv6-DNS解析】这个选项，关掉就行，可能是我这边ipv6网络不太好？但我其实并没有开ipv6（光猫，路由器和shellclash软件里面我都没开）。我怀疑是他会优先走一遍ipv6的dns解析，发现我没开再走回正常的dns解析，所以导致延迟变大？（不太懂，瞎猜的，不过确实关掉就一切都正常了）
@juewuy 大佬可以来看一下，看看以后版本怎么优化~（并且吐槽一下，这个ipv6设置藏太深了，我本来是在1.9.0之前试验发现了这个问题，但在1.9.1rc找了半天，大佬看看是不是可以改更好一点）
![QQ截图20241114064437](https://github.com/user-attachments/assets/12352ffa-f8ba-4ab6-ac00-55ed865475bf)

**Comment by juewuy** [comment]
这个ipv6DNS解析功能从开发到现在一直都是这样预设的，所以应该不是它的问题
我也遇见过近期部分游戏初始化时网络出现问题导致初始化时间延长或者失败，当我把面板中漏网之鱼切换为直连即可解决
个人怀疑是近期某些云服务提供商启用了新的入口节点导致现有规则无法覆盖

**Comment by Maozai-Teng** [comment]
> 这个ipv6DNS解析功能从开发到现在一直都是这样预设的，所以应该不是它的问题 我也遇见过近期部分游戏初始化时网络出现问题导致初始化时间延长或者失败，当我把面板中漏网之鱼切换为直连即可解决 个人怀疑是近期某些云服务提供商启用了新的入口节点导致现有规则无法覆盖

我又重新安装了1.9.0，确实ipv6DNS解析默认就是打开了，可能我之前关了：）。
不过确实还是如我所说，其他选项都不影响，但打开这个就一定延长，关闭就正常，不管1.9.1，1.9.0还是之前的版本都如此。

然后我也试验了一下你说的把漏网之鱼切直连这个方法，但对我来说无效，一样是延迟加大。可能是因为我开了绕过内核，我的面板里面并没有出现游戏走代理的链接，就更不可能出现走漏网之鱼这个代理了。

所以目前看下来，就只有把ipv6DNS关闭才能解决问题=。=（反正这个功能对我来说没什么作用）
大佬你看看要不要以后把这个默认关闭算了，哈哈哈~

**Comment by 907739769** [comment]
我这边关闭之后，ADGAURD HOME的延迟都低了一些  玄学

**Comment by 907739769** [comment]
> 我这边关闭之后，ADGAURD HOME的延迟都低了一些 玄学

发现是223.5.5.5不稳定  延迟有时候会800ms  有其他加密DNS替换没

**Comment by 907739769** [comment]
![image](https://github.com/user-attachments/assets/dfb3574f-b38d-473b-8954-a826d6a6388b)

**Comment by yangxijun** [comment]
感谢，我这边开了这个后直接上不了外网了，关闭就好。

1.9.0的时候可以，今天升级1.9.1正式版后就不行了，关闭ipv6 dns后又好了
