### ISSUE TITLE
[Bug] 打开绕过CN功能之后Cloudflare异常

### ISSUE THREAD

**Issue by gitcoinkuang** [juewuy/ShellCrash#823]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

打开绕过CN功能之后遇到cloudflare会无限的重复刷新机器人页面，几乎无法验证成功，就好像完全没有代理到cloudflare，但是打开clash连接又可以看到cloudflare.com被代理，f12查看cloudflare的ip是104.22.72.214

脚本里没有开启屏蔽QUIC

**Comment by juewuy** [comment]
没办法定位问题，可以排查一下是否与ipv6相关

**Comment by gitcoinkuang** [comment]
> 没办法定位问题，可以排查一下是否与ipv6相关

我关闭了ipv6也没有用，cloudflare验证的时候我发现是直连，没有通过代理，所以很慢，有时候会成功，我需要怎么提供详细的信息给你呢

**Comment by juewuy** [comment]
@gitcoinkuang 重新生成配置文件，选择合适的规则

**Comment by gitcoinkuang** [comment]
> @gitcoinkuang 重新生成配置文件，选择合适的规则

好的，我还有一个问题，我直接修改/tmp/ShellCrash下的配置文件，发现没有用，重启之后又恢复成原来的

**Comment by juewuy** [comment]
@gitcoinkuang 6-6

**Comment by curryhendry** [comment]
我也是这个问题
