### ISSUE TITLE
I只有一个字节, 为什么可以通过一个字节就可以判断大端还是小端?

### ISSUE THREAD

**Issue by huhu415** [juewuy/ShellCrash#825]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

[echo -n I | hexdump -o 2>/dev/null | awk '{ print substr($2,6,1); exit}'](https://github.com/juewuy/ShellCrash/blob/bfd608b3f8322a3891e2be31cd6de1a6c92f5aa0/scripts/webget.sh#L1202)

我在x86_64试过这个命令, 如下结果, 但我不明白, 为什么I就一个字节也可以判断大端还是小端?
```
root@OpenWrt:~echo -n I | hexdump -o 2>/dev/null
0000000  000111
0000001
```

**Comment by juewuy** [comment]
@huhu415 这个命令仅限mips，x86应该是用不了

**Comment by huhu415** [comment]
那也不对吧 感觉不太对劲哪 大端小端应该是靠分辨高低字节 一个字节应该不行吧

**Comment by juewuy** [comment]
@huhu415 我当初也是网上找的，一直用也没人反馈有问题，具体架构这块我也不清楚

**Comment by huhu415** [comment]
我也在想解决这个问题的办法，奈何找不到大端存储的机器，哎
