### ISSUE TITLE
[Bug] ] 1.9.1rc10 配合AdGuardHome进行域名分流，DNS解析全走到了ShellCrash

### ISSUE THREAD

**Issue by ZhelinCheng** [juewuy/ShellCrash#826]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

在1.9.0无该问题

复现步骤：
1. 安装AdGuardHome 和 ShellCrash；
2. ShellCrash做上游，确认 ShellCrash DNS端口是1053;
3. AdGuardHome 配置DNS设置：
```
[/*.google.com/]127.0.0.1:1053
223.5.5.5
```
4. 使用nslookup 分别解析www.google.com及www.baidu.com，会发现www.baidu.com此时解析正确，www.google.com解析走FAKE-IP也正确（也可能直接复现问题，看第6步）；
5. 重启设备，等待ShellCrash完全启动；
6. 此时重复第4步，发现AdGuardHome 已经失效（是启动成功的，可以到后台），所有的DNS解析都走到了ShellCrash

**Comment by juewuy** [comment]
@ZhelinCheng 做上游为什么不禁用DNS劫持

**Comment by ZhelinCheng** [comment]
> @ZhelinCheng 做上游为什么不禁用DNS劫持

  查看过RC10的所有选项，没有找到相关的设置。可以具体告知禁用DNS劫持的序号吗？

**Comment by juewuy** [comment]
@ZhelinCheng 2-2
