### ISSUE TITLE
[Bug] 通过自定义规则，配置了REJECT，但是发现还是能访问

### ISSUE THREAD

**Issue by persiliao** [juewuy/ShellCrash#827]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

www.parallels.com:443 match DomainKeyword(parallels) using REJECT

这个是面板中的日志显示的，但是还是能访问

**Comment by juewuy** [comment]
@persiliao 这不是本脚本能解决的问题

**Comment by persiliao** [comment]
> @persiliao 这不是本脚本能解决的问题

找了一圈没有找到Clash的源码，大佬有知道Clash的源码链接吗，如果没有我再去找找

**Comment by persiliao** [comment]
或者说现在的Clash的其它的版本客户端编译替换能直接支持吗？

**Comment by juewuy** [comment]
@persiliao 你可以尝试查看日志是否还有其他涉及相关地址的流量，这也不一定是内核问题

**Comment by persiliao** [comment]
> @persiliao 你可以尝试查看日志是否还有其他涉及相关地址的流量，这也不一定是内核问题

好的，我去看看日志先

**Comment by persiliao** [comment]
@juewuy 经过排查，最后发现是华为某个VPN客户端导致的问题，退出了还会影响，重启了才有用，我真的无语
