### ISSUE TITLE
[Bug]加密协议不支持启动报错 error: cipher not supported

### ISSUE THREAD

**Issue by sivenLee** [juewuy/ShellCrash#828]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

服务器配置信息如下，生成的配置文件中cipher=none，启动后报错error: cipher not supported，应该是不支持我的加密和混淆配置，可以添加支持吗？

<img width="317" alt="image" src="https://github.com/user-attachments/assets/3bbb835b-0365-434c-b56e-9ce694590b47">

**Comment by juewuy** [comment]
@sivenLee 更换DNS

**Comment by sivenLee** [comment]
重新安装后又可以了，可能是环境问题
