### ISSUE TITLE
[Bug] CPU使用率百分百

### ISSUE THREAD

**Issue by SunMingZeIt** [juewuy/ShellCrash#829]
### Verify steps

- [x]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### 问题描述
- 近期发现首次启动插件时cpu直接飙满，导致路由器死机重启，因为设置了插件开机启动，路由器来回能重启个3次左右，cpu恢复正常，起初我怀疑是配置问题，但细想如果是硬件配置问题的话应该会一直持续cpu百分比的情况，不应该在重启几次之后恢复正常，不知道是不是和默认的端口有关系，导致暴漏被dos攻击导致？
- 未使用公测版本，不知道和这个有没有关系
### 路由器
- 型号：网件R6100
- 版本：openwrt 23.05.5 (r24106-10cc5fcd00)
- ShellClash命令：export url='https://fastly.jsdelivr.net/gh/juewuy/ShellCrash@master' && wget -q --no-check-certificate -O /tmp/install.sh $url/install.sh  && sh /tmp/install.sh && source /etc/profile &> /dev/null）

**Comment by juewuy** [comment]
@SunMingZeIt 很难定位问题，如果担心存在泄露，可以尝试断网启动

**Comment by qeqeq1** [comment]
你不是一个人，我几个服务器安装clashcore，都出现了不定期的
1.内存占用99%
2.CPU占用99%
3.日志填满硬盘

更搞笑的是有时候只占用单线程的99%，有时候有多核优化一样，四核心能全占满...
