### ISSUE TITLE
[Bug] ipset v6.38: Error in line 1: Set cannot be created: set with the same name already exists

### ISSUE THREAD

**Issue by 907739769** [juewuy/ShellCrash#832]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

ipset v6.38: Error in line 1: Set cannot be created: set with the same name already exists
升级最新版1.9.1 重启报错这个   crash服务是正常的
![image](https://github.com/user-attachments/assets/a0871a62-4ba6-4e59-bed7-6972966b359c)

**Comment by juewuy** [comment]
@907739769 尝试重启一下设备

**Comment by 907739769** [comment]
> @907739769 尝试重启一下设备

重启路由器没有问题了
