### ISSUE TITLE
[Feature] 在线生成服务器能否增加只用本地自建服务器

### ISSUE THREAD

**Issue by maxwelldong** [juewuy/ShellCrash#833]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

你好，能否增加一个选项默认只用本地subconvert自建服务选项，每次更新版本都要手动修改servers.list文件注释掉几个在线生成服务器，如果忘记修改servers.list现在发现内置的几个服务器中的某个好像存在节点泄漏问题，CF每天10万个请求的没多长时间就会被耗光。注释在线生成服务器后就不会存在耗光请求这个问题。

**Comment by juewuy** [comment]
@maxwelldong 自己拼接然后用6-2

**Comment by maxwelldong** [comment]
好的，谢谢，这方法不错
