### ISSUE TITLE
[Feature] 在线配置规则模板可否加入一些dustwin的规则...

### ISSUE THREAD

**Issue by seset** [juewuy/ShellCrash#834]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

dustwin的规则模板分类具体细则每天都在更新,看上去挺不错的, 我想用这一整套ruleset规则,https://proxy-tutorials.dustinwin.top/posts/share-shellcrash-singboxp-ruleset/ 但弄了一整天, 都无法成功用6-2或者6-4生成正确的配置,总是有各种类似下面的错误:
FATAL[0000] start service: initialize rule-set[24]: initial rule-set: cnip: Get 
"https://github.com/DustinWin/ruleset_geodata/releases/download/sing-box-ruleset/cnip.srs": invalid argument | initialize rule-set[24]: initial rule-set: primevideo: Get "https://github.com/DustinWin/ruleset_geodata/releases/download/sing-box-ruleset/primevideo.srs":

原文要求shellcrash 安装到/data文件夹下面,而我使用华硕路由器的data文件夹容量太小,shellcrash只能装到jffs分区, 也不知道报错是否与此相关,.实在无力搞清楚..

**Comment by juewuy** [comment]
@seset 用cdn链接

**Comment by seset** [comment]
多谢,已解决!
