### ISSUE TITLE
[Feature] 1.9.1已绑定域名的局域网地址解析问题

### ISSUE THREAD

**Issue by Fuck996** [juewuy/ShellCrash#838]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

以前用老版本是可以在局域网用域名访问局域网中其它设备的，现在新版本已无法解析dns，请问应该如何解决？

**Comment by Fuck996** [comment]
重新安装后似乎解决了

**Comment by Fuck996** [comment]
> 重新安装后似乎解决了

其实并没有，只是漏网之鱼解析到访问了，关掉漏网之鱼依然无法解析

**Comment by yangmengli** [comment]
![局部截取_20241210_103749](https://github.com/user-attachments/assets/be52929f-737e-4261-a216-19cb9364a937)
我遇到的是第一次启动获取到的代理地址是错的，是dns的地址，手动重启服务又好了

**Comment by yangmengli** [comment]
重启服务后变正常
![局部截取_20241210_104001](https://github.com/user-attachments/assets/8b136a03-d22e-4ffc-9772-6a6c0fb0bce8)

**Comment by juewuy** [comment]
> > 重新安装后似乎解决了
> 
> 其实并没有，只是漏网之鱼解析到访问了，关掉漏网之鱼依然无法解析

内核、DNS模式都提供一下

**Comment by juewuy** [comment]
> ![局部截取_20241210_103749](https://github.com/user-attachments/assets/be52929f-737e-4261-a216-19cb9364a937)
> 我遇到的是第一次启动获取到的代理地址是错的，是dns的地址，手动重启服务又好了

尝试设置自启延迟

**Comment by yangmengli** [comment]
> > ![局部截取_20241210_103749](https://private-user-images.githubusercontent.com/6427961/394083596-be52929f-737e-4261-a216-19cb9364a937.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4MDEwMzQsIm5iZiI6MTczMzgwMDczNCwicGF0aCI6Ii82NDI3OTYxLzM5NDA4MzU5Ni1iZTUyOTI5Zi03MzdlLTQyNjEtYTIxNi0xOWNiOTM2NGE5MzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTBUMDMxODU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDc5YmQwZTI3Y2YyYzdjNDFmNDcwMjVmYjI1Y2Q3ODVhMTIwYmE1YzE3NGYxNDQ2YzhmZGM3MGI4Y2EzMTNjNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.hdzrTs9RTzH21kifSbb-7d7UNJCYhDYemISN8Goz_gY)
> > 我遇到的是第一次启动获取到的代理地址是错的，是dns的地址，手动重启服务又好了
> 
> 尝试设置自启延迟

设置了延时启动，问题还是存在，不知道和我在docker里运行是否有关，我是在docker里运行一个openwrt,然后安装的shellcrash
