### ISSUE TITLE
[Feature] 更新1.91版本后无法打开9999端口的ui界面

### ISSUE THREAD

**Issue by karaongithub** [juewuy/ShellCrash#841]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

 更新1.91版本后无法打开9999端口的ui界面

**Comment by juewuy** [comment]
清理浏览器缓存或者Ctrl加f5强制刷新

**Comment by karaongithub** [comment]
> 清理浏览器缓存或者Ctrl加f5强制刷新
不是这个问题  没有用   查看  系统 没有9999的端口 ui后台 没有运行

**Comment by juewuy** [comment]
@karaongithub 是否使用了自定义配置文件

**Comment by juewuy** [comment]
@Arispex 尝试更换内核

**Comment by Arispex** [comment]
> @Arispex 尝试更换内核

已经解决了，是我的问题，忘记在路径 `/ui` 了

**Comment by karaongithub** [comment]
> @karaongithub 是否使用了自定义配置文件

怎么 查看呢  现在9999端口 进入了  还剩不能 实现有流量通过

**Comment by karaongithub** [comment]
> > @karaongithub 是否使用了自定义配置文件
> 
> 怎么 查看呢 现在9999端口 进入了 还剩不能 实现有流量通过

终于解决了   没有设置过 不知道怎么9999端口和7890端口自动被墙了，手动放行 ，就恢复正常使用了。
