### ISSUE TITLE
[Bug] ipv6测试不通过

### ISSUE THREAD

**Issue by 907739769** [juewuy/ShellCrash#842]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

切换到meta内核，使用的vless协议，TProxy模式，fakeip模式，能正常通过测试

切换到redir就不能通过测试了

**Comment by juewuy** [comment]
@907739769 redir模式需要启用ipv6转发且需要设备防火墙支持

**Comment by 907739769** [comment]
> @907739769 redir模式需要启用ipv6转发且需要设备防火墙支持

说错了  是DNS模式是redir就不行  fakeip就行              是怎么转发   设置里面有吗   crash设置里面的IPV6相关的设置都是未启用

**Comment by 907739769** [comment]
路由器是红米AX6000

**Comment by 907739769** [comment]
![image](https://github.com/user-attachments/assets/c0377e74-dd1f-43c9-b3cd-b3f472646f23)
![image](https://github.com/user-attachments/assets/cb5e864a-718a-4f5d-b981-f0e91839d468)

**Comment by juewuy** [comment]
@907739769 都改成启用

**Comment by 907739769** [comment]
> @907739769 都改成启用

vps不支持ipv6

**Comment by juewuy** [comment]
@907739769 不支持为什么你fakeip模式能通过测试

**Comment by 907739769** [comment]
ipv6都改成已启用  可以了

**Comment by 907739769** [comment]
> @907739769 不支持为什么你fakeip模式能通过测试

vps只有v4地址  我也不清楚到底支不支持，，
