### ISSUE TITLE
[Bug] 1.9.1虚拟内存占用爆表

### ISSUE THREAD

**Issue by saury** [juewuy/ShellCrash#843]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

PID  PPID USER     STAT   VSZ %VSZ %CPU COMMAND
32095     1 root     S     763m 194%   4% /tmp/ShellCrash/CrashCore -d /data/Sh

设备：ax3600
脚本：1.9.1 stable
内核：v1.7.1

**Comment by juewuy** [comment]
@saury 任何版本都是一样的，无视即可
