### ISSUE TITLE
[Bug] ax3600软固化ssh密码被还原为sn码计算密码

### ISSUE THREAD

**Issue by foreverlong** [juewuy/ShellCrash#844]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

ax3600软固化ssh密码被还原为sn码计算密码，而不是自己输入的密码（在shellcrash.cfg里）

**Comment by juewuy** [comment]
@foreverlong 重新软固化并且按提示输入密码
