### ISSUE TITLE
[Bug] Clash服务自动停止，运行一段时间后状态就变成了 "没有运行（Redir模式）"

### ISSUE THREAD

**Issue by woomartin** [juewuy/ShellCrash#846]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用公测版本测试过，问题依旧存在 I have tested using the test mod, and the issue still exists. 
- [X]  我已经仔细看过 [常见问题](https://juewuy.github.io/chang-jian-wen-ti/) 并无法自行解决问题 

### Description

两台Openwrt路由器都存在这个问题
一台 Linux GL-MT6000 5.4.238 #0 SMP Thu Sep 5 02:05:53 2024 aarch64 GNU/Linux
一台 小米4A千兆版 

代理 vless协议，路由器是无线中继模式
国内网站访问一直正常，代理有时候半天停止一次，有时半小时停止一次。

**Comment by juewuy** [comment]
@woomartin 尝试更换内核，或者更换性能更强的设备

**Comment by woomartin** [comment]
一台 Linux GL-MT6000 5.4.238 #0 SMP Thu Sep 5 02:05:53 2024 aarch64 GNU/Linux
好的，这一台配置很好，内存1G，存储8G。应该和性能无关，我切换下内核试试。

**Comment by woomartin** [comment]
5-4-1 找到了这个日志，感觉是网络不稳定的原因自动停止了，有办法处理吗
-----------------------------------------------
2024-12-16_13:04:28~当前设备无法连接网络，已停止启动！
2024-12-16_13:54:26~ShellCrash服务已启动！

**Comment by juewuy** [comment]
@woomartin 这是开机启动时的校验，和你的问题应该没关系

**Comment by saury** [comment]
手上的ax3600最近升了最新的1.9.1也频繁出现同样的问题，一天要好几次，而且还会导致家里所有设备无法上网，感觉像是dns解析出了问题，必须要手动重启下clash才能正常

**Comment by juewuy** [comment]
@saury 请在出现问题时查看面板日志或者查看脚本防火墙设置

**Comment by saury** [comment]
> @saury 请在出现问题时查看面板日志或者查看脚本防火墙设置

防火墙设置没改过，服务都停了，到哪里看日志呢？

**Comment by juewuy** [comment]
@saury 网页面板，防火墙用8-1-4查看

**Comment by saury** [comment]
@juewuy 服务都停了，网页面板自然404了。
8-1-4执行之后什么都没有
```
这里是测试命令菜单
如遇问题尽量运行相应命令后截图提交issue或TG讨论组
-----------------------------------------------
 1 Debug模式运行内核
 2 查看系统DNS端口(:53)占用 
 3 测试ssl加密(aes-128-gcm)跑分
 4 查看ShellCrash相关路由规则
 5 查看内核配置文件前40行
 6 测试代理服务器连通性(google.tw)
-----------------------------------------------
 0 返回上级目录！
请输入对应数字 > 4
root@XiaoQiang:~# 
```

**Comment by juewuy** [comment]
@saury 8-3呢？什么设备？内核版本？

**Comment by saury** [comment]
@juewuy 8-3-1看了下暂时看不出什么问题，下面“已启动”这条应该是停止后手动执行的记录，别的除了一条同步时间都是保存面板配置：
```
2024-12-20_15:20:00~任务【运行时每10分钟自动保存面板配置】执行成功
2024-12-20_15:20:33~任务【服务启动后自动同步ntp时间】执行成功
2024-12-20_15:20:37~ShellCrash服务已启动！
2024-12-20_15:30:01~任务【运行时每10分钟自动保存面板配置】执行成功
```
设备是小米的ax3600，其他信息：
```
当前目录(/data/ShellCrash)剩余空间：11.6M
-----------------------------------------------
 1 更新管理脚本    1.9.1 > 1.9.1 
 2 切换内核文件    v1.7.1 > v1.7.1
 3 更新数据库文件       > 20241130
```

**Comment by juewuy** [comment]
@saury 你先换保守模式吧，看不出问题，也不像是内存

**Comment by juewuy** [comment]
@SuuKomura 尝试用meta内核或者切换保守模式

**Comment by joezhouchenye** [comment]
昨天刚装的，小米AC2100，一样的问题。改成了tcp用redir，udp用tun，自动提示装了meta，然后启动也改成了保守。感觉实际还是自动停止，现象是正常访问着，突然访问谷歌啥的都变成了refused connection，然后1,2分钟又好了。保守模式的意思是定时检测自动重开吗？

**Comment by juewuy** [comment]
@joezhouchenye 设备内存太低

**Comment by saury** [comment]
> @saury 你先换保守模式吧，看不出问题，也不像是内存

@juewuy  感觉有比较严重的内存溢出问题，开保守模式之后两天确实没再断网，但今天又出现相同问题，路由器ssh进去巨卡无比，kill掉clash进程后就瞬间流畅了。
```
 8868     1 root     S     764m 194%   1% /tmp/ShellCrash/CrashCore -d /data/Sh
```
不知道是不是这个内存高占用的原因，前段时间还开过相关issue。

**Comment by juewuy** [comment]
@saury 如果出现类似问题请优先结合当时的面板连接及日志排查

**Comment by saury** [comment]
> @saury 如果出现类似问题请优先结合当时的面板连接及日志排查

看过日志，没有任何线索，难道是ax3600的512 ram太小了吗

**Comment by juewuy** [comment]
@saury 尽量在卡顿时候观察连接数是否有异常

**Comment by woomartin** [comment]
我后续使用了debug模式运行就没断了，搞不明白什么原因，可以尝试下。
![image](https://github.com/user-attachments/assets/5b107cb2-4753-46f1-be78-da560024f0b0)

**Comment by curryhendry** [comment]
我的也会不定时的掉线，主要是会影响整个网络的上网，基本掉线就是半断网的状态。
以我的能力估计也判断不出来原由。
不知道是否有办法可以检测断线同时自动恢复启动。

**Comment by lianjie1355** [comment]
我的小米BE6500 pro 也有这个问题,内网正常没事 ,ShellCrash过个一两个小时就掉线 断流.不知道是哪的问题?

**Comment by saury** [comment]
> 我的小米BE6500 pro 也有这个问题,内网正常没事 ,ShellCrash过个一两个小时就掉线 断流.不知道是哪的问题?

退回到1.8吧，我折腾了好久，退回去一切都正常了

**Comment by DDKK1070** [comment]
> > 我的小米BE6500 pro 也有这个问题,内网正常没事 ,ShellCrash过个一两个小时就掉线 断流.不知道是哪的问题?
> 
> 退回到1.8吧，我折腾了好久，退回去一切都正常了

我也想回退到1.8但是在内置的回退里无法下载老meta内核，请问下您是怎么解决的
